// Second opinion on GPU/TS terrain parity, built to disagree with
// client/scripts/gpuTerrainParity.mjs wherever it can.
//
//   expected  an integer reference written from the spec, not drawnGroundHeight
//   measured  the real gpuTerrainMaterial rasterised top-down, one pixel per
//             subcell, vertex-stage height read back through a float target
//   driven    by the page posting results back, not by CDP evaluate
//
// Mutants deform the shipped material and must be caught, so a pass is not
// vacuous. Layered columns are refused rather than silently compared.
import { execFileSync, spawn } from 'node:child_process';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createServer as createViteServer } from 'vite';
import { resolveChromeHeadlessShell } from './chromeHeadlessShell.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '../..');
const CLIENT_ROOT = resolve(HERE, '..');

// ---------------------------------------------------------------------------
// The spec, implemented from scratch. Nothing here is imported from shared/.
// ---------------------------------------------------------------------------

const REF_LATTICE_N = 4;
const REF_SUBCELL_DENOM = 2 * REF_LATTICE_N;
const REF_BAND_HEIGHT = 16;
const REF_BAND_BLEND_DENOM = REF_SUBCELL_DENOM * REF_SUBCELL_DENOM * REF_BAND_HEIGHT;
const REF_CHUNK_SIZE = 16;
const REF_MIN_HEIGHT = -1536;
const REF_MAX_HEIGHT = 1024;
const REF_CELL_WORLD_SIZE = 1 / 4;
const REF_CELL_CENTRE_OFFSET = 0.5;

const SUBDIV_NEAR = 4;
const SUBDIV_FAR = 1;

function refFloorDiv(a, b) {
  const q = Math.floor(a / b);
  return q * b > a ? q - 1 : q;
}

function refClampCoord(size, coord) {
  return coord > 0 ? (coord < size ? coord : size) : 0;
}

function refClampCell(size, i) {
  return i < 0 ? 0 : i > size - 1 ? size - 1 : i;
}

function refAxis(size, coord) {
  const c = refClampCoord(size, coord);
  const q = 2 * Math.floor(c * REF_LATTICE_N) + 1 - REF_LATTICE_N;
  const base = refFloorDiv(q, REF_SUBCELL_DENOM);
  return {
    i0: refClampCell(size, base),
    i1: refClampCell(size, base + 1),
    f: q - base * REF_SUBCELL_DENOM,
  };
}

function refSurfaceHeight(cells, size, x, y, floorDiv = refFloorDiv) {
  const ax = refAxis(size, x);
  const ay = refAxis(size, y);
  const d = REF_SUBCELL_DENOM;
  const numerator =
    (d - ax.f) * (d - ay.f) * cells[ay.i0 * size + ax.i0] +
    ax.f * (d - ay.f) * cells[ay.i0 * size + ax.i1] +
    (d - ax.f) * ay.f * cells[ay.i1 * size + ax.i0] +
    ax.f * ay.f * cells[ay.i1 * size + ax.i1];
  return floorDiv(numerator, REF_BAND_BLEND_DENOM) * REF_BAND_HEIGHT;
}

/** Deliberately wrong: truncates toward zero, the classic negative-height trap. */
function truncDiv(a, b) {
  return Math.trunc(a / b);
}

// ---------------------------------------------------------------------------
// Deterministic maps, generated by the same source text in Node and in the page.
// ---------------------------------------------------------------------------

const MAP_LCG_MULTIPLIER = 1103515245;
const MAP_LCG_INCREMENT = 12345;
const MAP_LCG_MODULUS = 2 ** 31;
const MAP_SEED_MIX = 2654435761;
const RAMP_X_STRIDE = 7;
const RAMP_Y_STRIDE = 13;

function buildMapCells(kind, size, minHeight, maxHeight, bandHeight) {
  const cells = new Int16Array(size * size);
  let state = (size * MAP_SEED_MIX) % MAP_LCG_MODULUS;
  for (let i = 0; i < cells.length; i++) {
    state = (state * MAP_LCG_MULTIPLIER + MAP_LCG_INCREMENT) % MAP_LCG_MODULUS;
    if (kind === 'ramp') {
      const x = i % size;
      const y = (i - x) / size;
      const stride = (x * RAMP_X_STRIDE + y * RAMP_Y_STRIDE) * bandHeight;
      cells[i] = minHeight + (stride % (maxHeight - minHeight + 1));
    } else if (kind === 'negative') {
      cells[i] = minHeight + (state % (-bandHeight - minHeight + 1));
    } else {
      cells[i] = minHeight + (state % (maxHeight - minHeight + 1));
    }
  }
  return cells;
}

const MAP_BUILDER_SOURCE = `${buildMapCells.toString()}
const MAP_LCG_MULTIPLIER = ${MAP_LCG_MULTIPLIER};
const MAP_LCG_INCREMENT = ${MAP_LCG_INCREMENT};
const MAP_LCG_MODULUS = ${MAP_LCG_MODULUS};
const MAP_SEED_MIX = ${MAP_SEED_MIX};
const RAMP_X_STRIDE = ${RAMP_X_STRIDE};
const RAMP_Y_STRIDE = ${RAMP_Y_STRIDE};`;

// ---------------------------------------------------------------------------
// Cases and mutants.
// ---------------------------------------------------------------------------

const SMALL_CHUNKS_PER_EDGE = 4;
const SMALL_SIZE = REF_CHUNK_SIZE * SMALL_CHUNKS_PER_EDGE;
const LARGE_SIZE = 2048;
const LARGE_CHUNKS_PER_EDGE = LARGE_SIZE / REF_CHUNK_SIZE;
const WINDOW_CHUNKS = 2;
const LARGE_CORNER_CHUNK0 = LARGE_CHUNKS_PER_EDGE - WINDOW_CHUNKS;
const LARGE_MID_CHUNK0 = LARGE_CHUNKS_PER_EDGE / 2;

const smallCase = (name, kind, subdiv) => ({
  name,
  kind,
  subdiv,
  size: SMALL_SIZE,
  cx0: 0,
  cy0: 0,
  chunks: SMALL_CHUNKS_PER_EDGE,
});

const largeCase = (name, kind, subdiv, chunk0) => ({
  name,
  kind,
  subdiv,
  size: LARGE_SIZE,
  cx0: chunk0,
  cy0: chunk0,
  chunks: WINDOW_CHUNKS,
});

const CASES = [
  smallCase('mixed 64 near', 'mixed', SUBDIV_NEAR),
  smallCase('negative 64 near', 'negative', SUBDIV_NEAR),
  smallCase('ramp 64 near', 'ramp', SUBDIV_NEAR),
  smallCase('mixed 64 far', 'mixed', SUBDIV_FAR),
  smallCase('negative 64 far', 'negative', SUBDIV_FAR),
  largeCase('mixed 2048 corner near', 'mixed', SUBDIV_NEAR, LARGE_CORNER_CHUNK0),
  largeCase('mixed 2048 corner far', 'mixed', SUBDIV_FAR, LARGE_CORNER_CHUNK0),
  largeCase('negative 2048 corner near', 'negative', SUBDIV_NEAR, LARGE_CORNER_CHUNK0),
  largeCase('mixed 2048 mid near', 'mixed', SUBDIV_NEAR, LARGE_MID_CHUNK0),
  largeCase('mixed 2048 mid far', 'mixed', SUBDIV_FAR, LARGE_MID_CHUNK0),
  largeCase('mixed 2048 origin far', 'mixed', SUBDIV_FAR, 0),
];

/** Deformations of the shipped material that must move the drawn surface. */
const MUTANTS = [
  { key: 'shiftSubcell', caseName: 'mixed 64 near' },
  { key: 'shiftSubcell', caseName: 'mixed 64 far' },
  { key: 'dropHalfCell', caseName: 'mixed 64 far' },
  { key: 'truncDiv', caseName: 'negative 64 near' },
];

/** Known slack: at subdivision 4 the half-subcell offset never crosses a lattice edge. */
const SLACK_MUTANTS = [{ key: 'dropHalfCell', caseName: 'mixed 64 near' }];

const caseByName = (name) => {
  const found = CASES.find((c) => c.name === name);
  if (found === undefined) throw new Error(`no case named ${name}`);
  return found;
};

const JOBS = [
  ...CASES.map((c) => ({ ...c, label: c.name, mutate: null, slack: false })),
  ...[...MUTANTS, ...SLACK_MUTANTS].map((m) => ({
    ...caseByName(m.caseName),
    label: `mutant ${m.key} / ${m.caseName}`,
    mutate: m.key,
    slack: SLACK_MUTANTS.some((s) => s.key === m.key && s.caseName === m.caseName),
  })),
];

const mapCache = new Map();
function mapFor(kind, size) {
  const key = `${kind}:${size}`;
  let cells = mapCache.get(key);
  if (cells === undefined) {
    cells = buildMapCells(kind, size, REF_MIN_HEIGHT, REF_MAX_HEIGHT, REF_BAND_HEIGHT);
    mapCache.set(key, cells);
  }
  return cells;
}

const sideOf = (job) => job.chunks * REF_CHUNK_SIZE * job.subdiv;

function sampleCellCoord(chunk0, pixel, subdiv) {
  return chunk0 * REF_CHUNK_SIZE + (pixel + 0.5) / subdiv;
}

function expectedForCase(testCase, floorDiv) {
  const cells = mapFor(testCase.kind, testCase.size);
  const side = sideOf(testCase);
  const out = new Int32Array(side * side);
  for (let py = 0; py < side; py++) {
    const y = sampleCellCoord(testCase.cy0, py, testCase.subdiv);
    for (let px = 0; px < side; px++) {
      const x = sampleCellCoord(testCase.cx0, px, testCase.subdiv);
      out[py * side + px] = refSurfaceHeight(cells, testCase.size, x, y, floorDiv);
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// Page: real geometry, real material, float readback of the drawn surface.
// ---------------------------------------------------------------------------

const PROBE_COVERED_FLAG = 1;
const CAMERA_HEIGHT_WORLD = 64;
const CAMERA_NEAR_WORLD = 1;
const CAMERA_FAR_WORLD = 256;
const INSTANCE_COMPONENTS = 2;
const META_ROUTE = '/probe-meta';
const HEIGHTS_ROUTE = '/probe-heights';

const PROBE_PAGE = `<!doctype html><meta charset="utf-8"><title>independent gpu terrain parity</title>
<script type="module" src="/probe.js"></script>`;

const PROBE_SCRIPT = `
import * as THREE from 'three';
import { createChunkTemplate, createGpuTerrainMaterial } from 'gpuTerrainMaterial';
import { createBandPaletteTexture, createHeightTexture } from 'gpuTerrainTextures';

${MAP_BUILDER_SOURCE}

const JOBS = ${JSON.stringify(JOBS)};
const CHUNK_SIZE = ${REF_CHUNK_SIZE};
const CELL_WORLD_SIZE = ${REF_CELL_WORLD_SIZE};
const CELL_CENTRE_OFFSET = ${REF_CELL_CENTRE_OFFSET};
const MIN_HEIGHT = ${REF_MIN_HEIGHT};
const MAX_HEIGHT = ${REF_MAX_HEIGHT};
const BAND_HEIGHT = ${REF_BAND_HEIGHT};
const COVERED_FLAG = ${PROBE_COVERED_FLAG};
const CAMERA_HEIGHT = ${CAMERA_HEIGHT_WORLD};
const CAMERA_NEAR = ${CAMERA_NEAR_WORLD};
const CAMERA_FAR = ${CAMERA_FAR_WORLD};
const INSTANCE_COMPONENTS = ${INSTANCE_COMPONENTS};

const PROBE_VARYING = 'flat varying float vProbeHeight;\\n';
const VERTEX_ANCHOR = '#include <project_vertex>';
const FRAGMENT_ANCHOR = '#include <dithering_fragment>';

/** Each deforms the shipped material so a clean run proves the check bites. */
const MUTATIONS = {
  dropHalfCell: ['(subIJ + 0.5) / uSubdiv', '(subIJ) / uSubdiv'],
  shiftSubcell: ['(subIJ + 0.5) / uSubdiv', '(subIJ + 1.5) / uSubdiv'],
  truncDiv: ['return q * b > a ? q - 1 : q;', 'return q;'],
};

function splice(source, anchor, replacement) {
  if (!source.includes(anchor)) throw new Error('probe anchor missing: ' + anchor);
  return source.replace(anchor, replacement);
}

const errors = [];
window.addEventListener('error', (e) => errors.push(String(e.message)));
window.addEventListener('unhandledrejection', (e) => errors.push(String(e.reason)));

const canvas = document.createElement('canvas');
const renderer = new THREE.WebGLRenderer({ canvas, antialias: false });
renderer.outputColorSpace = THREE.LinearSRGBColorSpace;
renderer.toneMapping = THREE.NoToneMapping;
renderer.setClearColor(0x000000, 1);

function probeMaterial(uniforms, subdiv, mutate) {
  const material = createGpuTerrainMaterial({ ...uniforms, uSubdiv: { value: subdiv } });
  const base = material.onBeforeCompile.bind(material);
  material.onBeforeCompile = (shader, r) => {
    base(shader, r);
    let vs = PROBE_VARYING + shader.vertexShader;
    if (mutate !== null) {
      const [anchor, replacement] = MUTATIONS[mutate];
      if (!vs.includes(anchor)) throw new Error('mutation anchor missing: ' + mutate);
      vs = vs.replace(anchor, replacement);
    }
    shader.vertexShader = splice(vs, VERTEX_ANCHOR, 'vProbeHeight = float(heightHere);\\n  ' + VERTEX_ANCHOR);
    shader.fragmentShader = splice(
      PROBE_VARYING + shader.fragmentShader,
      FRAGMENT_ANCHOR,
      'gl_FragColor = vec4(vProbeHeight, ' + COVERED_FLAG.toFixed(1) + ', 0.0, 1.0);',
    );
  };
  material.customProgramCacheKey = () => 'independent-probe|' + subdiv + '|' + String(mutate);
  return material;
}

const cellCoordToWorld = (c) => (c - CELL_CENTRE_OFFSET) * CELL_WORLD_SIZE;

let loaded = null;

function load(kind, size) {
  if (loaded !== null) loaded.height.dispose();
  const map = {
    size,
    cells: buildMapCells(kind, size, MIN_HEIGHT, MAX_HEIGHT, BAND_HEIGHT),
    columnSpans: new Map(),
  };
  loaded = { key: kind + ':' + size, map, height: createHeightTexture(map) };
  return loaded.map.columnSpans.size;
}

function probe(job) {
  const uniforms = {
    uHeight: { value: loaded.height.texture },
    uPalette: { value: createBandPaletteTexture() },
    uSizeCells: { value: loaded.map.size },
    uSmooth: { value: 1 },
  };
  const { geometry } = createChunkTemplate(job.subdiv);
  const count = job.chunks * job.chunks;
  const origins = new THREE.InstancedBufferAttribute(
    new Float32Array(count * INSTANCE_COMPONENTS),
    INSTANCE_COMPONENTS,
  );
  for (let j = 0; j < job.chunks; j++) {
    for (let i = 0; i < job.chunks; i++) {
      const slot = (j * job.chunks + i) * INSTANCE_COMPONENTS;
      origins.array[slot] = (job.cx0 + i) * CHUNK_SIZE;
      origins.array[slot + 1] = (job.cy0 + j) * CHUNK_SIZE;
    }
  }
  geometry.setAttribute('aChunk', origins);
  geometry.instanceCount = count;

  const material = probeMaterial(uniforms, job.subdiv, job.mutate);
  const mesh = new THREE.Mesh(geometry, material);
  mesh.frustumCulled = false;
  const scene = new THREE.Scene();
  scene.add(mesh);

  const cellSpan = job.chunks * CHUNK_SIZE;
  const side = cellSpan * job.subdiv;
  const half = (cellSpan * CELL_WORLD_SIZE) / 2;
  const centreX = cellCoordToWorld(job.cx0 * CHUNK_SIZE) + half;
  const centreZ = cellCoordToWorld(job.cy0 * CHUNK_SIZE) + half;
  // Top and bottom are swapped so readback row 0 is the low-Z edge.
  const camera = new THREE.OrthographicCamera(-half, half, -half, half, CAMERA_NEAR, CAMERA_FAR);
  camera.position.set(centreX, CAMERA_HEIGHT, centreZ);
  camera.rotation.set(-Math.PI / 2, 0, 0);
  camera.updateMatrixWorld(true);
  camera.updateProjectionMatrix();

  const target = new THREE.WebGLRenderTarget(side, side, {
    format: THREE.RGBAFormat,
    type: THREE.FloatType,
    minFilter: THREE.NearestFilter,
    magFilter: THREE.NearestFilter,
    depthBuffer: true,
    stencilBuffer: false,
  });
  renderer.setRenderTarget(target);
  renderer.clear(true, true, false);
  renderer.render(scene, camera);
  const raw = new Float32Array(side * side * 4);
  renderer.readRenderTargetPixels(target, 0, 0, side, side, raw);
  renderer.setRenderTarget(null);
  target.dispose();
  geometry.dispose();
  material.dispose();
  uniforms.uPalette.value.dispose();

  const heights = new Float32Array(side * side);
  let uncovered = 0;
  for (let i = 0; i < heights.length; i++) {
    if (raw[i * 4 + 1] !== COVERED_FLAG) uncovered++;
    heights[i] = raw[i * 4];
  }
  return { heights, uncovered, side };
}

function rendererName() {
  const gl = renderer.getContext();
  const ext = gl.getExtension('WEBGL_debug_renderer_info');
  return ext ? gl.getParameter(ext.UNMASKED_RENDERER_WEBGL) : gl.getParameter(gl.RENDERER);
}

(async () => {
  const meta = { renderer: '', jobs: [], errors, fatal: null };
  const blocks = [];
  try {
    meta.renderer = rendererName();
    for (const job of JOBS) {
      const key = job.kind + ':' + job.size;
      const layered = loaded !== null && loaded.key === key ? 0 : load(job.kind, job.size);
      if (layered !== 0) throw new Error('layered columns present; this reference covers unlayered only');
      const result = probe(job);
      meta.jobs.push({ label: job.label, side: result.side, uncovered: result.uncovered });
      blocks.push(result.heights);
    }
  } catch (error) {
    meta.fatal = String((error && error.stack) || error);
  }
  let total = 0;
  for (const b of blocks) total += b.length;
  const flat = new Float32Array(total);
  let offset = 0;
  for (const b of blocks) {
    flat.set(b, offset);
    offset += b.length;
  }
  await fetch(${JSON.stringify(META_ROUTE)}, { method: 'POST', body: JSON.stringify(meta) });
  await fetch(${JSON.stringify(HEIGHTS_ROUTE)}, { method: 'POST', body: flat.buffer });
})();
`;

// ---------------------------------------------------------------------------
// Harness plumbing.
// ---------------------------------------------------------------------------

const RUN_TIMEOUT_MS = 600_000;
const POLL_INTERVAL_MS = 250;
const CDP_PORT_BASE = 9900;
const CDP_PORT_SPREAD = 200;
const FLOAT_BYTES = 4;
const WINDOWS_CHROME_PATH = '/mnt/c/Program Files/Google/Chrome/Application/chrome.exe';
const WINDOWS_TEMP_WSL_PATH = '/mnt/c/Users/shawn/AppData/Local/Temp';
const WINDOWS_TEMP_DOS_PATH = 'C:\\Users\\shawn\\AppData\\Local\\Temp';
const WINDOWS_PROFILE_PREFIX = 'terrace-gpu-parity-indep-';

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function readBody(req) {
  return new Promise((res, rej) => {
    const chunks = [];
    req.on('data', (c) => chunks.push(c));
    req.on('end', () => res(Buffer.concat(chunks)));
    req.on('error', rej);
  });
}

function wslHostIp() {
  const out = execFileSync('ip', ['-o', '-4', 'addr', 'show', 'eth0'], { encoding: 'utf8' });
  const match = /inet (\d+\.\d+\.\d+\.\d+)/.exec(out);
  if (match === null) throw new Error('no IPv4 address on eth0');
  return match[1];
}

async function startVite(scratch, inbox) {
  writeFileSync(join(scratch, 'index.html'), PROBE_PAGE);
  writeFileSync(join(scratch, 'probe.js'), PROBE_SCRIPT);
  const server = await createViteServer({
    configFile: false,
    root: scratch,
    logLevel: 'error',
    appType: 'mpa',
    optimizeDeps: { noDiscovery: true, include: [] },
    plugins: [
      {
        name: 'probe-inbox',
        configureServer(dev) {
          dev.middlewares.use(META_ROUTE, (req, res) => {
            readBody(req).then((body) => {
              inbox.resolveMeta(JSON.parse(body.toString('utf8')));
              res.end('ok');
            });
          });
          dev.middlewares.use(HEIGHTS_ROUTE, (req, res) => {
            readBody(req).then((body) => {
              inbox.resolveHeights(
                new Float32Array(
                  body.buffer.slice(body.byteOffset, body.byteOffset + body.byteLength),
                ),
              );
              res.end('ok');
            });
          });
        },
      },
    ],
    resolve: {
      alias: {
        three: join(CLIENT_ROOT, 'node_modules/three/build/three.module.js'),
        '@terrace/shared': join(REPO_ROOT, 'shared/src/index.ts'),
        gpuTerrainMaterial: join(CLIENT_ROOT, 'src/render/gpuTerrainMaterial.ts'),
        gpuTerrainTextures: join(CLIENT_ROOT, 'src/render/gpuTerrainTextures.ts'),
      },
    },
    server: { port: 0, strictPort: false, host: true, allowedHosts: true, fs: { allow: [REPO_ROOT] } },
  });
  await server.listen();
  return { server, port: server.config.server.port ?? server.httpServer.address().port };
}

function createInbox() {
  const inbox = {};
  inbox.meta = new Promise((r) => {
    inbox.resolveMeta = r;
  });
  inbox.heights = new Promise((r) => {
    inbox.resolveHeights = r;
  });
  return inbox;
}

const BROWSERS = {
  swiftshader: () => ({
    binary: resolveChromeHeadlessShell(),
    args: ['--enable-unsafe-swiftshader', '--use-gl=angle', '--use-angle=swiftshader'],
    windows: false,
  }),
  real: () => ({
    binary: WINDOWS_CHROME_PATH,
    args: ['--use-angle=d3d11', '--ignore-gpu-blocklist', '--enable-gpu'],
    windows: true,
  }),
};

function startChrome(spec, url) {
  const port = CDP_PORT_BASE + Math.floor(Math.random() * CDP_PORT_SPREAD);
  const stamp = `${process.pid}-${port}`;
  const profileWsl = spec.windows
    ? join(WINDOWS_TEMP_WSL_PATH, WINDOWS_PROFILE_PREFIX + stamp)
    : mkdtempSync(join(tmpdir(), 'gpu-parity-indep-'));
  if (spec.windows) mkdirSync(profileWsl, { recursive: true });
  const profileArg = spec.windows
    ? `${WINDOWS_TEMP_DOS_PATH}\\${WINDOWS_PROFILE_PREFIX}${stamp}`
    : profileWsl;
  const child = spawn(
    spec.binary,
    [
      '--no-sandbox',
      '--disable-dev-shm-usage',
      '--no-first-run',
      '--no-default-browser-check',
      '--headless=new',
      ...spec.args,
      `--user-data-dir=${profileArg}`,
      `--remote-debugging-port=${port}`,
      url,
    ],
    { stdio: ['ignore', 'ignore', 'pipe'] },
  );
  const stderr = [];
  child.stderr.on('data', (c) => stderr.push(c.toString()));
  const cleanup = () => {
    try {
      child.kill('SIGKILL');
    } catch {}
    try {
      rmSync(profileWsl, { recursive: true, force: true });
    } catch {}
  };
  process.on('exit', cleanup);
  return { child, cleanup, stderr, port };
}

function compare(gpu, expected) {
  let mismatches = 0;
  let worst = null;
  for (let i = 0; i < expected.length; i++) {
    if (gpu[i] === expected[i]) continue;
    mismatches++;
    const delta = Math.abs(gpu[i] - expected[i]);
    if (worst === null || delta > worst.delta) {
      worst = { index: i, gpu: gpu[i], expected: expected[i], delta };
    }
  }
  return { samples: expected.length, mismatches, worst };
}

async function runBrowser(which, port, inbox) {
  const spec = BROWSERS[which]();
  const host = spec.windows ? wslHostIp() : '127.0.0.1';
  const chrome = startChrome(spec, `http://${host}:${port}/`);

  const timeout = new Promise((_, rej) =>
    setTimeout(() => rej(new Error(`no results within ${RUN_TIMEOUT_MS}ms`)), RUN_TIMEOUT_MS),
  );
  let meta;
  let heights;
  try {
    meta = await Promise.race([inbox.meta, timeout]);
    heights = await Promise.race([inbox.heights, timeout]);
  } catch (error) {
    chrome.cleanup();
    throw new Error(`${error.message}; chrome stderr: ${chrome.stderr.join('').slice(-400)}`);
  }
  chrome.cleanup();

  if (meta.fatal !== null) throw new Error(`page failed: ${meta.fatal}`);
  console.log(`[${which}] renderer: ${meta.renderer}`);

  const results = [];
  let offset = 0;
  for (let i = 0; i < JOBS.length; i++) {
    const job = JOBS[i];
    const reported = meta.jobs[i];
    if (reported === undefined || reported.label !== job.label) {
      throw new Error(`page returned ${meta.jobs.length} jobs for ${JOBS.length} requested`);
    }
    const count = reported.side * reported.side;
    const gpu = heights.subarray(offset, offset + count);
    offset += count;
    const cmp = compare(gpu, expectedForCase(job));
    results.push({ ...cmp, job, uncovered: reported.uncovered });
    console.log(
      `[${which}] ${job.label.padEnd(34)} samples ${String(cmp.samples).padStart(6)}` +
        `  mismatches ${String(cmp.mismatches).padStart(6)}  uncovered ${reported.uncovered}` +
        (job.mutate === null ? '' : job.slack ? '  (no-op by design)' : '  (must be non-zero)'),
    );
  }
  if (offset * FLOAT_BYTES !== heights.byteLength) {
    throw new Error(`payload was ${heights.byteLength} bytes, consumed ${offset * FLOAT_BYTES}`);
  }
  return { which, renderer: meta.renderer, results, errors: meta.errors };
}

// ---------------------------------------------------------------------------
// Reference agreement with the shipped drawnGroundHeight, reported separately.
// ---------------------------------------------------------------------------

const OFF_MAP_COORDS = [-9, -0.1, 0, SMALL_SIZE - 0.001, SMALL_SIZE, SMALL_SIZE + 0.3, SMALL_SIZE + 40];

async function checkReferenceAgainstShipped() {
  const shared = await import('../../shared/src/drawnGround.ts');
  const grid = await import('../../shared/src/grid.ts');
  const constants = await import('../../shared/src/constants.ts');
  const drift = [];
  for (const [name, value] of [
    ['TERRAIN_LOD_NEAR_N', REF_LATTICE_N],
    ['TERRAIN_LOD_FAR_N', SUBDIV_FAR],
    ['BAND_HEIGHT', REF_BAND_HEIGHT],
    ['CHUNK_SIZE', REF_CHUNK_SIZE],
    ['MIN_HEIGHT', REF_MIN_HEIGHT],
    ['MAX_HEIGHT', REF_MAX_HEIGHT],
  ]) {
    if (constants[name] !== value) drift.push(`${name}: shipped ${constants[name]}, mine ${value}`);
  }
  let samples = 0;
  let mismatches = 0;
  let worst = null;
  let offMapMismatches = 0;
  for (const kind of ['mixed', 'negative', 'ramp']) {
    const cells = mapFor(kind, SMALL_SIZE);
    const map = grid.createHeightmap(SMALL_SIZE);
    map.cells.set(cells);
    for (const subdiv of [SUBDIV_NEAR, SUBDIV_FAR]) {
      const side = SMALL_SIZE * subdiv;
      for (let py = 0; py < side; py++) {
        const y = sampleCellCoord(0, py, subdiv);
        for (let px = 0; px < side; px++) {
          const x = sampleCellCoord(0, px, subdiv);
          samples++;
          if (refSurfaceHeight(cells, SMALL_SIZE, x, y) === shared.drawnGroundHeight(map, x, y)) continue;
          mismatches++;
          if (worst === null) worst = { kind, subdiv, x, y };
        }
      }
    }
    for (const x of OFF_MAP_COORDS) {
      for (const y of OFF_MAP_COORDS) {
        samples++;
        if (refSurfaceHeight(cells, SMALL_SIZE, x, y) === shared.drawnGroundHeight(map, x, y)) continue;
        mismatches++;
        offMapMismatches++;
        if (worst === null) worst = { kind, subdiv: 'off-map', x, y };
      }
    }
  }
  return { drift, samples, mismatches, worst, offMapMismatches };
}

function referenceSelfTest() {
  const testCase = caseByName('negative 64 near');
  const good = expectedForCase(testCase);
  const bad = expectedForCase(testCase, truncDiv);
  let differing = 0;
  for (let i = 0; i < good.length; i++) if (good[i] !== bad[i]) differing++;
  return { samples: good.length, differing };
}

// ---------------------------------------------------------------------------

async function main() {
  const wanted = process.argv.slice(2).filter((a) => a in BROWSERS);
  const browsers = wanted.length > 0 ? wanted : ['swiftshader', 'real'];

  const ref = await checkReferenceAgainstShipped();
  console.log(
    `reference vs shipped drawnGroundHeight: ${ref.samples} samples, ${ref.mismatches} mismatches` +
      ` (${ref.offMapMismatches} of them off-map)`,
  );
  if (ref.drift.length > 0) console.log(`constant drift: ${ref.drift.join('; ')}`);
  if (ref.worst !== null) console.log(`first reference mismatch: ${JSON.stringify(ref.worst)}`);
  console.log('layered columns: refused (probe maps carry no columnSpans; unlayered reference only)');

  const self = referenceSelfTest();
  console.log(
    `reference self-test (trunc instead of floor): ${self.differing}/${self.samples} differ` +
      `${self.differing === 0 ? '  *** VACUOUS ***' : ''}`,
  );

  const runs = [];
  for (const which of browsers) {
    const dir = mkdtempSync(join(tmpdir(), 'gpu-parity-indep-page-'));
    let server;
    try {
      const inbox = createInbox();
      ({ server } = await startVite(dir, inbox));
      const port = server.config.server.port ?? server.httpServer.address().port;
      runs.push(await runBrowser(which, port, inbox));
    } catch (error) {
      console.log(`[${which}] SKIPPED: ${error.message}`);
    } finally {
      if (server !== undefined) await server.close().catch(() => {});
      rmSync(dir, { recursive: true, force: true });
    }
  }

  let total = 0;
  let failures = 0;
  for (const run of runs) {
    for (const r of run.results) {
      if (r.job.mutate === null) {
        total += r.samples;
        failures += r.mismatches + r.uncovered;
        if (r.mismatches > 0) {
          const side = sideOf(r.job);
          const wx = r.worst.index % side;
          const wy = (r.worst.index - wx) / side;
          console.log(
            `worst [${run.which}] ${r.job.label}: cell coord (` +
              `${sampleCellCoord(r.job.cx0, wx, r.job.subdiv)}, ` +
              `${sampleCellCoord(r.job.cy0, wy, r.job.subdiv)}) ` +
              `gpu ${r.worst.gpu} expected ${r.worst.expected} delta ${r.worst.delta}`,
          );
        }
      } else if (!r.job.slack && r.mismatches === 0) {
        console.log(`[${run.which}] *** ${r.job.label} undetected; this check is vacuous ***`);
        failures++;
      }
    }
    if (run.errors.length > 0) console.log(`[${run.which}] page errors: ${run.errors.join(' | ')}`);
  }

  if (runs.length > 1) {
    let disagree = 0;
    for (let i = 0; i < runs[0].results.length; i++) {
      if (runs[0].results[i].mismatches !== runs[1].results[i].mismatches) disagree++;
    }
    console.log(`\n${runs[0].which} and ${runs[1].which} agree on every job: ${disagree === 0 ? 'yes' : `no (${disagree} differ)`}`);
  }

  console.log(`\nbrowsers run ${runs.length}, total samples ${total}, failures ${failures}`);
  const ok = runs.length > 0 && failures === 0 && ref.mismatches === 0 && self.differing > 0;
  console.log(ok ? 'PASS' : 'FAIL');
  process.exit(ok ? 0 : 1);
}

await main();
