// rain — client half. Draws whatever the server's `rain:systems` broadcast says
// exists, and nothing else.
//
// It holds no authority: it never spawns a system, never moves one of its own
// accord, and never predicts. The wiring — subscribe, interpolate, pool one rig
// per living system, animate — is core's client kit
// (client/src/plugins/kit/discSystemsView.ts), which four plugins share; what is
// here is this plugin's rig and its budget.
//
// No HUD panel, deliberately: weather is a thing you look up at. A label saying
// RAIN would be the opposite of the feature.

import { CELL_WORLD_SIZE } from '@terrace/shared';
// PLACEHOLDER ASSET. Generated by scripts/audio-placeholders.py (high-passed
// noise, tail crossfaded into the head so it loops seamlessly), NOT authored
// sound design — it is here so the asset path is real end to end. Replacing it
// is a file swap and nothing else; an authored replacement should be OGG/Opus,
// which Vite serves with no config change (audio-host plan §2.5, §5).
import rainLoopUrl from './assets/rain-loop.wav?url';
import type {
  ClientPluginCtx,
  GroundShadeDisc,
  TerraceClientPlugin,
} from '../../../client/src/plugins/types.ts';
import { createDiscSystemsView } from '../../../client/src/plugins/kit/discSystemsView.ts';
import type { DiscRig } from '../../../client/src/plugins/kit/discRig.ts';
import { deckShadeDisc } from '../../../client/src/plugins/kit/cumulusDeck.ts';
import { MAX_ACTIVE_SYSTEMS, RAIN_PLUGIN_NAME, RAIN_SYSTEMS_MESSAGE } from '../protocol.ts';
import {
  createRainRigs,
  RAIN_DECK_DRAW_OBJECTS,
  RAIN_RIG_DRAW_OBJECTS,
  RAIN_SHADE_DARKNESS,
  type RainRigs,
} from './rig.ts';

/**
 * Module-level singleton, matching the shape of this repo's other plugins. The
 * client host constructs exactly one instance of each plugin
 * (client/src/plugins/host.ts), and `attach`/`dispose` bracket its whole
 * lifetime.
 */
/**
 * The pool, held here as well as by the view because the deck has to be
 * parented at attach and the shade lookup has to reach it. Null between attach
 * and dispose, exactly like the view's own state — the same shape the
 * thunderstorm plugin's `rigs` has.
 */
let rigs: RainRigs | null = null;
let unpublishShade: (() => void) | null = null;
let unsubscribeAmbience: (() => void) | null = null;

const view = createDiscSystemsView<DiscRig>({
  systemsMessage: RAIN_SYSTEMS_MESSAGE,
  containerName: `${RAIN_PLUGIN_NAME}:systems`,
  createPool: (ctx) => {
    rigs = createRainRigs(ctx);
    return rigs;
  },
  update: (rig, disc, elapsed) => {
    rig.update(disc, elapsed);
  },
  // The view orders the deck against the camera once per frame — see
  // DiscSystemsViewSpec.deck.
  deck: () => rigs?.deck ?? null,
  attachExtras: (ctx: ClientPluginCtx) => {
    const pool = rigs;
    if (pool === null) return;
    // Beside the masses, not inside them: ONE instanced draw carries every
    // mass's cloud, so it belongs to the plugin's layer and not to any rig.
    ctx.layer.add(pool.deck.object);
  },
  disposeExtras: () => {
    rigs = null;
  },
});

/**
 * The shade this plugin's clouds throw on the ground, rebuilt each frame.
 *
 * REUSED, NEVER REALLOCATED: core reads this during the frame it draws, every
 * frame, and a fresh array per frame would be garbage for nothing. Read from
 * the view's INTERPOLATED poses — the same numbers the decks were drawn from
 * this frame — so a shadow can never be a broadcast behind its cloud.
 */
const shade: GroundShadeDisc[] = [];

function shadeDiscs(): readonly GroundShadeDisc[] {
  shade.length = 0;
  for (const disc of view.poses().values()) {
    if (disc.intensity <= 0) continue;
    shade.push(deckShadeDisc(disc, RAIN_SHADE_DARKNESS));
  }
  return shade;
}

/**
 * HOW LOUD IT RAINS WHERE THE CAMERA IS, in 0..1 — the weight the ambience loop
 * is faded toward every frame.
 *
 * DERIVED HERE RATHER THAN READ FROM SOMETHING EXISTING, because nothing
 * existing answers it: the plugin's rigs are drawn per SYSTEM and its ground
 * shade is published per system too (`shadeDiscs` above), and neither asks
 * "what is over the camera". So this walks the same interpolated poses those
 * two use — `view.poses()`, the map the rigs were drawn from this frame — and
 * asks it that question.
 *
 * LINEAR FALLOFF FROM THE CENTRE, and the LOUDEST system wins rather than the
 * sum. A disc's intensity is how hard it is raining in it, so two fronts
 * overlapping is not twice the rain; it is the harder of the two. The falloff
 * is what stops the loop from snapping on as the camera crosses a disc's edge —
 * paired with the engine's own 1.5 s fade, a front sliding overhead arrives the
 * way the cloud does.
 *
 * CELLS, NOT WORLD UNITS: an InterpolatedDisc's x, y and radius are in cells
 * (kit/discInterpolator.ts:21-26; kit/cumulusDeck.ts:383-390 multiplies each by
 * CELL_WORLD_SIZE to draw them), while `cameraPosition` is in world units — so
 * the camera is converted into cell space here rather than the discs out of it.
 */
function rainWeightUnderCamera(ctx: ClientPluginCtx): number {
  const camera = ctx.cameraPosition();
  const cameraCellX = camera.x / CELL_WORLD_SIZE;
  const cameraCellY = camera.z / CELL_WORLD_SIZE;
  let loudest = 0;
  for (const disc of view.poses().values()) {
    if (disc.intensity <= 0 || disc.radius <= 0) continue;
    const dx = cameraCellX - disc.x;
    const dy = cameraCellY - disc.y;
    const distance = Math.sqrt(dx * dx + dy * dy);
    if (distance >= disc.radius) continue;
    const weight = disc.intensity * (1 - distance / disc.radius);
    if (weight > loudest) loudest = weight;
  }
  // Already in 0..1 by construction (intensity is, and the falloff only
  // shrinks it), but clamped anyway: the host clamps too, and a weight that
  // could leave here out of range is one that will one day be NaN.
  return Math.min(1, Math.max(0, loudest));
}

export const clientPlugin: TerraceClientPlugin = {
  name: RAIN_PLUGIN_NAME,

  /**
   * Its share of the frame's draw calls, from its own cap — see
   * TerraceClientPlugin.drawBudget. One rig per living system, and the sim never
   * has more than MAX_ACTIVE_SYSTEMS.
   */
  drawBudget: MAX_ACTIVE_SYSTEMS * RAIN_RIG_DRAW_OBJECTS + RAIN_DECK_DRAW_OBJECTS,

  /**
   * One shade disc per living mass, so the budget IS the mass cap — an
   * expression of this plugin's own cap, exactly as `drawBudget` above is.
   */
  groundShadeBudget: MAX_ACTIVE_SYSTEMS,

  attach(ctx: ClientPluginCtx): void {
    view.attach(ctx);
    // Decode the loop now rather than on the first frame under a front, so the
    // rain fades in from silence instead of starting a decode as it does.
    ctx.audio.preload(rainLoopUrl);
    unpublishShade = ctx.publishGroundShade(shadeDiscs);
    // EVERY FRAME, deliberately. `ambience` is contracted to short-circuit an
    // unchanged weight to one float comparison (ClientPluginCtx's PluginAudio),
    // and the weight moves continuously as a front drifts — so "recompute and
    // retarget each frame" is both the simplest correct thing and the intended
    // usage, with no edge events for this plugin to invent or to miss.
    unsubscribeAmbience = ctx.onFrame(() => {
      ctx.audio.ambience(rainLoopUrl, rainWeightUnderCamera(ctx));
    });
  },

  dispose(): void {
    unsubscribeAmbience?.();
    unsubscribeAmbience = null;
    unpublishShade?.();
    unpublishShade = null;
    view.dispose();
  },
};
