// thunderstorm — client half. Draws whatever the server's `thunderstorm:systems`
// broadcast says exists, and flashes where its `thunderstorm:strikes` events say
// a bolt landed.
//
// It holds no authority: it never spawns a system, never moves one of its own
// accord, never predicts, and never decides that a bolt happened. The wiring —
// subscribe, interpolate, pool one rig per living system, animate — is core's
// client kit (client/src/plugins/kit/discSystemsView.ts), which four plugins
// share; what is here is this plugin's rig, its budget, and everything about
// lightning.
//
// No HUD panel, deliberately: weather is a thing you look up at.

import { CELL_WORLD_SIZE, MAX_RELIEF_WORLD_UNITS } from '@terrace/shared';
// PLACEHOLDER ASSET. Generated by scripts/audio-placeholders.py (a low-passed,
// decaying noise burst), NOT authored sound design — it is here so the asset
// path is real end to end. Replacing it is a file swap and nothing else; an
// authored replacement should be OGG/Opus, which Vite serves with no config
// change (audio-host plan §2.5, §5).
import thunderSfxUrl from './assets/thunder.wav?url';
import type {
  ClientPluginCtx,
  GroundShadeDisc,
  TerraceClientPlugin,
  WorldPosition,
} from '../../../client/src/plugins/types.ts';
import { deckShadeDisc } from '../../../client/src/plugins/kit/cumulusDeck.ts';
import { createDiscSystemsView } from '../../../client/src/plugins/kit/discSystemsView.ts';
import {
  MAX_ACTIVE_SYSTEMS,
  STRIKE_NO_SYSTEM,
  THUNDERSTORM_PLUGIN_NAME,
  THUNDERSTORM_STRIKES_MESSAGE,
  THUNDERSTORM_SYSTEMS_MESSAGE,
  parseStrikesPayload,
} from '../protocol.ts';
import { BOLT_BOTTOM_WORLD_Y, LightningGovernor } from './lightning.ts';
import {
  createThunderstormRigs,
  DRY_BOLT_DRAW_OBJECTS,
  LIGHT_BANK_DRAW_OBJECTS,
  THUNDERSTORM_DECK_DRAW_OBJECTS,
  THUNDERSTORM_RIG_DRAW_OBJECTS,
  THUNDERSTORM_SHADE_DARKNESS,
  type ThunderstormRig,
  type ThunderstormRigs,
} from './rig.ts';

/**
 * THE ONE THING THAT MAY START A FLASH ANYWHERE ON THIS CLIENT. Shared by every
 * storm rig, which is what makes the photosensitivity floor hold across
 * concurrent storms rather than only within one — see MIN_FLASH_INTERVAL_SECONDS.
 */
const governor = new LightningGovernor();

/**
 * The pool, held here as well as by the view because the strike path needs the
 * dry bolt and the attach path needs the light bank. Null between attach and
 * dispose, exactly like the view's own state.
 */
let rigs: ThunderstormRigs | null = null;
let unsubscribeStrikes: (() => void) | null = null;
let unpublishShade: (() => void) | null = null;

const view = createDiscSystemsView<ThunderstormRig>({
  systemsMessage: THUNDERSTORM_SYSTEMS_MESSAGE,
  containerName: `${THUNDERSTORM_PLUGIN_NAME}:systems`,
  createPool: (ctx) => {
    rigs = createThunderstormRigs(ctx);
    return rigs;
  },
  update: (rig, disc, elapsed, dt, reduced) => {
    rig.update(disc, elapsed, dt, reduced);
  },
  // The view orders the deck against the camera once per frame — see
  // DiscSystemsViewSpec.deck.
  deck: () => rigs?.deck ?? null,
  attachExtras: (ctx: ClientPluginCtx) => {
    const pool = rigs;
    if (pool === null) return;
    // Beside the systems, not inside them: a dry bolt is positioned in world
    // space and must not ride any system's transform.
    ctx.layer.add(pool.dryBolt.root);
    // The storm flash lights, all of them, dark, for the plugin's whole life —
    // so the scene's light count is fixed from here on (rig.ts, lightBank).
    ctx.layer.add(pool.lightBank);
    // Beside the systems as well: ONE instanced draw carries every storm's
    // cloud, so it belongs to the layer and not to any rig.
    ctx.layer.add(pool.deck.object);
  },
  frameExtras: (dt, reduced) => {
    // Advanced once per frame, BEFORE any rig asks it for permission, so every
    // storm this frame is measured against the same clock.
    governor.advance(dt);
    // The dry bolt is advanced every frame whatever the weather: it belongs to
    // no system, so nothing else would ever decay its flash.
    rigs?.dryBolt.update(dt, reduced);
  },
  disposeExtras: () => {
    governor.reset();
    rigs = null;
  },
});

/**
 * HOW BIG A WORLD UNIT IS, in metres.
 *
 * Nothing in the codebase declares a metric scale, and thunder needs one: the
 * speed of sound is a real number in real units and it has to be converted into
 * this world's before a delay can be computed at all. So the scale is anchored
 * on THE one constant that states a real-world dimension of this world —
 * `MAX_RELIEF_WORLD_UNITS` (client/src/config.ts:110, re-exported from
 * @terrace/shared where a plugin can reach it): the full sea-to-summit relief,
 * 16 world units, described there as "THE relief fact ... how mountainous the
 * world looks".
 *
 * `MAX_RELIEF_METRES` is the one judgement call, and it is 160 — terraced hills
 * with a highest point about half a Ben Nevis, which is what the terrain
 * actually looks like and not what "mountain" might suggest. CROSS-CHECKED
 * against a drawn object rather than asserted: flora's conifer is
 * `TRUNK_HEIGHT + CONIFER_CROWN_HEIGHT` = 0.45 + 1.05 = 1.5 world units
 * (plugins/flora/client/models.ts:75, :96), and a conifer is about 15 m — which
 * gives the same 10 m per world unit from a completely independent direction.
 * A third check: the shipped world is `DEFAULT_WORLD_SPAN` = 512 world units
 * across (@terrace/shared), i.e. 5.1 km — an island, which is what it is.
 *
 * If the owner later declares a real scale somewhere central, this derives from
 * that instead and nothing else here changes.
 */
const MAX_RELIEF_METRES = 160;
const WORLD_UNIT_METRES = MAX_RELIEF_METRES / MAX_RELIEF_WORLD_UNITS;

/** Dry air at 20 °C, the textbook figure. */
const SPEED_OF_SOUND_METRES_PER_SECOND = 343;

/**
 * How fast sound crosses this world, in world units per second.
 *
 * DERIVED, never written: 343 / 10 = 34.3 world units a second. A strike at the
 * camera's default framing distance (CAMERA_INITIAL_DISTANCE = 80 world units)
 * is therefore heard about 2.3 s after it is seen, which is the cue this whole
 * mechanism exists for.
 */
const SPEED_OF_SOUND_WORLD_UNITS_PER_SECOND =
  SPEED_OF_SOUND_METRES_PER_SECOND / WORLD_UNIT_METRES;

/**
 * The longest a clap may be held back, in seconds.
 *
 * FOUR, and it is a PERCEPTUAL limit rather than a physical one. Physically the
 * shipped world's diagonal is 512·√2 ≈ 724 world units, which at the speed
 * above is 21 s — real, and useless: a rumble twenty seconds after a flash is
 * not heard as that flash's thunder, it is heard as an unexplained noise, and
 * by then the storm may have thrown three more bolts. Four seconds is about
 * where a flash and a clap stop binding into one event for a viewer who is
 * watching for it; past that the delay has done all the work it can.
 *
 * RESIDUAL, NAMED: beyond ~137 world units the delay is capped and therefore no
 * longer proportional to distance, so two strikes at 200 and 600 units sound
 * equally far in TIME. They are still separated by loudness — the positional
 * falloff is uncapped — so the cue degrades rather than disappearing.
 */
const MAX_THUNDER_DELAY_SECONDS = 4;

/**
 * How long after the flash this strike's clap should arrive, in seconds.
 *
 * MEASURED FROM THE CAMERA, which is where the listener is: core puts the
 * AudioListener on `viewport.camera` (client/src/audio/audioEngine.ts), so the
 * distance sound has to cover is camera → strike and nothing else. Straight-line
 * distance in three dimensions, because that is the path it takes.
 */
function thunderDelaySeconds(ctx: ClientPluginCtx, at: WorldPosition): number {
  const camera = ctx.cameraPosition();
  const dx = at.x - camera.x;
  const dy = at.y - camera.y;
  const dz = at.z - camera.z;
  const distance = Math.sqrt(dx * dx + dy * dy + dz * dz);
  return Math.min(MAX_THUNDER_DELAY_SECONDS, distance / SPEED_OF_SOUND_WORLD_UNITS_PER_SECOND);
}

/**
 * The clap for one strike, at the strike's own world position.
 *
 * THE SAME POINT THE FLASH LIGHT IS PUT AT — `(worldX, BOLT_BOTTOM_WORLD_Y,
 * worldZ)`, rig.ts:476 for a loose bolt and rig.ts:356-359 for a bolt inside a
 * system (whose rig root sits at the system centre, so root + offset is this
 * same world point). Sound and light therefore come from one place by
 * construction rather than by two agreeing calculations.
 *
 * NO DELAY FOR DISTANCE in phase 1 (plan §7, owner default): a real clap
 * arrives seconds after its flash, and whether that is atmosphere or annoyance
 * is a sound-design decision the owner has not made yet.
 */
function playThunder(ctx: ClientPluginCtx, cellX: number, cellY: number): void {
  const at: WorldPosition = {
    x: cellX * CELL_WORLD_SIZE,
    y: BOLT_BOTTOM_WORLD_Y,
    z: cellY * CELL_WORLD_SIZE,
  };
  // No `gain` and no `playbackRate`: thunder is the loudest thing in this world
  // by a distance — that is what it is for — and the positional falloff already
  // takes a far strike down on its own. Both options are sound-design dials and
  // there is no sound design yet, only a placeholder asset. `delaySeconds` is
  // not a dial: it is a fact about where the strike was.
  ctx.audio.playSfx(thunderSfxUrl, { at, delaySeconds: thunderDelaySeconds(ctx, at) });
}

/**
 * A bolt landed. Finds the rig drawing the system that threw it and tells it
 * where, in that rig's OWN space — the rig's root sits at the system's centre, so
 * a strike is an offset from there rather than a world position.
 *
 * THE SYSTEM'S SAMPLED POSITION, not its last broadcast one: the rig is drawn at
 * the interpolated position this frame, so measuring the offset against anything
 * else would put the bolt a fraction of a cell away from where the storm is.
 *
 * A bolt for a system this client does not know about — one whose broadcast has
 * not landed yet, or one already retired — is drawn by the loose bolt at the
 * strike's own world position, exactly like a dry strike. Dropping it would show
 * a player a forest catching under a clear sky with no bolt at all.
 */
function applyStrike(systemId: number, cellX: number, cellY: number): void {
  const rig = systemId === STRIKE_NO_SYSTEM ? undefined : view.rigFor(systemId);
  const disc = rig === undefined ? undefined : view.poseFor(systemId);

  if (rig === undefined || disc === undefined) {
    rigs?.dryBolt.strike(cellX * CELL_WORLD_SIZE, cellY * CELL_WORLD_SIZE, governor);
    return;
  }

  rig.strike((cellX - disc.x) * CELL_WORLD_SIZE, (cellY - disc.y) * CELL_WORLD_SIZE, governor);
}

/** The shade this plugin's clouds throw — see rain's copy for the reasoning. */
const shade: GroundShadeDisc[] = [];

function shadeDiscs(): readonly GroundShadeDisc[] {
  shade.length = 0;
  for (const disc of view.poses().values()) {
    if (disc.intensity <= 0) continue;
    shade.push(deckShadeDisc(disc, THUNDERSTORM_SHADE_DARKNESS));
  }
  return shade;
}

export const clientPlugin: TerraceClientPlugin = {
  name: THUNDERSTORM_PLUGIN_NAME,

  /**
   * Its share of the frame's draw calls, from its own caps — see
   * TerraceClientPlugin.drawBudget and the constants in ./rig.ts.
   */
  drawBudget:
    MAX_ACTIVE_SYSTEMS * THUNDERSTORM_RIG_DRAW_OBJECTS +
    DRY_BOLT_DRAW_OBJECTS +
    LIGHT_BANK_DRAW_OBJECTS +
    THUNDERSTORM_DECK_DRAW_OBJECTS,

  /** One shade disc per living storm, so the budget IS the storm cap. */
  groundShadeBudget: MAX_ACTIVE_SYSTEMS,

  attach(ctx: ClientPluginCtx): void {
    view.attach(ctx);
    // DECODE THE CLAP NOW, not at the first bolt. A one-shot whose buffer is
    // not ready is dropped rather than played late (ClientPluginCtx's
    // PluginAudio), and without this the FIRST thunderclap of every session —
    // the one a player actually notices — was silent.
    ctx.audio.preload(thunderSfxUrl);
    unpublishShade = ctx.publishGroundShade(shadeDiscs);

    unsubscribeStrikes = ctx.onMessage(THUNDERSTORM_STRIKES_MESSAGE, (payload) => {
      const strikes = parseStrikesPayload(payload);
      if (strikes === null) return;
      // THE CLAP IS NOT MOTION, so it happens BEFORE the reduced-motion guard
      // below and is heard either way. That is this handler's own stated
      // reasoning applied to a second sense: "a player who asked for less
      // motion asked for less motion, not for a different world" — a world
      // whose storms had gone silent would be a different world.
      for (const strike of strikes) playThunder(ctx, strike.x, strike.y);
      // REDUCED MOTION DROPS THE BOLT HERE, at the door, rather than inside the
      // rig: it is the one place that knows the strike is a visual event at all.
      // The server's fire burns either way — a player who asked for less motion
      // asked for less motion, not for a different world.
      if (view.isReduced()) return;
      for (const strike of strikes) applyStrike(strike.systemId, strike.x, strike.y);
    });
  },

  dispose(): void {
    unsubscribeStrikes?.();
    unsubscribeStrikes = null;
    unpublishShade?.();
    unpublishShade = null;
    view.dispose();
  },
};
