// thunderstorm — client half. Draws whatever the server's `thunderstorm:systems`
// broadcast says exists, and flashes where its `thunderstorm:strikes` events say
// a bolt landed.
//
// It holds no authority: it never spawns a system, never moves one of its own
// accord, never predicts, and never decides that a bolt happened. The wiring —
// subscribe, interpolate, pool one rig per living system, animate — is core's
// client kit (client/src/plugins/kit/discSystemsView.ts), which four plugins
// share; what is here is this plugin's rig, its budget, and everything about
// lightning.
//
// No HUD panel, deliberately: weather is a thing you look up at.

import { CELL_WORLD_SIZE, MAX_RELIEF_WORLD_UNITS } from '@terrace/shared';
// PLACEHOLDER, generated by scripts/audio-placeholders.py — here so the asset
// path is real end to end. Replacing it is a file swap; prefer OGG/Opus.
import thunderSfxUrl from './assets/thunder.wav?url';
import type {
  ClientPluginCtx,
  GroundShadeDisc,
  TerraceClientPlugin,
  WorldPosition,
} from '../../../client/src/plugins/types.ts';
import { deckShadeDisc } from '../../../client/src/plugins/kit/cumulusDeck.ts';
import { createDiscSystemsView } from '../../../client/src/plugins/kit/discSystemsView.ts';
import {
  MAX_ACTIVE_SYSTEMS,
  STRIKE_NO_SYSTEM,
  THUNDERSTORM_PLUGIN_NAME,
  THUNDERSTORM_STRIKES_MESSAGE,
  THUNDERSTORM_SYSTEMS_MESSAGE,
  parseStrikesPayload,
} from '../protocol.ts';
import { BOLT_BOTTOM_WORLD_Y, LightningGovernor } from './lightning.ts';
import {
  createThunderstormRigs,
  DRY_BOLT_DRAW_OBJECTS,
  LIGHT_BANK_DRAW_OBJECTS,
  THUNDERSTORM_DECK_DRAW_OBJECTS,
  THUNDERSTORM_RIG_DRAW_OBJECTS,
  THUNDERSTORM_SHADE_DARKNESS,
  type ThunderstormRig,
  type ThunderstormRigs,
} from './rig.ts';

/**
 * THE ONE THING THAT MAY START A FLASH ANYWHERE ON THIS CLIENT. Shared by every
 * storm rig, which is what makes the photosensitivity floor hold across
 * concurrent storms rather than only within one — see MIN_FLASH_INTERVAL_SECONDS.
 */
const governor = new LightningGovernor();

/**
 * The pool, held here as well as by the view because the strike path needs the
 * dry bolt and the attach path needs the light bank. Null between attach and
 * dispose, exactly like the view's own state.
 */
let rigs: ThunderstormRigs | null = null;
let unsubscribeStrikes: (() => void) | null = null;
let unpublishShade: (() => void) | null = null;
let unpublishWeight: (() => void) | null = null;

/** Gauge key for how hard the storm falls where the camera is, 0..1. */
const WEIGHT_GAUGE_KEY = 'weightUnderCamera';

const view = createDiscSystemsView<ThunderstormRig>({
  systemsMessage: THUNDERSTORM_SYSTEMS_MESSAGE,
  containerName: `${THUNDERSTORM_PLUGIN_NAME}:systems`,
  createPool: (ctx) => {
    rigs = createThunderstormRigs(ctx);
    return rigs;
  },
  update: (rig, disc, elapsed, dt, reduced) => {
    rig.update(disc, elapsed, dt, reduced);
  },
  // The view orders the deck against the camera once per frame — see
  // DiscSystemsViewSpec.deck.
  deck: () => rigs?.deck ?? null,
  attachExtras: (ctx: ClientPluginCtx) => {
    const pool = rigs;
    if (pool === null) return;
    // Beside the systems, not inside them: a dry bolt is positioned in world
    // space and must not ride any system's transform.
    ctx.layer.add(pool.dryBolt.root);
    // The storm flash lights, all of them, dark, for the plugin's whole life —
    // so the scene's light count is fixed from here on (rig.ts, lightBank).
    ctx.layer.add(pool.lightBank);
    // Beside the systems as well: ONE instanced draw carries every storm's
    // cloud, so it belongs to the layer and not to any rig.
    ctx.layer.add(pool.deck.object);
  },
  frameExtras: (dt, reduced) => {
    // Advanced once per frame, BEFORE any rig asks it for permission, so every
    // storm this frame is measured against the same clock.
    governor.advance(dt);
    // The dry bolt is advanced every frame whatever the weather: it belongs to
    // no system, so nothing else would ever decay its flash.
    rigs?.dryBolt.update(dt, reduced);
  },
  disposeExtras: () => {
    governor.reset();
    rigs = null;
  },
});

/**
 * AN ASSUMPTION, because nothing in the codebase declares a metric scale and
 * the speed of sound needs one. Anchored on MAX_RELIEF_WORLD_UNITS
 * (client/src/config.ts:110), the one constant stating a real dimension.
 *
 * 160 m of sea-to-summit relief → 10 m per world unit. Cross-checked, not
 * asserted: flora's conifer is 1.5 world units (models.ts:75, :96) and a
 * conifer is ~15 m; and a 512-unit world is then 5.1 km, an island.
 */
const MAX_RELIEF_METRES = 160;
const WORLD_UNIT_METRES = MAX_RELIEF_METRES / MAX_RELIEF_WORLD_UNITS;

/** Dry air at 20 °C, the textbook figure. */
const SPEED_OF_SOUND_METRES_PER_SECOND = 343;

/** Derived: 343 / 10 = 34.3. A strike 80 units out is heard ~2.3 s later. */
const SPEED_OF_SOUND_WORLD_UNITS_PER_SECOND =
  SPEED_OF_SOUND_METRES_PER_SECOND / WORLD_UNIT_METRES;

/**
 * A PERCEPTUAL cap, not a physical one: the world diagonal is honestly 21 s,
 * and a rumble that late is not heard as that flash's thunder.
 *
 * RESIDUAL: past ~137 units the delay stops being proportional, so distant
 * strikes sound equally far in time. Loudness still separates them.
 */
const MAX_THUNDER_DELAY_SECONDS = 4;

/** From the CAMERA, which is where core puts the listener (audioGraph.ts). */
function thunderDelaySeconds(ctx: ClientPluginCtx, at: WorldPosition): number {
  const camera = ctx.cameraPosition();
  const dx = at.x - camera.x;
  const dy = at.y - camera.y;
  const dz = at.z - camera.z;
  const distance = Math.sqrt(dx * dx + dy * dy + dz * dz);
  return Math.min(MAX_THUNDER_DELAY_SECONDS, distance / SPEED_OF_SOUND_WORLD_UNITS_PER_SECOND);
}

/**
 * THE SAME POINT THE FLASH LIGHT IS PUT AT (rig.ts:476, and :356-359 for a bolt
 * inside a system), so sound and light share one place by construction.
 */
function playThunder(ctx: ClientPluginCtx, cellX: number, cellY: number): void {
  const at: WorldPosition = {
    x: cellX * CELL_WORLD_SIZE,
    y: BOLT_BOTTOM_WORLD_Y,
    z: cellY * CELL_WORLD_SIZE,
  };
  // No gain or playbackRate: sound-design dials, and there is no sound design
  // yet. `delaySeconds` is not a dial — it is a fact about where the strike was.
  ctx.audio.playSfx(thunderSfxUrl, { at, delaySeconds: thunderDelaySeconds(ctx, at) });
}

/**
 * A bolt landed. Finds the rig drawing the system that threw it and tells it
 * where, in that rig's OWN space — the rig's root sits at the system's centre, so
 * a strike is an offset from there rather than a world position.
 *
 * THE SYSTEM'S SAMPLED POSITION, not its last broadcast one: the rig is drawn at
 * the interpolated position this frame, so measuring the offset against anything
 * else would put the bolt a fraction of a cell away from where the storm is.
 *
 * A bolt for a system this client does not know about — one whose broadcast has
 * not landed yet, or one already retired — is drawn by the loose bolt at the
 * strike's own world position, exactly like a dry strike. Dropping it would show
 * a player a forest catching under a clear sky with no bolt at all.
 */
function applyStrike(systemId: number, cellX: number, cellY: number): void {
  const rig = systemId === STRIKE_NO_SYSTEM ? undefined : view.rigFor(systemId);
  const disc = rig === undefined ? undefined : view.poseFor(systemId);

  if (rig === undefined || disc === undefined) {
    rigs?.dryBolt.strike(cellX * CELL_WORLD_SIZE, cellY * CELL_WORLD_SIZE, governor);
    return;
  }

  rig.strike((cellX - disc.x) * CELL_WORLD_SIZE, (cellY - disc.y) * CELL_WORLD_SIZE, governor);
}

/** The shade this plugin's clouds throw — see rain's copy for the reasoning. */
const shade: GroundShadeDisc[] = [];

/**
 * How hard it storms where the camera is, 0..1. A DOCUMENTED COPY of rain's
 * rainWeightUnderCamera — plugins never import each other
 * (docs/decisions/plugin-host.md, 2026-09-01). Loudest system wins.
 */
function stormWeightUnderCamera(ctx: ClientPluginCtx): number {
  const camera = ctx.cameraPosition();
  const cameraCellX = camera.x / CELL_WORLD_SIZE;
  const cameraCellY = camera.z / CELL_WORLD_SIZE;
  let loudest = 0;
  for (const disc of view.poses().values()) {
    if (disc.intensity <= 0 || disc.radius <= 0) continue;
    const dx = cameraCellX - disc.x;
    const dy = cameraCellY - disc.y;
    const distance = Math.sqrt(dx * dx + dy * dy);
    if (distance >= disc.radius) continue;
    const weight = disc.intensity * (1 - distance / disc.radius);
    if (weight > loudest) loudest = weight;
  }
  // In range by construction; clamped anyway, belt and suspenders.
  return Math.min(1, Math.max(0, loudest));
}

function shadeDiscs(): readonly GroundShadeDisc[] {
  shade.length = 0;
  for (const disc of view.poses().values()) {
    if (disc.intensity <= 0) continue;
    shade.push(deckShadeDisc(disc, THUNDERSTORM_SHADE_DARKNESS));
  }
  return shade;
}

export const clientPlugin: TerraceClientPlugin = {
  name: THUNDERSTORM_PLUGIN_NAME,

  /**
   * Its share of the frame's draw calls, from its own caps — see
   * TerraceClientPlugin.drawBudget and the constants in ./rig.ts.
   */
  drawBudget:
    MAX_ACTIVE_SYSTEMS * THUNDERSTORM_RIG_DRAW_OBJECTS +
    DRY_BOLT_DRAW_OBJECTS +
    LIGHT_BANK_DRAW_OBJECTS +
    THUNDERSTORM_DECK_DRAW_OBJECTS,

  /** One shade disc per living storm, so the budget IS the storm cap. */
  groundShadeBudget: MAX_ACTIVE_SYSTEMS,

  attach(ctx: ClientPluginCtx): void {
    view.attach(ctx);
    // DECODE NOW, not at the first bolt: a one-shot with no buffer is dropped,
    // so without this the first thunderclap of every session was silent.
    ctx.audio.preload(thunderSfxUrl);
    unpublishShade = ctx.publishGroundShade(shadeDiscs);
    unpublishWeight = ctx.publishGauge(WEIGHT_GAUGE_KEY, () => stormWeightUnderCamera(ctx));

    unsubscribeStrikes = ctx.onMessage(THUNDERSTORM_STRIKES_MESSAGE, (payload) => {
      const strikes = parseStrikesPayload(payload);
      if (strikes === null) return;
      // THE CLAP IS NOT MOTION, so it precedes the reduced-motion guard below
      // — this handler's own reasoning, applied to a second sense.
      for (const strike of strikes) playThunder(ctx, strike.x, strike.y);
      // REDUCED MOTION DROPS THE BOLT HERE, at the door, rather than inside the
      // rig: it is the one place that knows the strike is a visual event at all.
      // The server's fire burns either way — a player who asked for less motion
      // asked for less motion, not for a different world.
      if (view.isReduced()) return;
      for (const strike of strikes) applyStrike(strike.systemId, strike.x, strike.y);
    });
  },

  dispose(): void {
    unsubscribeStrikes?.();
    unsubscribeStrikes = null;
    unpublishShade?.();
    unpublishShade = null;
    unpublishWeight?.();
    unpublishWeight = null;
    view.dispose();
  },
};
