export const CTHULHU_TORSO_HEIGHT = 6;
export const CTHULHU_TORSO_LENGTH = 3;
export const CTHULHU_TORSO_WIDTH = 4.2;

export const CTHULHU_SHOULDER_HEIGHT = 5.6;
export const CTHULHU_SHOULDER_OFFSET = 2;
export const CTHULHU_SHOULDER_LENGTH = 2.8;
export const CTHULHU_SHOULDER_THICKNESS = 2.2;
export const CTHULHU_SHOULDER_WIDTH = 2.8;

export const CTHULHU_NECK_CENTER_HEIGHT = 6.6;
export const CTHULHU_NECK_LENGTH = 2.6;
export const CTHULHU_NECK_HEIGHT = 2.8;
export const CTHULHU_NECK_WIDTH = 2.9;
export const CTHULHU_NECK_FORWARD = 0.25;

export const CTHULHU_HEAD_CENTER_HEIGHT = 8.4;
export const CTHULHU_HEAD_LENGTH = 4.6;
export const CTHULHU_HEAD_HEIGHT = 3.8;
export const CTHULHU_HEAD_WIDTH = 3.6;
export const CTHULHU_HEAD_FORWARD = 0.5;

export const CTHULHU_HEAD_MUZZLE_TAPER = 0.3;
export const CTHULHU_HEAD_BROW_SLOPE = 0.22;

export const CTHULHU_HEAD_TOP = CTHULHU_HEAD_CENTER_HEIGHT + CTHULHU_HEAD_HEIGHT / 2;
export const CTHULHU_HEAD_BOTTOM = CTHULHU_HEAD_CENTER_HEIGHT - CTHULHU_HEAD_HEIGHT / 2;

export const CTHULHU_FACE_TENTACLE_COUNT = 7;
export const CTHULHU_TENTACLE_ROOT_FORWARD = 1.5;
export const CTHULHU_TENTACLE_ROOT_HEIGHT = 7.5;
export const CTHULHU_TENTACLE_FAN_RADIANS = 1.5;
export const CTHULHU_TENTACLE_PITCH_RADIANS = 0.45;
export const CTHULHU_TENTACLE_BEND_RADIANS = 0.55;

export const CTHULHU_TENTACLE_UPPER_LENGTH = 1.5;
export const CTHULHU_TENTACLE_UPPER_RADIUS = 0.34;
export const CTHULHU_TENTACLE_LOWER_LENGTH = 1.3;
export const CTHULHU_TENTACLE_LOWER_RADIUS = 0.2;
export const CTHULHU_TENTACLE_TIP_RADIUS = 0.045;

export const CTHULHU_TENTACLE_UPPER_CURL_RADIANS = 0.34;
export const CTHULHU_TENTACLE_LOWER_CURL_RADIANS = 1.05;
export const CTHULHU_TENTACLE_MIN_CURL_RADIANS = 0.05;

export const CTHULHU_TENTACLE_CURL_VARIATION = 0.35;
export const CTHULHU_TENTACLE_LENGTH_VARIATION = 0.18;
export const CTHULHU_TENTACLE_DRIFT = 0.22;
export const CTHULHU_TENTACLE_SWELL = 0.12;
export const CTHULHU_TENTACLE_TAPER_EXPONENT = 0.75;

export const CTHULHU_WING_CHORD = 2.9;
export const CTHULHU_WING_SPAN = 4.4;
export const CTHULHU_WING_ARM_RADIUS = 0.28;
export const CTHULHU_WING_OFFSET = 2;
export const CTHULHU_WING_HEIGHT = 7;
export const CTHULHU_WING_BACKSET = 0.6;
export const CTHULHU_WING_LEAN_RADIANS = 0.35;
export const CTHULHU_WING_RAKE_RADIANS = 0.4;
export const CTHULHU_WING_FOLD_SCALE = 0.55;
export const CTHULHU_WING_FOLD_RISE = 2.6;
export const CTHULHU_WING_FINGER_LENGTH = CTHULHU_WING_SPAN * CTHULHU_WING_FOLD_SCALE;
export const CTHULHU_WING_FINGER_RISE = CTHULHU_WING_FINGER_LENGTH / 2;

export const CTHULHU_WING_FINGER_COUNT = 4;
export const CTHULHU_WING_FINGER_FAN_START_RADIANS = Math.acos(
  CTHULHU_WING_FINGER_RISE / CTHULHU_WING_FINGER_LENGTH,
);
export const CTHULHU_WING_FINGER_FAN_STEP_RADIANS = 0.4;
export const CTHULHU_WING_FINGER_LENGTH_STEP = 0.86;
export const CTHULHU_WING_FINGER_SPREAD = 0.1;
export const CTHULHU_WING_FINGER_BOW = 0.1;
export const CTHULHU_WING_FINGER_RADIUS = 0.16;
export const CTHULHU_WING_FINGER_TIP_RADIUS = 0.04;
export const CTHULHU_WING_WRIST_RADIUS = 0.17;
export const CTHULHU_WING_KNUCKLE_SWELL = 1.5;

export const CTHULHU_WING_ELBOW_RISE_FRACTION = 0.55;
export const CTHULHU_WING_ELBOW_BACK_FRACTION = 0.3;
export const CTHULHU_WING_ELBOW_BULGE = 0.35;

export const CTHULHU_WING_TRAILING_DROP = 3.4;
export const CTHULHU_WING_TRAILING_TUCK = 0.7;

export const CTHULHU_WING_MEMBRANE_SCALLOP = 0.16;
export const CTHULHU_WING_MEMBRANE_SAG = 0.5;
export const CTHULHU_WING_SAG_DOWN = 1;
export const CTHULHU_WING_SAG_INBOARD = 0.55;

export const CTHULHU_EYE_RADIUS = 0.22;
export const CTHULHU_EYE_FORWARD = 1.9;
export const CTHULHU_EYE_HEIGHT = 9;
export const CTHULHU_EYE_OFFSET = 0.85;
export const CTHULHU_EYE_BULGE = 0.55;
export const CTHULHU_EYE_HALO_SCALE = 2.8;
export const CTHULHU_EYE_HALO_OPACITY = 0.2;

export const CTHULHU_WING_TIP_HEIGHT =
  CTHULHU_WING_HEIGHT +
  CTHULHU_WING_FOLD_RISE +
  CTHULHU_WING_FINGER_RISE +
  CTHULHU_WING_FINGER_TIP_RADIUS;
export const CTHULHU_TOTAL_HEIGHT = Math.max(CTHULHU_HEAD_TOP, CTHULHU_WING_TIP_HEIGHT);

export const CTHULHU_WIDTH_CELLS = 7;

export const CTHULHU_WATERLINE_BITE = 0.1;

export const CTHULHU_LURK_DEPTH = CTHULHU_HEAD_BOTTOM + CTHULHU_WATERLINE_BITE;

export const CTHULHU_BODY_COLOR = 0x1b2a20;
export const CTHULHU_HEAD_COLOR = 0x24382a;
export const CTHULHU_WING_COLOR = 0x111a14;
export const CTHULHU_WING_RIB_COLOR = 0x1d2a20;
export const CTHULHU_TENTACLE_COLOR = 0x203024;
export const CTHULHU_EYE_COLOR = 0x0d1410;
export const CTHULHU_EYE_EMISSIVE = 0x86c34a;

export const CTHULHU_HEAD_WRINKLE_DEPTH = 0.04;
export const CTHULHU_BODY_WRINKLE_DEPTH = 0.08;
export const CTHULHU_WRINKLE_FREQUENCY = 1.7;
export const CTHULHU_SHADE_VARIATION = 0.16;
export const CTHULHU_SHADE_FREQUENCY = 0.55;

export const CTHULHU_TENTACLE_SWAY_HZ = 0.22;
export const CTHULHU_TENTACLE_SWAY_RADIANS = 0.26;
export const CTHULHU_TENTACLE_PHASE_STEP = 0.9;

export const CTHULHU_BREATH_HZ = 0.11;
export const CTHULHU_BREATH_RISE = 0.18;
export const CTHULHU_BREATH_ROLL_RADIANS = 0.02;
