// The gem's material: THE ICON'S LIGHTING, in the world (owner, 2026-09-04:
// "I want the 3D model renders for the relics to look more like the icon
// style we use in the HUDs"). The panel icons (RelicIcons.tsx, generated by
// .claude/orchestration/refs/hud-icons/relics.py) are gradient-lit faceted
// solids: one fixed light from the viewer's upper left, every face binned to
// one of a few light levels, and each level a short vertical gradient between
// the paint's light and dark ends. This shader draws the world mesh the same
// way — same light, same levels, same paint ends (relicShapes.ts's vertex
// colours) — so a relic on the ground is the icon in its panel, turned.
//
// It is UNLIT by the scene: the light is fixed to the camera, as it is fixed
// to the panel, so the relic reads the same from every orbit angle and at
// every hour of the day. That is the icon's contract, not the terrain's — a
// relic is a marker, and it kept its own glow before this (an emissive gem)
// for the same reason.
//
// relics.py reads ICON_LIGHT_UVH and ICON_LIGHT_LEVELS from this file, so
// the panel and the world share one lighting model.

import { ShaderMaterial, Vector3 } from 'three';

/**
 * The icon's light direction in its tile frame: u runs to the lower right of
 * the tile, v to the lower left, h up. From the upper left, as the tile top
 * lights itself.
 */
export const ICON_LIGHT_UVH = [-0.35, 0.55, 0.75] as const;

/** How many light levels a face is binned into. */
export const ICON_LIGHT_LEVELS = 4;

/**
 * The icon's viewer, in the same frame: the tile is seen from (1, 1, 1),
 * screen-right is u minus v, screen-up is h — the world's x, z and y, seen
 * from the isometric corner. The light is carried into camera space through
 * that basis, so "upper left of the viewer" means the same thing in the world
 * as on the panel.
 */
function iconLightInViewSpace(): Vector3 {
  const [u, v, h] = ICON_LIGHT_UVH;
  // Tile frame to world: u → x, h → y, v → z (relicShapes.ts's place()).
  const light = new Vector3(u, h, v);
  const view = new Vector3(1, 1, 1).normalize();
  const right = new Vector3(1, 0, -1).normalize();
  const up = new Vector3().crossVectors(right, view);
  return new Vector3(light.dot(right), light.dot(up), light.dot(view)).normalize();
}

const LIGHT_DIR_VIEW = iconLightInViewSpace();

const VERTEX_SHADER = /* glsl */ `
attribute vec3 paintLight;
attribute vec3 paintDark;
uniform float uRadius;
varying vec3 vViewPosition;
varying vec3 vPaintLight;
varying vec3 vPaintDark;
varying float vDownward;

void main() {
  vec4 viewPosition = modelViewMatrix * vec4(position, 1.0);
  vec4 viewCentre = modelViewMatrix * vec4(0.0, 0.0, 0.0, 1.0);
  vViewPosition = viewPosition.xyz;
  // 0 at the top of the gem on screen, 1 at its bottom: the icon's vertical
  // gradient, spanning the whole gem rather than each face.
  vDownward = clamp((viewCentre.y + uRadius - viewPosition.y) / (2.0 * uRadius), 0.0, 1.0);
  vPaintLight = paintLight;
  vPaintDark = paintDark;
  gl_Position = projectionMatrix * viewPosition;
}
`;

const FRAGMENT_SHADER = /* glsl */ `
uniform vec3 uLightDir;
uniform float uLevels;
varying vec3 vViewPosition;
varying vec3 vPaintLight;
varying vec3 vPaintDark;
varying float vDownward;

void main() {
  // The face's own normal, from screen-space derivatives: flat shading with
  // no normal attribute, as three's own flatShading does it.
  vec3 normal = normalize(cross(dFdx(vViewPosition), dFdy(vViewPosition)));
  float lit = (dot(normal, uLightDir) + 1.0) * 0.5;
  float level = min(uLevels - 1.0, floor((1.0 - lit) * uLevels));
  float t = (level + vDownward) / uLevels;
  // The paints are sRGB and the icon blends them as sRGB; blend the same,
  // then hand three linear light to write out.
  vec4 srgb = vec4(mix(vPaintLight, vPaintDark, t), 1.0);
  gl_FragColor = sRGBTransferEOTF(srgb);
  #include <colorspace_fragment>
}
`;

/**
 * One material per gem. `radius` is the gem geometry's bounding-sphere
 * radius, the span of the on-screen gradient. The material is not tone
 * mapped: the paints are the colours the icon shows, and the scene's
 * exposure would lift them off it.
 */
export function createGemMaterial(radius: number): ShaderMaterial {
  return new ShaderMaterial({
    vertexShader: VERTEX_SHADER,
    fragmentShader: FRAGMENT_SHADER,
    uniforms: {
      uLightDir: { value: LIGHT_DIR_VIEW.clone() },
      uLevels: { value: ICON_LIGHT_LEVELS },
      uRadius: { value: radius },
    },
    toneMapped: false,
  });
}
