// THE RELICS' FACES in the corner panel (owner, 2026-09-04: "more
// representative of what they do and what they are", then "relic icons should
// match the style of the other icons"): one SVG per skill, the same object the
// relic takes in the world (relicShapes.ts), drawn in the toolbar's idiom
// (BrushIcons.tsx) — gradient-lit solid faces on the isometric grass tile, no
// outlines, a cast shade on the grass, a drop shadow from the tile's own CSS.
// The skill's category colour (gems.ts) is the glow on the grass and the
// object's own material, so the three-colour code a player learns from the
// gems still holds.
//
// GENERATED by .claude/orchestration/refs/hud-icons/relics.py, which projects
// the world shapes onto the tile; edit the art there and rerun it, since the
// polygons below are its output. Gradient ids are prefixed with the skill's
// name because SVG ids are document-global and the panel shows several of
// these at once.

import type { JSX } from 'solid-js';

/** The tile every icon stands on — the toolbar icons' own, verbatim. */
function Tile(props: { prefix: string; glow: string }): JSX.Element {
  return (
    <>
      <defs>
        <linearGradient id={`${props.prefix}-tile-top`} x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stop-color="#a6e08a" />
          <stop offset="1" stop-color="#4f9a4a" />
        </linearGradient>
        <linearGradient id={`${props.prefix}-tile-left`} x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#9a6a45" />
          <stop offset="1" stop-color="#5a3a22" />
        </linearGradient>
        <linearGradient id={`${props.prefix}-tile-right`} x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#6e4a2f" />
          <stop offset="1" stop-color="#3a2415" />
        </linearGradient>
      </defs>
      <ellipse cx="16" cy="27.5" rx="12" ry="3" fill="#000" opacity="0.35" />
      <polygon points="16,13 28,19 16,25 4,19" fill={`url(#${props.prefix}-tile-top)`} />
      <polygon points="4,19 16,25 16,29 4,23" fill={`url(#${props.prefix}-tile-left)`} />
      <polygon points="28,19 16,25 16,29 28,23" fill={`url(#${props.prefix}-tile-right)`} />
      <ellipse cx="16" cy="19" rx="7" ry="3.2" fill={props.glow} opacity="0.3" />
    </>
  );
}

/** Titan's Hand: a modelled hand raised palm-out, fingers up. */
export function TitansHandIcon(): JSX.Element {
  return (
    <svg class="relics-gem" viewBox="0 0 32 32" aria-hidden="true">
      <defs>
        <linearGradient id="titan-amber-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#ffe2b0" />
          <stop offset="1" stop-color="#e2be88" />
        </linearGradient>
        <linearGradient id="titan-amber-1" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#e2be88" />
          <stop offset="1" stop-color="#c49b60" />
        </linearGradient>
        <linearGradient id="titan-amber-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#c49b60" />
          <stop offset="1" stop-color="#a77838" />
        </linearGradient>
        <linearGradient id="titan-amber-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#a77838" />
          <stop offset="1" stop-color="#8a5410" />
        </linearGradient>
      </defs>
      <g transform="translate(0 -1.1)">
        <Tile prefix="titan" glow="#ffb347" />
        <ellipse cx="16" cy="19.2" rx="5" ry="2.4" fill="#2e5a2e" opacity="0.5" />
        <polygon points="15.2,18.2 15.0,15.6 16.8,15.5 16.6,18.1" fill="url(#titan-amber-1)" />
        <polygon points="16.6,18.1 16.8,15.5 18.1,16.1 17.7,18.6" fill="url(#titan-amber-0)" />
        <polygon points="14.2,18.7 13.8,16.2 15.0,15.6 15.2,18.2" fill="url(#titan-amber-2)" />
        <polygon points="17.8,19.3 16.8,19.8 15.4,19.9 14.3,19.4 14.2,18.7 15.2,18.2 16.6,18.1 17.7,18.6" fill="url(#titan-amber-0)" />
        <polygon points="17.7,18.6 18.1,16.1 18.2,17.0 17.8,19.3" fill="url(#titan-amber-0)" />
        <polygon points="14.3,19.4 13.9,17.1 13.8,16.2 14.2,18.7" fill="url(#titan-amber-3)" />
        <polygon points="18.7,17.2 18.8,16.7 19.6,15.7 19.4,16.2" fill="url(#titan-amber-3)" />
        <polygon points="19.3,14.4 19.3,15.0 18.7,15.1 18.6,14.5" fill="url(#titan-amber-1)" />
        <polygon points="19.3,15.0 19.1,15.5 18.7,15.1" fill="url(#titan-amber-0)" />
        <polygon points="19.6,15.2 19.1,15.5 19.3,15.0" fill="url(#titan-amber-0)" />
        <polygon points="19.8,14.7 19.6,15.2 19.3,15.0 19.3,14.4" fill="url(#titan-amber-0)" />
        <polygon points="18.7,15.1 19.1,15.5 18.5,15.3" fill="url(#titan-amber-1)" />
        <polygon points="18.6,14.5 18.7,15.1 18.5,15.3 18.3,14.8" fill="url(#titan-amber-2)" />
        <polygon points="19.3,14.0 19.3,14.4 18.6,14.5 18.7,14.1" fill="url(#titan-amber-2)" />
        <polygon points="19.4,15.5 19.1,15.5 19.6,15.2" fill="url(#titan-amber-0)" />
        <polygon points="18.5,15.3 19.1,15.5 18.9,15.5" fill="url(#titan-amber-1)" />
        <polygon points="13.9,9.4 13.8,10.0 13.3,10.1 13.1,9.5" fill="url(#titan-amber-1)" />
        <polygon points="13.8,10.0 13.6,10.5 13.3,10.1" fill="url(#titan-amber-0)" />
        <polygon points="19.6,14.2 19.8,14.7 19.3,14.4 19.3,14.0" fill="url(#titan-amber-1)" />
        <polygon points="18.9,15.5 19.1,15.5 19.4,15.5" fill="url(#titan-amber-0)" />
        <polygon points="14.1,10.2 13.6,10.5 13.8,10.0" fill="url(#titan-amber-0)" />
        <polygon points="14.4,9.7 14.1,10.2 13.8,10.0 13.9,9.4" fill="url(#titan-amber-0)" />
        <polygon points="13.3,10.1 13.6,10.5 13.1,10.3" fill="url(#titan-amber-1)" />
        <polygon points="18.7,14.1 18.6,14.5 18.3,14.8 18.5,14.3" fill="url(#titan-amber-3)" />
        <polygon points="19.5,15.5 19.1,15.7 18.7,15.3 18.5,14.6 18.7,14.1 19.0,13.9 19.5,14.3 19.6,14.9" fill="url(#titan-amber-2)" />
        <polygon points="18.8,16.7 18.7,17.2 18.3,17.5 17.9,17.5 13.4,16.7 12.9,16.5 12.6,16.1 12.4,15.6 12.4,11.1 12.6,10.6 12.9,10.4 13.4,10.3 17.9,11.1 18.3,11.3 18.7,11.8 18.8,12.3" fill="url(#titan-amber-1)" />
        <polygon points="12.9,10.4 12.6,10.6 13.3,9.6 13.7,9.3" fill="url(#titan-amber-0)" />
        <polygon points="13.1,9.5 13.3,10.1 13.1,10.3 12.9,9.8" fill="url(#titan-amber-2)" />
        <polygon points="13.8,9.0 13.9,9.4 13.1,9.5 13.3,9.0" fill="url(#titan-amber-2)" />
        <polygon points="18.8,16.7 18.8,12.3 19.6,11.2 19.6,15.7" fill="url(#titan-amber-3)" />
        <polygon points="14.0,10.5 13.6,10.5 14.1,10.2" fill="url(#titan-amber-0)" />
        <polygon points="13.1,10.3 13.6,10.5 13.4,10.5" fill="url(#titan-amber-1)" />
        <polygon points="14.1,9.2 14.4,9.7 13.9,9.4 13.8,9.0" fill="url(#titan-amber-1)" />
        <polygon points="15.5,9.7 15.4,10.3 14.9,10.4 14.7,9.8" fill="url(#titan-amber-1)" />
        <polygon points="15.4,10.3 15.2,10.8 14.9,10.4" fill="url(#titan-amber-0)" />
        <polygon points="13.4,10.5 13.6,10.5 14.0,10.5" fill="url(#titan-amber-0)" />
        <polygon points="13.4,10.3 12.9,10.4 13.7,9.3 14.1,9.3" fill="url(#titan-amber-0)" />
        <polygon points="15.7,10.5 15.2,10.8 15.4,10.3" fill="url(#titan-amber-0)" />
        <polygon points="13.3,9.0 13.1,9.5 12.9,9.8 13.1,9.3" fill="url(#titan-amber-3)" />
        <polygon points="14.2,9.9 13.9,10.1 13.4,10.1 13.0,9.9 13.0,9.7 13.3,9.5 13.8,9.5 14.2,9.6" fill="url(#titan-amber-0)" />
        <polygon points="16.0,10.0 15.7,10.5 15.4,10.3 15.5,9.7" fill="url(#titan-amber-0)" />
        <polygon points="14.9,10.4 15.2,10.8 14.7,10.6" fill="url(#titan-amber-1)" />
        <polygon points="14.7,9.8 14.9,10.4 14.7,10.6 14.5,10.1" fill="url(#titan-amber-2)" />
        <polygon points="19.5,14.3 22.1,13.6 22.3,14.3 19.6,14.9" fill="url(#titan-amber-0)" />
        <polygon points="15.4,9.3 15.5,9.7 14.7,9.8 14.9,9.3" fill="url(#titan-amber-2)" />
        <polygon points="13.3,9.5 13.3,7.2 13.8,7.2 13.8,9.5" fill="url(#titan-amber-1)" />
        <polygon points="15.5,10.8 15.2,10.8 15.7,10.5" fill="url(#titan-amber-0)" />
        <polygon points="19.6,14.9 22.3,14.3 22.2,14.9 19.5,15.5" fill="url(#titan-amber-0)" />
        <polygon points="14.7,10.6 15.2,10.8 15.0,10.8" fill="url(#titan-amber-1)" />
        <polygon points="13.8,9.5 13.8,7.2 14.2,7.4 14.2,9.6" fill="url(#titan-amber-0)" />
        <polygon points="15.7,9.5 16.0,10.0 15.5,9.7 15.4,9.3" fill="url(#titan-amber-1)" />
        <polygon points="17.1,10.0 17.0,10.6 16.5,10.6 16.3,10.1" fill="url(#titan-amber-1)" />
        <polygon points="17.0,10.6 16.8,11.1 16.5,10.6" fill="url(#titan-amber-0)" />
        <polygon points="13.0,9.7 13.0,7.4 13.3,7.2 13.3,9.5" fill="url(#titan-amber-2)" />
        <polygon points="15.0,10.8 15.2,10.8 15.5,10.8" fill="url(#titan-amber-0)" />
        <polygon points="17.3,10.8 16.8,11.1 17.0,10.6" fill="url(#titan-amber-0)" />
        <polygon points="19.0,13.9 21.7,13.3 22.1,13.6 19.5,14.3" fill="url(#titan-amber-2)" />
        <polygon points="14.9,9.3 14.7,9.8 14.5,10.1 14.7,9.6" fill="url(#titan-amber-3)" />
        <polygon points="15.8,10.2 15.5,10.3 15.0,10.4 14.6,10.2 14.6,9.9 14.9,9.8 15.4,9.8 15.8,9.9" fill="url(#titan-amber-0)" />
        <polygon points="17.5,10.3 17.3,10.8 17.0,10.6 17.1,10.0" fill="url(#titan-amber-0)" />
        <polygon points="16.5,10.6 16.8,11.1 16.3,10.9" fill="url(#titan-amber-1)" />
        <polygon points="19.5,15.5 22.2,14.9 21.8,15.0 19.1,15.7" fill="url(#titan-amber-0)" />
        <polygon points="16.3,10.1 16.5,10.6 16.3,10.9 16.0,10.4" fill="url(#titan-amber-2)" />
        <polygon points="17.0,9.6 17.1,10.0 16.3,10.1 16.5,9.6" fill="url(#titan-amber-2)" />
        <polygon points="14.2,9.6 14.2,7.4 14.2,7.6 14.2,9.9" fill="url(#titan-amber-0)" />
        <polygon points="17.1,11.1 16.8,11.1 17.3,10.8" fill="url(#titan-amber-0)" />
        <polygon points="17.9,11.1 13.4,10.3 14.1,9.3 18.6,10.1" fill="url(#titan-amber-0)" />
        <polygon points="16.3,10.9 16.8,11.1 16.6,11.1" fill="url(#titan-amber-1)" />
        <polygon points="14.9,9.8 14.9,7.3 15.4,7.3 15.4,9.8" fill="url(#titan-amber-1)" />
        <polygon points="13.9,7.2 13.8,7.8 13.3,7.8 13.1,7.2" fill="url(#titan-amber-1)" />
        <polygon points="13.8,7.8 13.6,8.2 13.3,7.8" fill="url(#titan-amber-0)" />
        <polygon points="17.3,9.8 17.5,10.3 17.1,10.0 17.0,9.6" fill="url(#titan-amber-1)" />
        <polygon points="18.7,10.3 18.6,10.9 18.0,10.9 17.9,10.3" fill="url(#titan-amber-1)" />
        <polygon points="18.6,10.9 18.4,11.4 18.0,10.9" fill="url(#titan-amber-0)" />
        <polygon points="16.6,11.1 16.8,11.1 17.1,11.1" fill="url(#titan-amber-0)" />
        <polygon points="14.1,8.0 13.6,8.2 13.8,7.8" fill="url(#titan-amber-0)" />
        <polygon points="15.4,9.8 15.4,7.3 15.8,7.4 15.8,9.9" fill="url(#titan-amber-0)" />
        <polygon points="18.9,11.1 18.4,11.4 18.6,10.9" fill="url(#titan-amber-0)" />
        <polygon points="14.6,9.9 14.6,7.4 14.9,7.3 14.9,9.8" fill="url(#titan-amber-2)" />
        <polygon points="14.3,7.5 14.1,8.0 13.8,7.8 13.9,7.2" fill="url(#titan-amber-0)" />
        <polygon points="13.3,7.8 13.6,8.2 13.1,8.1" fill="url(#titan-amber-1)" />
        <polygon points="16.5,9.6 16.3,10.1 16.0,10.4 16.3,9.9" fill="url(#titan-amber-3)" />
        <polygon points="17.4,10.5 17.1,10.6 16.6,10.6 16.2,10.5 16.2,10.2 16.5,10.1 17.0,10.0 17.4,10.2" fill="url(#titan-amber-0)" />
        <polygon points="19.1,10.6 18.9,11.1 18.6,10.9 18.7,10.3" fill="url(#titan-amber-0)" />
        <polygon points="18.0,10.9 18.4,11.4 17.9,11.2" fill="url(#titan-amber-1)" />
        <polygon points="13.1,7.2 13.3,7.8 13.1,8.1 12.9,7.6" fill="url(#titan-amber-2)" />
        <polygon points="13.8,6.8 13.9,7.2 13.1,7.2 13.3,6.8" fill="url(#titan-amber-2)" />
        <polygon points="22.1,13.7 22.0,14.5 21.3,14.5 21.1,13.8" fill="url(#titan-amber-1)" />
        <polygon points="22.0,14.5 21.8,15.1 21.3,14.5" fill="url(#titan-amber-0)" />
        <polygon points="13.9,8.2 13.6,8.2 14.1,8.0" fill="url(#titan-amber-0)" />
        <polygon points="17.9,10.3 18.0,10.9 17.9,11.2 17.6,10.7" fill="url(#titan-amber-2)" />
        <polygon points="18.6,9.9 18.7,10.3 17.9,10.3 18.0,9.9" fill="url(#titan-amber-2)" />
        <polygon points="18.7,11.4 18.4,11.4 18.9,11.1" fill="url(#titan-amber-0)" />
        <polygon points="16.5,10.1 16.5,7.8 17.0,7.7 17.0,10.0" fill="url(#titan-amber-1)" />
        <polygon points="13.1,8.1 13.6,8.2 13.4,8.3" fill="url(#titan-amber-1)" />
        <polygon points="18.8,12.3 18.7,11.8 19.4,10.7 19.6,11.2" fill="url(#titan-amber-2)" />
        <polygon points="15.8,9.9 15.8,7.4 15.8,7.7 15.8,10.2" fill="url(#titan-amber-0)" />
        <polygon points="22.5,14.8 21.8,15.1 22.0,14.5" fill="url(#titan-amber-0)" />
        <polygon points="14.1,7.0 14.3,7.5 13.9,7.2 13.8,6.8" fill="url(#titan-amber-1)" />
        <polygon points="17.9,11.2 18.4,11.4 18.2,11.4" fill="url(#titan-amber-1)" />
        <polygon points="13.4,8.3 13.6,8.2 13.9,8.2" fill="url(#titan-amber-0)" />
        <polygon points="18.9,10.1 19.1,10.6 18.7,10.3 18.6,9.9" fill="url(#titan-amber-1)" />
        <polygon points="17.0,10.0 17.0,7.7 17.4,7.9 17.4,10.2" fill="url(#titan-amber-0)" />
        <polygon points="22.7,14.1 22.5,14.8 22.0,14.5 22.1,13.7" fill="url(#titan-amber-0)" />
        <polygon points="18.2,11.4 18.4,11.4 18.7,11.4" fill="url(#titan-amber-0)" />
        <polygon points="21.3,14.5 21.8,15.1 21.1,14.9" fill="url(#titan-amber-1)" />
        <polygon points="16.2,10.2 16.2,7.9 16.5,7.8 16.5,10.1" fill="url(#titan-amber-2)" />
        <polygon points="13.3,6.8 13.1,7.2 12.9,7.6 13.1,7.1" fill="url(#titan-amber-3)" />
        <polygon points="14.2,7.6 13.9,7.8 13.4,7.9 13.1,7.7 13.1,7.4 13.4,7.2 13.8,7.2 14.1,7.4" fill="url(#titan-amber-0)" />
        <polygon points="18.7,11.8 18.3,11.3 19.1,10.3 19.4,10.7" fill="url(#titan-amber-1)" />
        <polygon points="15.5,7.2 15.4,7.8 14.9,7.9 14.7,7.3" fill="url(#titan-amber-1)" />
        <polygon points="15.4,7.8 15.2,8.3 14.9,7.9" fill="url(#titan-amber-0)" />
        <polygon points="18.3,11.3 17.9,11.1 18.6,10.1 19.1,10.3" fill="url(#titan-amber-0)" />
        <polygon points="18.0,9.9 17.9,10.3 17.6,10.7 17.9,10.2" fill="url(#titan-amber-3)" />
        <polygon points="19.0,10.7 18.7,10.9 18.2,10.9 17.8,10.8 17.8,10.5 18.1,10.3 18.6,10.3 19.0,10.5" fill="url(#titan-amber-0)" />
        <polygon points="21.1,13.8 21.3,14.5 21.1,14.9 20.8,14.2" fill="url(#titan-amber-2)" />
        <polygon points="15.7,8.0 15.2,8.3 15.4,7.8" fill="url(#titan-amber-0)" />
        <polygon points="22.0,13.2 22.1,13.7 21.1,13.8 21.3,13.2" fill="url(#titan-amber-2)" />
        <polygon points="18.1,10.3 18.1,8.5 18.6,8.5 18.6,10.3" fill="url(#titan-amber-1)" />
        <polygon points="22.2,15.1 21.8,15.1 22.5,14.8" fill="url(#titan-amber-0)" />
        <polygon points="15.9,7.5 15.7,8.0 15.4,7.8 15.5,7.2" fill="url(#titan-amber-0)" />
        <polygon points="14.9,7.9 15.2,8.3 14.7,8.1" fill="url(#titan-amber-1)" />
        <polygon points="13.4,7.2 13.3,5.5 13.7,5.5 13.8,7.2" fill="url(#titan-amber-1)" />
        <polygon points="17.4,10.2 17.4,7.9 17.4,8.2 17.4,10.5" fill="url(#titan-amber-0)" />
        <polygon points="18.6,10.3 18.6,8.5 19.0,8.6 19.0,10.5" fill="url(#titan-amber-0)" />
        <polygon points="21.1,14.9 21.8,15.1 21.5,15.2" fill="url(#titan-amber-1)" />
        <polygon points="17.8,10.5 17.8,8.7 18.1,8.5 18.1,10.3" fill="url(#titan-amber-2)" />
        <polygon points="14.7,7.3 14.9,7.9 14.7,8.1 14.5,7.6" fill="url(#titan-amber-2)" />
        <polygon points="15.4,6.8 15.5,7.2 14.7,7.3 14.9,6.9" fill="url(#titan-amber-2)" />
        <polygon points="22.5,13.4 22.7,14.1 22.1,13.7 22.0,13.2" fill="url(#titan-amber-1)" />
        <polygon points="13.8,7.2 13.7,5.5 14.1,5.6 14.1,7.4" fill="url(#titan-amber-1)" />
        <polygon points="15.5,8.3 15.2,8.3 15.7,8.0" fill="url(#titan-amber-0)" />
        <polygon points="13.1,7.4 13.0,5.7 13.3,5.5 13.4,7.2" fill="url(#titan-amber-2)" />
        <polygon points="17.1,7.7 17.0,8.3 16.5,8.3 16.3,7.8" fill="url(#titan-amber-1)" />
        <polygon points="21.5,15.2 21.8,15.1 22.2,15.1" fill="url(#titan-amber-0)" />
        <polygon points="17.0,8.3 16.8,8.7 16.5,8.3" fill="url(#titan-amber-0)" />
        <polygon points="14.7,8.1 15.2,8.3 15.0,8.3" fill="url(#titan-amber-1)" />
        <polygon points="17.3,8.5 16.8,8.7 17.0,8.3" fill="url(#titan-amber-0)" />
        <polygon points="15.7,7.0 15.9,7.5 15.5,7.2 15.4,6.8" fill="url(#titan-amber-1)" />
        <polygon points="21.3,13.2 21.1,13.8 20.8,14.2 21.1,13.5" fill="url(#titan-amber-3)" />
        <polygon points="22.4,14.6 22.0,14.9 21.4,14.7 21.1,14.2 21.1,13.7 21.6,13.4 22.1,13.6 22.4,14.1" fill="url(#titan-amber-1)" />
        <polygon points="15.0,8.3 15.2,8.3 15.5,8.3" fill="url(#titan-amber-0)" />
        <polygon points="17.5,8.0 17.3,8.5 17.0,8.3 17.1,7.7" fill="url(#titan-amber-0)" />
        <polygon points="16.5,8.3 16.8,8.7 16.3,8.6" fill="url(#titan-amber-1)" />
        <polygon points="18.6,8.4 18.6,9.0 18.1,9.1 17.9,8.5" fill="url(#titan-amber-1)" />
        <polygon points="18.6,9.0 18.4,9.5 18.1,9.1" fill="url(#titan-amber-0)" />
        <polygon points="19.0,10.5 19.0,8.6 19.0,8.9 19.0,10.7" fill="url(#titan-amber-0)" />
        <polygon points="14.9,6.9 14.7,7.3 14.5,7.6 14.7,7.1" fill="url(#titan-amber-3)" />
        <polygon points="15.7,7.7 15.4,7.9 15.0,7.9 14.7,7.7 14.7,7.5 15.0,7.3 15.4,7.2 15.7,7.4" fill="url(#titan-amber-0)" />
        <polygon points="14.1,7.4 14.1,5.6 14.1,5.9 14.2,7.6" fill="url(#titan-amber-0)" />
        <polygon points="18.9,9.2 18.4,9.5 18.6,9.0" fill="url(#titan-amber-0)" />
        <polygon points="16.3,7.8 16.5,8.3 16.3,8.6 16.1,8.1" fill="url(#titan-amber-2)" />
        <polygon points="17.0,7.3 17.1,7.7 16.3,7.8 16.5,7.3" fill="url(#titan-amber-2)" />
        <polygon points="17.1,8.7 16.8,8.7 17.3,8.5" fill="url(#titan-amber-0)" />
        <polygon points="19.1,8.7 18.9,9.2 18.6,9.0 18.6,8.4" fill="url(#titan-amber-0)" />
        <polygon points="18.1,9.1 18.4,9.5 17.9,9.3" fill="url(#titan-amber-1)" />
        <polygon points="13.8,5.5 13.7,6.0 13.2,6.1 13.1,5.5" fill="url(#titan-amber-1)" />
        <polygon points="13.7,6.0 13.5,6.4 13.2,6.1" fill="url(#titan-amber-0)" />
        <polygon points="16.3,8.6 16.8,8.7 16.6,8.8" fill="url(#titan-amber-1)" />
        <polygon points="14.0,6.2 13.5,6.4 13.7,6.0" fill="url(#titan-amber-0)" />
        <polygon points="17.3,7.5 17.5,8.0 17.1,7.7 17.0,7.3" fill="url(#titan-amber-1)" />
        <polygon points="17.9,8.5 18.1,9.1 17.9,9.3 17.7,8.8" fill="url(#titan-amber-2)" />
        <polygon points="16.6,8.8 16.8,8.7 17.1,8.7" fill="url(#titan-amber-0)" />
        <polygon points="18.6,8.0 18.6,8.4 17.9,8.5 18.1,8.1" fill="url(#titan-amber-2)" />
        <polygon points="14.2,5.7 14.0,6.2 13.7,6.0 13.8,5.5" fill="url(#titan-amber-0)" />
        <polygon points="13.2,6.1 13.5,6.4 13.1,6.3" fill="url(#titan-amber-1)" />
        <polygon points="18.7,9.5 18.4,9.5 18.9,9.2" fill="url(#titan-amber-0)" />
        <polygon points="15.0,7.3 14.9,5.3 15.3,5.3 15.4,7.2" fill="url(#titan-amber-1)" />
        <polygon points="16.5,7.3 16.3,7.8 16.1,8.1 16.3,7.6" fill="url(#titan-amber-3)" />
        <polygon points="17.3,8.1 17.0,8.3 16.6,8.4 16.3,8.2 16.3,7.9 16.6,7.7 17.0,7.7 17.3,7.9" fill="url(#titan-amber-0)" />
        <polygon points="17.9,9.3 18.4,9.5 18.2,9.5" fill="url(#titan-amber-1)" />
        <polygon points="13.1,5.5 13.2,6.1 13.1,6.3 12.9,5.9" fill="url(#titan-amber-2)" />
        <polygon points="13.7,5.1 13.8,5.5 13.1,5.5 13.2,5.2" fill="url(#titan-amber-2)" />
        <polygon points="18.9,8.2 19.1,8.7 18.6,8.4 18.6,8.0" fill="url(#titan-amber-1)" />
        <polygon points="13.8,6.4 13.5,6.4 14.0,6.2" fill="url(#titan-amber-0)" />
        <polygon points="15.4,7.2 15.3,5.3 15.6,5.5 15.7,7.4" fill="url(#titan-amber-1)" />
        <polygon points="14.7,7.5 14.6,5.5 14.9,5.3 15.0,7.3" fill="url(#titan-amber-2)" />
        <polygon points="18.2,9.5 18.4,9.5 18.7,9.5" fill="url(#titan-amber-0)" />
        <polygon points="13.1,6.3 13.5,6.4 13.4,6.5" fill="url(#titan-amber-1)" />
        <polygon points="14.0,5.3 14.2,5.7 13.8,5.5 13.7,5.1" fill="url(#titan-amber-1)" />
        <polygon points="18.1,8.1 17.9,8.5 17.7,8.8 17.9,8.3" fill="url(#titan-amber-3)" />
        <polygon points="18.9,8.9 18.6,9.1 18.2,9.1 17.9,8.9 17.8,8.7 18.1,8.5 18.6,8.4 18.9,8.6" fill="url(#titan-amber-0)" />
        <polygon points="13.4,6.5 13.5,6.4 13.8,6.4" fill="url(#titan-amber-0)" />
        <polygon points="16.6,7.7 16.5,6.0 16.9,5.9 17.0,7.7" fill="url(#titan-amber-1)" />
        <polygon points="13.2,5.2 13.1,5.5 12.9,5.9 13.1,5.4" fill="url(#titan-amber-3)" />
        <polygon points="14.0,5.9 13.7,6.1 13.4,6.2 13.1,6.0 13.1,5.7 13.3,5.5 13.7,5.4 14.0,5.6" fill="url(#titan-amber-0)" />
        <polygon points="18.1,8.5 18.1,7.0 18.5,7.0 18.6,8.4" fill="url(#titan-amber-1)" />
        <polygon points="15.7,7.4 15.6,5.5 15.7,5.7 15.7,7.7" fill="url(#titan-amber-0)" />
        <polygon points="17.0,7.7 16.9,5.9 17.2,6.1 17.3,7.9" fill="url(#titan-amber-1)" />
        <polygon points="16.3,7.9 16.2,6.2 16.5,6.0 16.6,7.7" fill="url(#titan-amber-2)" />
        <polygon points="18.6,8.4 18.5,7.0 18.8,7.2 18.9,8.6" fill="url(#titan-amber-1)" />
        <polygon points="17.8,8.7 17.8,7.3 18.1,7.0 18.1,8.5" fill="url(#titan-amber-2)" />
        <polygon points="22.1,13.6 23.2,12.4 23.5,12.9 22.4,14.1" fill="url(#titan-amber-1)" />
        <polygon points="15.3,5.3 15.3,5.9 14.8,5.9 14.7,5.4" fill="url(#titan-amber-1)" />
        <polygon points="15.3,5.9 15.1,6.3 14.8,5.9" fill="url(#titan-amber-0)" />
        <polygon points="22.4,14.1 23.5,12.9 23.5,13.4 22.4,14.6" fill="url(#titan-amber-0)" />
        <polygon points="21.6,13.4 22.7,12.2 23.2,12.4 22.1,13.6" fill="url(#titan-amber-2)" />
        <polygon points="15.6,6.0 15.1,6.3 15.3,5.9" fill="url(#titan-amber-0)" />
        <polygon points="13.3,5.5 13.1,4.3 13.5,4.2 13.7,5.4" fill="url(#titan-amber-2)" />
        <polygon points="17.3,7.9 17.2,6.1 17.3,6.4 17.3,8.1" fill="url(#titan-amber-0)" />
        <polygon points="15.8,5.6 15.6,6.0 15.3,5.9 15.3,5.3" fill="url(#titan-amber-0)" />
        <polygon points="14.8,5.9 15.1,6.3 14.6,6.1" fill="url(#titan-amber-1)" />
        <polygon points="13.1,5.7 12.9,4.5 13.1,4.3 13.3,5.5" fill="url(#titan-amber-2)" />
        <polygon points="18.6,7.0 18.5,7.6 18.0,7.6 17.9,7.1" fill="url(#titan-amber-1)" />
        <polygon points="18.9,8.6 18.8,7.2 18.9,7.5 18.9,8.9" fill="url(#titan-amber-0)" />
        <polygon points="18.5,7.6 18.3,8.0 18.0,7.6" fill="url(#titan-amber-0)" />
        <polygon points="13.7,5.4 13.5,4.2 13.8,4.4 14.0,5.6" fill="url(#titan-amber-1)" />
        <polygon points="16.9,5.9 16.9,6.5 16.4,6.5 16.3,6.0" fill="url(#titan-amber-1)" />
        <polygon points="16.9,6.5 16.7,6.9 16.4,6.5" fill="url(#titan-amber-0)" />
        <polygon points="22.4,14.6 23.5,13.4 23.1,13.7 22.0,14.9" fill="url(#titan-amber-0)" />
        <polygon points="14.7,5.4 14.8,5.9 14.6,6.1 14.4,5.7" fill="url(#titan-amber-2)" />
        <polygon points="18.8,7.8 18.3,8.0 18.5,7.6" fill="url(#titan-amber-0)" />
        <polygon points="15.3,5.0 15.3,5.3 14.7,5.4 14.8,5.0" fill="url(#titan-amber-2)" />
        <polygon points="15.4,6.3 15.1,6.3 15.6,6.0" fill="url(#titan-amber-0)" />
        <polygon points="19.0,7.3 18.8,7.8 18.5,7.6 18.6,7.0" fill="url(#titan-amber-0)" />
        <polygon points="17.2,6.7 16.7,6.9 16.9,6.5" fill="url(#titan-amber-0)" />
        <polygon points="18.0,7.6 18.3,8.0 17.9,7.8" fill="url(#titan-amber-1)" />
        <polygon points="13.1,6.0 12.9,4.8 12.9,4.5 13.1,5.7" fill="url(#titan-amber-3)" />
        <polygon points="14.6,6.1 15.1,6.3 14.9,6.3" fill="url(#titan-amber-1)" />
        <polygon points="17.4,6.2 17.2,6.7 16.9,6.5 16.9,5.9" fill="url(#titan-amber-0)" />
        <polygon points="16.4,6.5 16.7,6.9 16.2,6.8" fill="url(#titan-amber-1)" />
        <polygon points="15.6,5.1 15.8,5.6 15.3,5.3 15.3,5.0" fill="url(#titan-amber-1)" />
        <polygon points="17.9,7.1 18.0,7.6 17.9,7.8 17.7,7.4" fill="url(#titan-amber-2)" />
        <polygon points="14.9,6.3 15.1,6.3 15.4,6.3" fill="url(#titan-amber-0)" />
        <polygon points="18.5,6.7 18.6,7.0 17.9,7.1 18.0,6.7" fill="url(#titan-amber-2)" />
        <polygon points="18.6,8.0 18.3,8.0 18.8,7.8" fill="url(#titan-amber-0)" />
        <polygon points="16.3,6.0 16.4,6.5 16.2,6.8 16.0,6.3" fill="url(#titan-amber-2)" />
        <polygon points="16.9,5.6 16.9,5.9 16.3,6.0 16.4,5.6" fill="url(#titan-amber-2)" />
        <polygon points="13.6,4.3 13.5,4.8 13.1,4.8 13.0,4.3" fill="url(#titan-amber-1)" />
        <polygon points="13.5,4.8 13.4,5.1 13.1,4.8" fill="url(#titan-amber-0)" />
        <polygon points="14.8,5.0 14.7,5.4 14.4,5.7 14.6,5.2" fill="url(#titan-amber-3)" />
        <polygon points="15.6,5.7 15.3,6.0 14.9,6.0 14.7,5.8 14.6,5.5 14.9,5.3 15.3,5.3 15.6,5.4" fill="url(#titan-amber-0)" />
        <polygon points="17.0,6.9 16.7,6.9 17.2,6.7" fill="url(#titan-amber-0)" />
        <polygon points="17.9,7.8 18.3,8.0 18.2,8.0" fill="url(#titan-amber-1)" />
        <polygon points="13.8,4.9 13.4,5.1 13.5,4.8" fill="url(#titan-amber-0)" />
        <polygon points="18.8,6.9 19.0,7.3 18.6,7.0 18.5,6.7" fill="url(#titan-amber-1)" />
        <polygon points="16.2,6.8 16.7,6.9 16.5,6.9" fill="url(#titan-amber-1)" />
        <polygon points="18.2,8.0 18.3,8.0 18.6,8.0" fill="url(#titan-amber-0)" />
        <polygon points="14.0,4.5 13.8,4.9 13.5,4.8 13.6,4.3" fill="url(#titan-amber-0)" />
        <polygon points="13.1,4.8 13.4,5.1 12.9,5.0" fill="url(#titan-amber-1)" />
        <polygon points="17.2,5.8 17.4,6.2 16.9,5.9 16.9,5.6" fill="url(#titan-amber-1)" />
        <polygon points="16.5,6.9 16.7,6.9 17.0,6.9" fill="url(#titan-amber-0)" />
        <polygon points="18.0,6.7 17.9,7.1 17.7,7.4 17.9,6.9" fill="url(#titan-amber-3)" />
        <polygon points="18.8,7.4 18.5,7.7 18.2,7.7 17.9,7.6 17.8,7.3 18.1,7.0 18.5,7.0 18.8,7.2" fill="url(#titan-amber-0)" />
        <polygon points="13.0,4.3 13.1,4.8 12.9,5.0 12.8,4.6" fill="url(#titan-amber-2)" />
        <polygon points="13.5,4.0 13.6,4.3 13.0,4.3 13.1,4.0" fill="url(#titan-amber-2)" />
        <polygon points="16.4,5.6 16.3,6.0 16.0,6.3 16.2,5.9" fill="url(#titan-amber-3)" />
        <polygon points="17.2,6.4 16.9,6.6 16.5,6.6 16.3,6.5 16.2,6.2 16.5,5.9 16.9,5.9 17.2,6.1" fill="url(#titan-amber-0)" />
        <polygon points="13.6,5.1 13.4,5.1 13.8,4.9" fill="url(#titan-amber-0)" />
        <polygon points="23.2,12.5 23.1,13.3 22.5,13.3 22.3,12.6" fill="url(#titan-amber-1)" />
        <polygon points="23.1,13.3 22.9,13.8 22.5,13.3" fill="url(#titan-amber-0)" />
        <polygon points="12.9,5.0 13.4,5.1 13.2,5.2" fill="url(#titan-amber-1)" />
        <polygon points="13.8,4.1 14.0,4.5 13.6,4.3 13.5,4.0" fill="url(#titan-amber-1)" />
        <polygon points="23.5,13.5 22.9,13.8 23.1,13.3" fill="url(#titan-amber-0)" />
        <polygon points="13.2,5.2 13.4,5.1 13.6,5.1" fill="url(#titan-amber-0)" />
        <polygon points="14.9,5.3 14.7,4.0 15.1,3.9 15.3,5.3" fill="url(#titan-amber-2)" />
        <polygon points="18.1,7.0 18.0,6.0 18.4,6.0 18.5,7.0" fill="url(#titan-amber-2)" />
        <polygon points="23.7,12.9 23.5,13.5 23.1,13.3 23.2,12.5" fill="url(#titan-amber-0)" />
        <polygon points="13.1,4.0 13.0,4.3 12.8,4.6 12.9,4.2" fill="url(#titan-amber-3)" />
        <polygon points="22.5,13.3 22.9,13.8 22.3,13.6" fill="url(#titan-amber-1)" />
        <polygon points="14.6,5.5 14.5,4.2 14.7,4.0 14.9,5.3" fill="url(#titan-amber-2)" />
        <polygon points="17.8,7.3 17.7,6.3 18.0,6.0 18.1,7.0" fill="url(#titan-amber-2)" />
        <polygon points="15.3,5.3 15.1,3.9 15.4,4.1 15.6,5.4" fill="url(#titan-amber-1)" />
        <polygon points="18.5,7.0 18.4,6.0 18.6,6.1 18.8,7.2" fill="url(#titan-amber-1)" />
        <polygon points="16.5,5.9 16.3,4.7 16.7,4.6 16.9,5.9" fill="url(#titan-amber-2)" />
        <polygon points="22.3,12.6 22.5,13.3 22.3,13.6 22.0,13.0" fill="url(#titan-amber-2)" />
        <polygon points="23.1,12.1 23.2,12.5 22.3,12.6 22.5,12.1" fill="url(#titan-amber-2)" />
        <polygon points="16.2,6.2 16.1,4.9 16.3,4.7 16.5,5.9" fill="url(#titan-amber-2)" />
        <polygon points="23.3,13.8 22.9,13.8 23.5,13.5" fill="url(#titan-amber-0)" />
        <polygon points="14.7,5.8 14.5,4.5 14.5,4.2 14.6,5.5" fill="url(#titan-amber-3)" />
        <polygon points="17.9,7.6 17.7,6.5 17.7,6.3 17.8,7.3" fill="url(#titan-amber-3)" />
        <polygon points="16.9,5.9 16.7,4.6 17.0,4.8 17.2,6.1" fill="url(#titan-amber-1)" />
        <polygon points="18.4,6.1 18.3,6.5 17.9,6.6 17.8,6.1" fill="url(#titan-amber-1)" />
        <polygon points="18.3,6.5 18.2,6.9 17.9,6.6" fill="url(#titan-amber-0)" />
        <polygon points="22.3,13.6 22.9,13.8 22.7,13.8" fill="url(#titan-amber-1)" />
        <polygon points="18.6,6.7 18.2,6.9 18.3,6.5" fill="url(#titan-amber-0)" />
        <polygon points="23.5,12.3 23.7,12.9 23.2,12.5 23.1,12.1" fill="url(#titan-amber-1)" />
        <polygon points="22.7,13.8 22.9,13.8 23.3,13.8" fill="url(#titan-amber-0)" />
        <polygon points="18.8,6.3 18.6,6.7 18.3,6.5 18.4,6.1" fill="url(#titan-amber-0)" />
        <polygon points="16.3,6.5 16.1,5.2 16.1,4.9 16.2,6.2" fill="url(#titan-amber-3)" />
        <polygon points="17.9,6.6 18.2,6.9 17.8,6.8" fill="url(#titan-amber-1)" />
        <polygon points="15.1,4.0 15.1,4.5 14.7,4.5 14.5,4.0" fill="url(#titan-amber-1)" />
        <polygon points="15.1,4.5 14.9,4.8 14.7,4.5" fill="url(#titan-amber-0)" />
        <polygon points="17.8,6.1 17.9,6.6 17.8,6.8 17.6,6.4" fill="url(#titan-amber-2)" />
        <polygon points="22.5,12.1 22.3,12.6 22.0,13.0 22.3,12.4" fill="url(#titan-amber-3)" />
        <polygon points="15.4,4.6 14.9,4.8 15.1,4.5" fill="url(#titan-amber-0)" />
        <polygon points="18.3,5.7 18.4,6.1 17.8,6.1 17.9,5.8" fill="url(#titan-amber-2)" />
        <polygon points="18.5,6.9 18.2,6.9 18.6,6.7" fill="url(#titan-amber-0)" />
        <polygon points="15.5,4.2 15.4,4.6 15.1,4.5 15.1,4.0" fill="url(#titan-amber-0)" />
        <polygon points="14.7,4.5 14.9,4.8 14.5,4.7" fill="url(#titan-amber-1)" />
        <polygon points="16.8,4.7 16.7,5.2 16.3,5.2 16.2,4.8" fill="url(#titan-amber-1)" />
        <polygon points="16.7,5.2 16.5,5.6 16.3,5.2" fill="url(#titan-amber-0)" />
        <polygon points="17.8,6.8 18.2,6.9 18.0,6.9" fill="url(#titan-amber-1)" />
        <polygon points="18.6,5.9 18.8,6.3 18.4,6.1 18.3,5.7" fill="url(#titan-amber-1)" />
        <polygon points="17.0,5.4 16.5,5.6 16.7,5.2" fill="url(#titan-amber-0)" />
        <polygon points="18.0,6.9 18.2,6.9 18.5,6.9" fill="url(#titan-amber-0)" />
        <polygon points="14.5,4.0 14.7,4.5 14.5,4.7 14.3,4.3" fill="url(#titan-amber-2)" />
        <polygon points="15.1,3.7 15.1,4.0 14.5,4.0 14.7,3.7" fill="url(#titan-amber-2)" />
        <polygon points="17.1,5.0 17.0,5.4 16.7,5.2 16.8,4.7" fill="url(#titan-amber-0)" />
        <polygon points="15.2,4.8 14.9,4.8 15.4,4.6" fill="url(#titan-amber-0)" />
        <polygon points="16.3,5.2 16.5,5.6 16.1,5.4" fill="url(#titan-amber-1)" />
        <polygon points="17.9,5.8 17.8,6.1 17.6,6.4 17.8,6.0" fill="url(#titan-amber-3)" />
        <polygon points="14.5,4.7 14.9,4.8 14.8,4.9" fill="url(#titan-amber-1)" />
        <polygon points="15.4,3.8 15.5,4.2 15.1,4.0 15.1,3.7" fill="url(#titan-amber-1)" />
        <polygon points="16.2,4.8 16.3,5.2 16.1,5.4 16.0,5.1" fill="url(#titan-amber-2)" />
        <polygon points="16.7,4.4 16.8,4.7 16.2,4.8 16.3,4.4" fill="url(#titan-amber-2)" />
        <polygon points="14.8,4.9 14.9,4.8 15.2,4.8" fill="url(#titan-amber-0)" />
        <polygon points="16.8,5.6 16.5,5.6 17.0,5.4" fill="url(#titan-amber-0)" />
        <polygon points="16.1,5.4 16.5,5.6 16.4,5.6" fill="url(#titan-amber-1)" />
        <polygon points="14.7,3.7 14.5,4.0 14.3,4.3 14.5,3.9" fill="url(#titan-amber-3)" />
        <polygon points="17.0,4.6 17.1,5.0 16.8,4.7 16.7,4.4" fill="url(#titan-amber-1)" />
        <polygon points="16.4,5.6 16.5,5.6 16.8,5.6" fill="url(#titan-amber-0)" />
        <polygon points="16.3,4.4 16.2,4.8 16.0,5.1 16.1,4.6" fill="url(#titan-amber-3)" />
      </g>
    </svg>
  );
}

/** Quake: sound waves standing out of the ground on either side of an epicentre. */
export function QuakeIcon(): JSX.Element {
  return (
    <svg class="relics-gem" viewBox="0 0 32 32" aria-hidden="true">
      <defs>
        <linearGradient id="quake-crimson-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#ffc2b8" />
          <stop offset="1" stop-color="#db9890" />
        </linearGradient>
        <linearGradient id="quake-crimson-1" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#db9890" />
          <stop offset="1" stop-color="#b86d68" />
        </linearGradient>
        <linearGradient id="quake-crimson-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#b86d68" />
          <stop offset="1" stop-color="#944240" />
        </linearGradient>
        <linearGradient id="quake-crimson-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#944240" />
          <stop offset="1" stop-color="#701818" />
        </linearGradient>
        <linearGradient id="quake-rock-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#7a6a5a" />
          <stop offset="1" stop-color="#66584a" />
        </linearGradient>
        <linearGradient id="quake-rock-1" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#66584a" />
          <stop offset="1" stop-color="#524539" />
        </linearGradient>
        <linearGradient id="quake-rock-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#524539" />
          <stop offset="1" stop-color="#3e3228" />
        </linearGradient>
        <linearGradient id="quake-rock-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#3e3228" />
          <stop offset="1" stop-color="#2a2018" />
        </linearGradient>
      </defs>
      <g transform="translate(0 -3.2)">
        <Tile prefix="quake" glow="#ff5c5c" />
        <ellipse cx="16" cy="19.2" rx="9" ry="3.8" fill="#2e5a2e" opacity="0.5" />
        <polygon points="14.7,14.8 14.7,14.0 19.9,14.4 19.9,15.2" fill="url(#quake-rock-1)" />
        <polygon points="10.0,16.0 10.0,15.2 14.7,14.0 14.7,14.8" fill="url(#quake-rock-2)" />
        <polygon points="11.7,18.9 12.3,18.6 12.8,19.5 12.3,19.9" fill="url(#quake-crimson-0)" />
        <polygon points="11.3,18.0 11.8,17.7 12.3,18.6 11.7,18.9" fill="url(#quake-crimson-1)" />
        <polygon points="10.9,17.0 11.4,16.7 11.8,17.7 11.3,18.0" fill="url(#quake-crimson-1)" />
        <polygon points="12.3,18.6 12.6,18.4 13.0,19.3 12.8,19.5" fill="url(#quake-crimson-0)" />
        <polygon points="11.8,17.7 12.1,17.6 12.6,18.4 12.3,18.6" fill="url(#quake-crimson-0)" />
        <polygon points="11.5,19.0 11.7,18.9 12.3,19.9 12.0,19.9" fill="url(#quake-crimson-2)" />
        <polygon points="11.1,18.1 11.3,18.0 11.7,18.9 11.5,19.0" fill="url(#quake-crimson-2)" />
        <polygon points="19.9,15.2 19.9,14.4 23.6,16.3 23.6,17.1" fill="url(#quake-rock-0)" />
        <polygon points="11.4,16.7 11.8,16.6 12.1,17.6 11.8,17.7" fill="url(#quake-crimson-0)" />
        <polygon points="10.6,15.9 11.1,15.7 11.4,16.7 10.9,17.0" fill="url(#quake-crimson-1)" />
        <polygon points="10.7,17.1 10.9,17.0 11.3,18.0 11.1,18.1" fill="url(#quake-crimson-2)" />
        <polygon points="11.1,15.7 11.5,15.7 11.8,16.6 11.4,16.7" fill="url(#quake-crimson-0)" />
        <polygon points="10.4,16.1 10.6,15.9 10.9,17.0 10.7,17.1" fill="url(#quake-crimson-2)" />
        <polygon points="10.4,14.9 10.9,14.7 11.1,15.7 10.6,15.9" fill="url(#quake-crimson-1)" />
        <polygon points="10.9,14.7 11.3,14.8 11.5,15.7 11.1,15.7" fill="url(#quake-crimson-0)" />
        <polygon points="10.2,15.1 10.4,14.9 10.6,15.9 10.4,16.1" fill="url(#quake-crimson-2)" />
        <polygon points="10.2,13.9 10.8,13.8 10.9,14.7 10.4,14.9" fill="url(#quake-crimson-1)" />
        <polygon points="10.8,13.8 11.2,13.9 11.3,14.8 10.9,14.7" fill="url(#quake-crimson-0)" />
        <polygon points="10.1,14.1 10.2,13.9 10.4,14.9 10.2,15.1" fill="url(#quake-crimson-2)" />
        <polygon points="12.7,18.2 13.3,17.9 13.7,18.5 13.1,18.9" fill="url(#quake-crimson-0)" />
        <polygon points="12.4,17.5 13.0,17.2 13.3,17.9 12.7,18.2" fill="url(#quake-crimson-1)" />
        <polygon points="10.2,12.9 10.8,12.8 10.8,13.8 10.2,13.9" fill="url(#quake-crimson-1)" />
        <polygon points="12.1,16.7 12.7,16.4 13.0,17.2 12.4,17.5" fill="url(#quake-crimson-1)" />
        <polygon points="10.8,12.8 11.2,13.0 11.2,13.9 10.8,13.8" fill="url(#quake-crimson-0)" />
        <polygon points="13.3,17.9 13.7,17.6 14.0,18.2 13.7,18.5" fill="url(#quake-crimson-0)" />
        <polygon points="13.0,17.2 13.4,17.0 13.7,17.6 13.3,17.9" fill="url(#quake-crimson-0)" />
        <polygon points="11.9,15.9 12.5,15.7 12.7,16.4 12.1,16.7" fill="url(#quake-crimson-1)" />
        <polygon points="12.5,18.3 12.7,18.2 13.1,18.9 12.9,18.9" fill="url(#quake-crimson-2)" />
        <polygon points="10.0,13.2 10.2,12.9 10.2,13.9 10.1,14.1" fill="url(#quake-crimson-3)" />
        <polygon points="12.7,16.4 13.1,16.3 13.4,17.0 13.0,17.2" fill="url(#quake-crimson-0)" />
        <polygon points="12.2,17.6 12.4,17.5 12.7,18.2 12.5,18.3" fill="url(#quake-crimson-2)" />
        <polygon points="7.6,18.3 7.6,17.5 10.0,15.2 10.0,16.0" fill="url(#quake-rock-3)" />
        <polygon points="11.9,16.8 12.1,16.7 12.4,17.5 12.2,17.6" fill="url(#quake-crimson-2)" />
        <polygon points="12.5,15.7 13.0,15.7 13.1,16.3 12.7,16.4" fill="url(#quake-crimson-0)" />
        <polygon points="11.7,15.1 12.3,14.9 12.5,15.7 11.9,15.9" fill="url(#quake-crimson-1)" />
        <polygon points="11.7,16.1 11.9,15.9 12.1,16.7 11.9,16.8" fill="url(#quake-crimson-2)" />
        <polygon points="10.2,11.9 10.8,11.9 10.8,12.8 10.2,12.9" fill="url(#quake-crimson-2)" />
        <polygon points="10.8,11.9 11.2,12.2 11.2,13.0 10.8,12.8" fill="url(#quake-crimson-0)" />
        <polygon points="12.3,14.9 12.8,15.0 13.0,15.7 12.5,15.7" fill="url(#quake-crimson-0)" />
        <polygon points="11.6,14.3 12.2,14.2 12.3,14.9 11.7,15.1" fill="url(#quake-crimson-1)" />
        <polygon points="11.5,15.4 11.7,15.1 11.9,15.9 11.7,16.1" fill="url(#quake-crimson-2)" />
        <polygon points="10.1,12.3 10.2,11.9 10.2,12.9 10.0,13.2" fill="url(#quake-crimson-3)" />
        <polygon points="12.2,14.2 12.7,14.4 12.8,15.0 12.3,14.9" fill="url(#quake-crimson-0)" />
        <polygon points="11.4,14.6 11.6,14.3 11.7,15.1 11.5,15.4" fill="url(#quake-crimson-2)" />
        <polygon points="11.6,13.6 12.2,13.5 12.2,14.2 11.6,14.3" fill="url(#quake-crimson-1)" />
        <polygon points="10.4,11.1 10.9,11.1 10.8,11.9 10.2,11.9" fill="url(#quake-crimson-2)" />
        <polygon points="10.9,11.1 11.3,11.4 11.2,12.2 10.8,11.9" fill="url(#quake-crimson-0)" />
        <polygon points="12.2,13.5 12.7,13.7 12.7,14.4 12.2,14.2" fill="url(#quake-crimson-0)" />
        <polygon points="11.4,13.9 11.6,13.6 11.6,14.3 11.4,14.6" fill="url(#quake-crimson-3)" />
        <polygon points="10.2,11.4 10.4,11.1 10.2,11.9 10.1,12.3" fill="url(#quake-crimson-3)" />
        <polygon points="13.8,17.5 14.4,17.1 14.7,17.5 14.0,17.9" fill="url(#quake-crimson-0)" />
        <polygon points="13.5,16.9 14.2,16.6 14.4,17.1 13.8,17.5" fill="url(#quake-crimson-1)" />
        <polygon points="13.3,16.4 14.0,16.1 14.2,16.6 13.5,16.9" fill="url(#quake-crimson-1)" />
        <polygon points="11.6,12.9 12.2,12.8 12.2,13.5 11.6,13.6" fill="url(#quake-crimson-2)" />
        <polygon points="12.2,12.8 12.7,13.1 12.7,13.7 12.2,13.5" fill="url(#quake-crimson-0)" />
        <polygon points="13.2,15.9 13.9,15.6 14.0,16.1 13.3,16.4" fill="url(#quake-crimson-1)" />
        <polygon points="14.4,17.1 14.8,16.8 15.0,17.1 14.7,17.5" fill="url(#quake-crimson-0)" />
        <polygon points="14.2,16.6 14.6,16.4 14.8,16.8 14.4,17.1" fill="url(#quake-crimson-0)" />
        <polygon points="14.0,16.1 14.5,16.0 14.6,16.4 14.2,16.6" fill="url(#quake-crimson-0)" />
        <polygon points="13.0,15.3 13.8,15.1 13.9,15.6 13.2,15.9" fill="url(#quake-crimson-1)" />
        <polygon points="13.5,17.5 13.8,17.5 14.0,17.9 13.7,18.0" fill="url(#quake-crimson-2)" />
        <polygon points="13.3,17.1 13.5,16.9 13.8,17.5 13.5,17.5" fill="url(#quake-crimson-2)" />
        <polygon points="10.6,10.3 11.1,10.3 10.9,11.1 10.4,11.1" fill="url(#quake-crimson-2)" />
        <polygon points="11.1,10.3 11.5,10.7 11.3,11.4 10.9,11.1" fill="url(#quake-crimson-0)" />
        <polygon points="11.4,13.2 11.6,12.9 11.6,13.6 11.4,13.9" fill="url(#quake-crimson-3)" />
        <polygon points="13.9,15.6 14.4,15.6 14.5,16.0 14.0,16.1" fill="url(#quake-crimson-0)" />
        <polygon points="13.1,16.6 13.3,16.4 13.5,16.9 13.3,17.1" fill="url(#quake-crimson-2)" />
        <polygon points="12.9,16.1 13.2,15.9 13.3,16.4 13.1,16.6" fill="url(#quake-crimson-2)" />
        <polygon points="13.0,14.8 13.7,14.6 13.8,15.1 13.0,15.3" fill="url(#quake-crimson-1)" />
        <polygon points="11.7,12.2 12.3,12.2 12.2,12.8 11.6,12.9" fill="url(#quake-crimson-2)" />
        <polygon points="13.8,15.1 14.3,15.2 14.4,15.6 13.9,15.6" fill="url(#quake-crimson-0)" />
        <polygon points="12.3,12.2 12.8,12.6 12.7,13.1 12.2,12.8" fill="url(#quake-crimson-0)" />
        <polygon points="10.4,10.6 10.6,10.3 10.4,11.1 10.2,11.4" fill="url(#quake-crimson-3)" />
        <polygon points="12.8,15.6 13.0,15.3 13.2,15.9 12.9,16.1" fill="url(#quake-crimson-2)" />
        <polygon points="13.7,14.6 14.2,14.8 14.3,15.2 13.8,15.1" fill="url(#quake-crimson-0)" />
        <polygon points="23.6,17.1 23.6,16.3 24.4,18.9 24.4,19.7" fill="url(#quake-rock-0)" />
        <polygon points="12.9,14.3 13.7,14.2 13.7,14.6 13.0,14.8" fill="url(#quake-crimson-1)" />
        <polygon points="16.8,16.1 16.6,17.8 15.4,17.8 15.2,16.1" fill="url(#quake-crimson-1)" />
        <polygon points="11.5,12.6 11.7,12.2 11.6,12.9 11.4,13.2" fill="url(#quake-crimson-3)" />
        <polygon points="12.8,15.1 13.0,14.8 13.0,15.3 12.8,15.6" fill="url(#quake-crimson-2)" />
        <polygon points="16.6,17.8 16.0,19.2 15.4,17.8" fill="url(#quake-crimson-0)" />
        <polygon points="13.7,14.2 14.2,14.4 14.2,14.8 13.7,14.6" fill="url(#quake-crimson-0)" />
        <polygon points="11.9,11.6 12.5,11.6 12.3,12.2 11.7,12.2" fill="url(#quake-crimson-2)" />
        <polygon points="11.4,9.6 11.8,10.0 11.5,10.7 11.1,10.3" fill="url(#quake-crimson-0)" />
        <polygon points="12.5,11.6 13.0,12.0 12.8,12.6 12.3,12.2" fill="url(#quake-crimson-0)" />
        <polygon points="13.0,13.8 13.7,13.7 13.7,14.2 12.9,14.3" fill="url(#quake-crimson-2)" />
        <polygon points="10.9,9.5 11.4,9.6 11.1,10.3 10.6,10.3" fill="url(#quake-crimson-2)" />
        <polygon points="15.4,17.8 16.0,19.2 14.6,18.3" fill="url(#quake-crimson-0)" />
        <polygon points="17.4,18.3 16.0,19.2 16.6,17.8" fill="url(#quake-crimson-0)" />
        <polygon points="12.7,14.6 12.9,14.3 13.0,14.8 12.8,15.1" fill="url(#quake-crimson-3)" />
        <polygon points="13.7,13.7 14.2,14.1 14.2,14.4 13.7,14.2" fill="url(#quake-crimson-0)" />
        <polygon points="15.2,16.1 15.4,17.8 14.6,18.3 14.0,16.7" fill="url(#quake-crimson-2)" />
        <polygon points="18.0,16.7 17.4,18.3 16.6,17.8 16.8,16.1" fill="url(#quake-crimson-0)" />
        <polygon points="11.8,10.0 11.6,10.4 11.4,11.1 11.5,10.7" fill="url(#quake-crimson-0)" />
        <polygon points="11.7,12.0 11.9,11.6 11.7,12.2 11.5,12.6" fill="url(#quake-crimson-3)" />
        <polygon points="13.0,13.3 13.8,13.3 13.7,13.7 13.0,13.8" fill="url(#quake-crimson-2)" />
        <polygon points="12.8,14.2 13.0,13.8 12.9,14.3 12.7,14.6" fill="url(#quake-crimson-3)" />
        <polygon points="13.8,13.3 14.3,13.7 14.2,14.1 13.7,13.7" fill="url(#quake-crimson-0)" />
        <polygon points="22.0,22.0 17.3,23.2 12.1,22.8 8.4,20.9 7.6,18.3 10.0,16.0 14.7,14.8 19.9,15.2 23.6,17.1 24.4,19.7" fill="url(#quake-rock-0)" />
        <polygon points="12.7,11.1 13.1,11.6 13.0,12.0 12.5,11.6" fill="url(#quake-crimson-0)" />
        <polygon points="12.1,11.0 12.7,11.1 12.5,11.6 11.9,11.6" fill="url(#quake-crimson-2)" />
        <polygon points="17.4,18.8 16.0,19.2 17.4,18.3" fill="url(#quake-crimson-0)" />
        <polygon points="14.6,18.3 16.0,19.2 14.6,18.8" fill="url(#quake-crimson-1)" />
        <polygon points="16.6,14.9 16.8,16.1 15.2,16.1 15.4,14.9" fill="url(#quake-crimson-2)" />
        <polygon points="13.2,12.9 13.9,12.9 13.8,13.3 13.0,13.3" fill="url(#quake-crimson-2)" />
        <polygon points="12.8,13.8 13.0,13.3 13.0,13.8 12.8,14.2" fill="url(#quake-crimson-3)" />
        <polygon points="13.9,12.9 14.4,13.4 14.3,13.7 13.8,13.3" fill="url(#quake-crimson-0)" />
        <polygon points="11.8,9.0 12.1,9.5 11.8,10.0 11.4,9.6" fill="url(#quake-crimson-0)" />
        <polygon points="11.3,8.9 11.8,9.0 11.4,9.6 10.9,9.5" fill="url(#quake-crimson-2)" />
        <polygon points="13.1,11.6 12.9,12.1 12.8,12.5 13.0,12.0" fill="url(#quake-crimson-0)" />
        <polygon points="12.1,9.5 12.0,9.9 11.6,10.4 11.8,10.0" fill="url(#quake-crimson-0)" />
        <polygon points="14.0,12.6 14.5,13.1 14.4,13.4 13.9,12.9" fill="url(#quake-crimson-0)" />
        <polygon points="13.0,10.6 13.4,11.2 13.1,11.6 12.7,11.1" fill="url(#quake-crimson-0)" />
        <polygon points="12.9,13.4 13.2,12.9 13.0,13.3 12.8,13.8" fill="url(#quake-crimson-3)" />
        <polygon points="13.3,12.5 14.0,12.6 13.9,12.9 13.2,12.9" fill="url(#quake-crimson-2)" />
        <polygon points="15.4,14.9 15.2,16.1 14.0,16.7 14.6,15.3" fill="url(#quake-crimson-3)" />
        <polygon points="17.4,15.3 18.0,16.7 16.8,16.1 16.6,14.9" fill="url(#quake-crimson-1)" />
        <polygon points="12.4,10.5 13.0,10.6 12.7,11.1 12.1,11.0" fill="url(#quake-crimson-2)" />
        <polygon points="16.6,19.3 16.0,19.2 17.4,18.8" fill="url(#quake-crimson-0)" />
        <polygon points="14.6,18.8 16.0,19.2 15.4,19.3" fill="url(#quake-crimson-1)" />
        <polygon points="18.0,17.5 17.4,18.8 17.4,18.3 18.0,16.7" fill="url(#quake-crimson-0)" />
        <polygon points="14.0,16.7 14.6,18.3 14.6,18.8 14.0,17.5" fill="url(#quake-crimson-2)" />
        <polygon points="13.4,11.2 13.2,11.7 12.9,12.1 13.1,11.6" fill="url(#quake-crimson-0)" />
        <polygon points="14.2,12.3 14.6,12.9 14.5,13.1 14.0,12.6" fill="url(#quake-crimson-0)" />
        <polygon points="14.5,13.1 14.3,13.7 14.2,13.9 14.4,13.4" fill="url(#quake-crimson-0)" />
        <polygon points="15.4,19.3 16.0,19.2 16.6,19.3" fill="url(#quake-crimson-0)" />
        <polygon points="13.5,12.2 14.2,12.3 14.0,12.6 13.3,12.5" fill="url(#quake-crimson-2)" />
        <polygon points="12.3,8.5 12.6,9.0 12.1,9.5 11.8,9.0" fill="url(#quake-crimson-0)" />
        <polygon points="11.7,8.4 12.3,8.5 11.8,9.0 11.3,8.9" fill="url(#quake-crimson-2)" />
        <polygon points="13.3,10.2 13.7,10.9 13.4,11.2 13.0,10.6" fill="url(#quake-crimson-0)" />
        <polygon points="14.6,12.9 14.4,13.5 14.3,13.7 14.5,13.1" fill="url(#quake-crimson-0)" />
        <polygon points="12.6,9.0 12.3,9.5 12.0,9.9 12.1,9.5" fill="url(#quake-crimson-0)" />
        <polygon points="14.4,12.0 14.8,12.7 14.6,12.9 14.2,12.3" fill="url(#quake-crimson-0)" />
        <polygon points="12.7,10.1 13.3,10.2 13.0,10.6 12.4,10.5" fill="url(#quake-crimson-2)" />
        <polygon points="13.7,10.9 13.4,11.4 13.2,11.7 13.4,11.2" fill="url(#quake-crimson-0)" />
        <polygon points="13.8,11.9 14.4,12.0 14.2,12.3 13.5,12.2" fill="url(#quake-crimson-2)" />
        <polygon points="18.3,19.3 17.9,18.6 18.1,18.4 18.5,19.1" fill="url(#quake-crimson-0)" />
        <polygon points="19.1,21.2 18.8,20.6 19.1,20.3 19.5,20.9" fill="url(#quake-crimson-0)" />
        <polygon points="20.0,23.2 19.7,22.6 20.2,22.2 20.5,22.8" fill="url(#quake-crimson-0)" />
        <polygon points="14.8,12.7 14.5,13.3 14.4,13.5 14.6,12.9" fill="url(#quake-crimson-0)" />
        <polygon points="19.7,23.6 20.0,23.2 20.5,22.8 20.3,23.2" fill="url(#quake-crimson-0)" />
        <polygon points="14.7,11.8 15.0,12.5 14.8,12.7 14.4,12.0" fill="url(#quake-crimson-0)" />
        <polygon points="19.7,22.6 19.2,22.5 19.7,22.1 20.2,22.2" fill="url(#quake-crimson-2)" />
        <polygon points="18.9,21.8 19.1,21.2 19.5,20.9 19.3,21.5" fill="url(#quake-crimson-0)" />
        <polygon points="18.0,19.9 18.3,19.3 18.5,19.1 18.2,19.7" fill="url(#quake-crimson-0)" />
        <polygon points="18.8,20.6 18.2,20.5 18.6,20.2 19.1,20.3" fill="url(#quake-crimson-2)" />
        <polygon points="17.9,18.6 17.3,18.5 17.5,18.3 18.1,18.4" fill="url(#quake-crimson-2)" />
        <polygon points="13.7,10.0 14.0,10.6 13.7,10.9 13.3,10.2" fill="url(#quake-crimson-0)" />
        <polygon points="12.8,8.1 13.0,8.6 12.6,9.0 12.3,8.5" fill="url(#quake-crimson-0)" />
        <polygon points="15.0,12.5 14.7,13.1 14.5,13.3 14.8,12.7" fill="url(#quake-crimson-0)" />
        <polygon points="14.0,11.7 14.7,11.8 14.4,12.0 13.8,11.9" fill="url(#quake-crimson-2)" />
        <polygon points="18.5,19.1 18.1,18.4 18.3,18.2 18.7,18.9" fill="url(#quake-crimson-0)" />
        <polygon points="14.0,10.6 13.8,11.1 13.4,11.4 13.7,10.9" fill="url(#quake-crimson-0)" />
        <polygon points="13.1,9.8 13.7,10.0 13.3,10.2 12.7,10.1" fill="url(#quake-crimson-2)" />
        <polygon points="13.0,8.6 12.8,9.1 12.3,9.5 12.6,9.0" fill="url(#quake-crimson-0)" />
        <polygon points="12.3,8.0 12.8,8.1 12.3,8.5 11.7,8.4" fill="url(#quake-crimson-2)" />
        <polygon points="18.1,18.4 17.5,18.3 17.6,18.1 18.3,18.2" fill="url(#quake-crimson-2)" />
        <polygon points="19.5,20.9 19.1,20.3 19.4,20.0 19.8,20.6" fill="url(#quake-crimson-0)" />
        <polygon points="18.2,19.7 18.5,19.1 18.7,18.9 18.5,19.4" fill="url(#quake-crimson-0)" />
        <polygon points="19.1,20.3 18.6,20.2 18.8,19.9 19.4,20.0" fill="url(#quake-crimson-2)" />
        <polygon points="18.7,18.9 18.3,18.2 18.4,18.0 18.9,18.6" fill="url(#quake-crimson-0)" />
        <polygon points="20.5,22.8 20.2,22.2 20.6,21.8 20.9,22.3" fill="url(#quake-crimson-0)" />
        <polygon points="19.3,21.5 19.5,20.9 19.8,20.6 19.6,21.1" fill="url(#quake-crimson-0)" />
        <polygon points="18.3,18.2 17.6,18.1 17.7,17.9 18.4,18.0" fill="url(#quake-crimson-2)" />
        <polygon points="20.2,22.2 19.7,22.1 20.0,21.7 20.6,21.8" fill="url(#quake-crimson-2)" />
        <polygon points="20.3,23.2 20.5,22.8 20.9,22.3 20.7,22.7" fill="url(#quake-crimson-0)" />
        <polygon points="18.5,19.4 18.7,18.9 18.9,18.6 18.7,19.1" fill="url(#quake-crimson-0)" />
        <polygon points="18.9,18.6 18.4,18.0 18.6,17.7 19.1,18.2" fill="url(#quake-crimson-0)" />
        <polygon points="18.4,18.0 17.7,17.9 17.8,17.7 18.6,17.7" fill="url(#quake-crimson-2)" />
        <polygon points="19.8,20.6 19.4,20.0 19.7,19.6 20.1,20.1" fill="url(#quake-crimson-0)" />
        <polygon points="19.4,20.0 18.8,19.9 19.1,19.5 19.7,19.6" fill="url(#quake-crimson-2)" />
        <polygon points="18.6,17.7 17.8,17.7 17.9,17.4 18.6,17.4" fill="url(#quake-crimson-2)" />
        <polygon points="19.6,21.1 19.8,20.6 20.1,20.1 19.9,20.6" fill="url(#quake-crimson-0)" />
        <polygon points="19.1,18.2 18.6,17.7 18.6,17.4 19.2,17.8" fill="url(#quake-crimson-0)" />
        <polygon points="18.7,19.1 18.9,18.6 19.1,18.2 18.8,18.7" fill="url(#quake-crimson-0)" />
        <polygon points="20.9,22.3 20.6,21.8 20.9,21.2 21.3,21.7" fill="url(#quake-crimson-0)" />
        <polygon points="20.6,21.8 20.0,21.7 20.4,21.2 20.9,21.2" fill="url(#quake-crimson-2)" />
        <polygon points="18.6,17.4 17.9,17.4 18.0,17.1 18.7,17.1" fill="url(#quake-crimson-2)" />
        <polygon points="20.1,20.1 19.7,19.6 19.9,19.1 20.3,19.6" fill="url(#quake-crimson-0)" />
        <polygon points="19.7,19.6 19.1,19.5 19.2,19.1 19.9,19.1" fill="url(#quake-crimson-2)" />
        <polygon points="19.2,17.8 18.6,17.4 18.7,17.1 19.2,17.4" fill="url(#quake-crimson-0)" />
        <polygon points="17.8,17.7 17.6,18.2 17.7,17.9 17.9,17.4" fill="url(#quake-crimson-3)" />
        <polygon points="20.7,22.7 20.9,22.3 21.3,21.7 21.1,22.1" fill="url(#quake-crimson-0)" />
        <polygon points="18.7,17.1 18.0,17.1 18.0,16.8 18.7,16.7" fill="url(#quake-crimson-2)" />
        <polygon points="19.9,20.6 20.1,20.1 20.3,19.6 20.1,20.0" fill="url(#quake-crimson-0)" />
        <polygon points="19.2,17.4 18.7,17.1 18.7,16.7 19.3,17.0" fill="url(#quake-crimson-0)" />
        <polygon points="17.9,17.4 17.7,17.9 17.8,17.5 18.0,17.1" fill="url(#quake-crimson-3)" />
        <polygon points="18.7,16.7 18.0,16.8 18.0,16.5 18.7,16.3" fill="url(#quake-crimson-1)" />
        <polygon points="19.9,19.1 19.2,19.1 19.4,18.6 20.0,18.6" fill="url(#quake-crimson-2)" />
        <polygon points="20.3,19.6 19.9,19.1 20.0,18.6 20.5,19.0" fill="url(#quake-crimson-0)" />
        <polygon points="19.3,17.0 18.7,16.7 18.7,16.3 19.2,16.5" fill="url(#quake-crimson-0)" />
        <polygon points="18.0,17.1 17.8,17.5 17.8,17.2 18.0,16.8" fill="url(#quake-crimson-3)" />
        <polygon points="18.7,16.3 18.0,16.5 17.9,16.1 18.6,15.9" fill="url(#quake-crimson-1)" />
        <polygon points="21.3,21.7 20.9,21.2 21.2,20.6 21.6,21.0" fill="url(#quake-crimson-0)" />
        <polygon points="20.9,21.2 20.4,21.2 20.6,20.5 21.2,20.6" fill="url(#quake-crimson-2)" />
        <polygon points="18.6,15.9 17.9,16.1 17.8,15.8 18.6,15.5" fill="url(#quake-crimson-1)" />
        <polygon points="19.2,16.5 18.7,16.3 18.6,15.9 19.2,16.0" fill="url(#quake-crimson-0)" />
        <polygon points="18.0,16.8 17.8,17.2 17.8,16.8 18.0,16.5" fill="url(#quake-crimson-3)" />
        <polygon points="19.2,19.1 19.0,19.6 19.2,19.0 19.4,18.6" fill="url(#quake-crimson-3)" />
        <polygon points="18.6,15.5 17.8,15.8 17.7,15.4 18.4,15.1" fill="url(#quake-crimson-1)" />
        <polygon points="21.1,22.1 21.3,21.7 21.6,21.0 21.4,21.3" fill="url(#quake-crimson-0)" />
        <polygon points="20.0,18.6 19.4,18.6 19.5,18.1 20.1,18.1" fill="url(#quake-crimson-2)" />
        <polygon points="18.4,15.1 17.7,15.4 17.6,15.1 18.3,14.7" fill="url(#quake-crimson-1)" />
        <polygon points="19.2,16.0 18.6,15.9 18.6,15.5 19.1,15.5" fill="url(#quake-crimson-0)" />
        <polygon points="18.0,16.5 17.8,16.8 17.7,16.4 17.9,16.1" fill="url(#quake-crimson-2)" />
        <polygon points="20.5,19.0 20.0,18.6 20.1,18.1 20.6,18.4" fill="url(#quake-crimson-0)" />
        <polygon points="18.3,14.7 17.6,15.1 17.5,14.7 18.1,14.4" fill="url(#quake-crimson-1)" />
        <polygon points="18.1,14.4 17.5,14.7 17.3,14.4 17.9,14.0" fill="url(#quake-crimson-0)" />
        <polygon points="19.1,15.5 18.6,15.5 18.4,15.1 18.9,15.0" fill="url(#quake-crimson-0)" />
        <polygon points="17.9,16.1 17.7,16.4 17.6,16.0 17.8,15.8" fill="url(#quake-crimson-2)" />
        <polygon points="18.9,15.0 18.4,15.1 18.3,14.7 18.7,14.5" fill="url(#quake-crimson-0)" />
        <polygon points="17.8,15.8 17.6,16.0 17.5,15.6 17.7,15.4" fill="url(#quake-crimson-2)" />
        <polygon points="19.4,18.6 19.2,19.0 19.3,18.5 19.5,18.1" fill="url(#quake-crimson-3)" />
        <polygon points="18.7,14.5 18.3,14.7 18.1,14.4 18.5,14.1" fill="url(#quake-crimson-0)" />
        <polygon points="18.5,14.1 18.1,14.4 17.9,14.0 18.3,13.6" fill="url(#quake-crimson-0)" />
        <polygon points="21.2,20.6 20.6,20.5 20.8,19.9 21.4,19.8" fill="url(#quake-crimson-2)" />
        <polygon points="21.6,21.0 21.2,20.6 21.4,19.8 21.8,20.2" fill="url(#quake-crimson-0)" />
        <polygon points="17.7,15.4 17.5,15.6 17.4,15.2 17.6,15.1" fill="url(#quake-crimson-2)" />
        <polygon points="20.1,18.1 19.5,18.1 19.5,17.5 20.1,17.5" fill="url(#quake-crimson-2)" />
        <polygon points="17.6,15.1 17.4,15.2 17.2,14.8 17.5,14.7" fill="url(#quake-crimson-2)" />
        <polygon points="17.5,14.7 17.2,14.8 17.0,14.5 17.3,14.4" fill="url(#quake-crimson-2)" />
        <polygon points="20.6,18.4 20.1,18.1 20.1,17.5 20.6,17.7" fill="url(#quake-crimson-0)" />
        <polygon points="20.6,20.5 20.5,20.9 20.7,20.2 20.8,19.9" fill="url(#quake-crimson-3)" />
        <polygon points="19.5,18.1 19.3,18.5 19.3,17.9 19.5,17.5" fill="url(#quake-crimson-3)" />
        <polygon points="20.1,17.5 19.5,17.5 19.5,16.9 20.1,16.8" fill="url(#quake-crimson-1)" />
        <polygon points="20.6,17.7 20.1,17.5 20.1,16.8 20.6,17.0" fill="url(#quake-crimson-0)" />
        <polygon points="21.4,19.8 20.8,19.9 20.9,19.1 21.5,19.1" fill="url(#quake-crimson-2)" />
        <polygon points="21.8,20.2 21.4,19.8 21.5,19.1 21.9,19.3" fill="url(#quake-crimson-0)" />
        <polygon points="20.1,16.8 19.5,16.9 19.4,16.3 20.0,16.2" fill="url(#quake-crimson-1)" />
        <polygon points="19.5,17.5 19.3,17.9 19.3,17.2 19.5,16.9" fill="url(#quake-crimson-3)" />
        <polygon points="20.6,17.0 20.1,16.8 20.0,16.2 20.5,16.2" fill="url(#quake-crimson-0)" />
        <polygon points="20.8,19.9 20.7,20.2 20.8,19.4 20.9,19.1" fill="url(#quake-crimson-3)" />
        <polygon points="20.0,16.2 19.4,16.3 19.2,15.7 19.9,15.5" fill="url(#quake-crimson-1)" />
        <polygon points="19.5,16.9 19.3,17.2 19.2,16.6 19.4,16.3" fill="url(#quake-crimson-2)" />
        <polygon points="20.5,16.2 20.0,16.2 19.9,15.5 20.3,15.5" fill="url(#quake-crimson-0)" />
        <polygon points="19.9,15.5 19.2,15.7 19.1,15.1 19.7,14.9" fill="url(#quake-crimson-1)" />
        <polygon points="21.5,19.1 20.9,19.1 21.0,18.3 21.6,18.2" fill="url(#quake-crimson-2)" />
        <polygon points="21.9,19.3 21.5,19.1 21.6,18.2 22.0,18.4" fill="url(#quake-crimson-0)" />
        <polygon points="19.4,16.3 19.2,16.6 19.0,15.9 19.2,15.7" fill="url(#quake-crimson-2)" />
        <polygon points="19.7,14.9 19.1,15.1 18.8,14.5 19.4,14.2" fill="url(#quake-crimson-1)" />
        <polygon points="20.3,15.5 19.9,15.5 19.7,14.9 20.1,14.8" fill="url(#quake-crimson-0)" />
        <polygon points="19.4,14.2 18.8,14.5 18.6,13.9 19.1,13.6" fill="url(#quake-crimson-1)" />
        <polygon points="19.1,13.6 18.6,13.9 18.2,13.4 18.8,13.0" fill="url(#quake-crimson-0)" />
        <polygon points="20.9,19.1 20.8,19.4 20.8,18.6 21.0,18.3" fill="url(#quake-crimson-3)" />
        <polygon points="19.2,15.7 19.0,15.9 18.9,15.3 19.1,15.1" fill="url(#quake-crimson-2)" />
        <polygon points="20.1,14.8 19.7,14.9 19.4,14.2 19.8,14.0" fill="url(#quake-crimson-0)" />
        <polygon points="19.8,14.0 19.4,14.2 19.1,13.6 19.5,13.3" fill="url(#quake-crimson-0)" />
        <polygon points="19.1,15.1 18.9,15.3 18.6,14.6 18.8,14.5" fill="url(#quake-crimson-2)" />
        <polygon points="19.5,13.3 19.1,13.6 18.8,13.0 19.1,12.7" fill="url(#quake-crimson-0)" />
        <polygon points="21.6,18.2 21.0,18.3 20.9,17.4 21.5,17.3" fill="url(#quake-crimson-1)" />
        <polygon points="18.8,14.5 18.6,14.6 18.3,14.0 18.6,13.9" fill="url(#quake-crimson-2)" />
        <polygon points="18.6,13.9 18.3,14.0 18.0,13.4 18.2,13.4" fill="url(#quake-crimson-2)" />
        <polygon points="22.0,18.4 21.6,18.2 21.5,17.3 21.9,17.5" fill="url(#quake-crimson-0)" />
        <polygon points="21.0,18.3 20.8,18.6 20.8,17.7 20.9,17.4" fill="url(#quake-crimson-3)" />
        <polygon points="21.5,17.3 20.9,17.4 20.8,16.6 21.4,16.4" fill="url(#quake-crimson-1)" />
        <polygon points="21.9,17.5 21.5,17.3 21.4,16.4 21.8,16.5" fill="url(#quake-crimson-0)" />
        <polygon points="20.9,17.4 20.8,17.7 20.7,16.8 20.8,16.6" fill="url(#quake-crimson-2)" />
        <polygon points="21.4,16.4 20.8,16.6 20.6,15.7 21.2,15.5" fill="url(#quake-crimson-1)" />
        <polygon points="21.8,16.5 21.4,16.4 21.2,15.5 21.6,15.5" fill="url(#quake-crimson-0)" />
        <polygon points="21.2,15.5 20.6,15.7 20.4,14.8 20.9,14.6" fill="url(#quake-crimson-1)" />
        <polygon points="20.8,16.6 20.7,16.8 20.5,15.9 20.6,15.7" fill="url(#quake-crimson-2)" />
        <polygon points="21.6,15.5 21.2,15.5 20.9,14.6 21.3,14.5" fill="url(#quake-crimson-0)" />
        <polygon points="20.9,14.6 20.4,14.8 20.0,13.9 20.6,13.7" fill="url(#quake-crimson-1)" />
        <polygon points="20.6,15.7 20.5,15.9 20.2,15.0 20.4,14.8" fill="url(#quake-crimson-2)" />
        <polygon points="20.6,13.7 20.0,13.9 19.7,13.1 20.2,12.8" fill="url(#quake-crimson-1)" />
        <polygon points="20.2,12.8 19.7,13.1 19.2,12.3 19.7,12.0" fill="url(#quake-crimson-0)" />
        <polygon points="21.3,14.5 20.9,14.6 20.6,13.7 20.9,13.5" fill="url(#quake-crimson-0)" />
        <polygon points="20.4,14.8 20.2,15.0 19.9,14.0 20.0,13.9" fill="url(#quake-crimson-2)" />
        <polygon points="20.9,13.5 20.6,13.7 20.2,12.8 20.5,12.6" fill="url(#quake-crimson-0)" />
        <polygon points="20.5,12.6 20.2,12.8 19.7,12.0 20.0,11.7" fill="url(#quake-crimson-0)" />
        <polygon points="20.0,13.9 19.9,14.0 19.4,13.2 19.7,13.1" fill="url(#quake-crimson-2)" />
        <polygon points="19.7,13.1 19.4,13.2 19.0,12.3 19.2,12.3" fill="url(#quake-crimson-2)" />
      </g>
    </svg>
  );
}

/** Genesis: an island risen out of the tile, a barbed arrow planted in its mound. */
export function GenesisIcon(): JSX.Element {
  return (
    <svg class="relics-gem" viewBox="0 0 32 32" aria-hidden="true">
      <defs>
        <linearGradient id="genesis-crimson-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#ffc2b8" />
          <stop offset="1" stop-color="#db9890" />
        </linearGradient>
        <linearGradient id="genesis-crimson-1" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#db9890" />
          <stop offset="1" stop-color="#b86d68" />
        </linearGradient>
        <linearGradient id="genesis-crimson-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#b86d68" />
          <stop offset="1" stop-color="#944240" />
        </linearGradient>
        <linearGradient id="genesis-crimson-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#944240" />
          <stop offset="1" stop-color="#701818" />
        </linearGradient>
        <linearGradient id="genesis-grass-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#c8f0a8" />
          <stop offset="1" stop-color="#a6d48e" />
        </linearGradient>
        <linearGradient id="genesis-grass-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#84b873" />
          <stop offset="1" stop-color="#619b58" />
        </linearGradient>
        <linearGradient id="genesis-grass-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#619b58" />
          <stop offset="1" stop-color="#3f7f3e" />
        </linearGradient>
        <linearGradient id="genesis-stone-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#e6dcc8" />
          <stop offset="1" stop-color="#c7bca7" />
        </linearGradient>
        <linearGradient id="genesis-stone-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#a89b86" />
          <stop offset="1" stop-color="#897a66" />
        </linearGradient>
        <linearGradient id="genesis-stone-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#897a66" />
          <stop offset="1" stop-color="#6a5a45" />
        </linearGradient>
      </defs>
      <g transform="translate(0 -1.6)">
        <Tile prefix="genesis" glow="#ff5c5c" />
        <ellipse cx="16" cy="19.2" rx="9" ry="3.8" fill="#2e5a2e" opacity="0.5" />
        <polygon points="14.7,14.8 14.9,14.4 19.1,14.7 19.9,15.2" fill="url(#genesis-stone-2)" />
        <polygon points="10.0,16.0 11.2,15.3 14.9,14.4 14.7,14.8" fill="url(#genesis-stone-3)" />
        <polygon points="14.9,14.4 15.3,13.0 18.1,13.2 19.1,14.7" fill="url(#genesis-grass-2)" />
        <polygon points="11.2,15.3 12.7,13.7 15.3,13.0 14.9,14.4" fill="url(#genesis-grass-3)" />
        <polygon points="19.1,14.7 18.1,13.2 20.2,14.3 22.0,16.2" fill="url(#genesis-grass-2)" />
        <polygon points="22.0,22.0 17.3,23.2 12.1,22.8 8.4,20.9 7.6,18.3 10.0,16.0 14.7,14.8 19.9,15.2 23.6,17.1 24.4,19.7" fill="url(#genesis-stone-0)" />
        <polygon points="20.8,20.1 17.1,21.1 12.9,20.7 10.0,19.3 9.3,17.2 11.2,15.3 14.9,14.4 19.1,14.7 22.0,16.2 22.7,18.3" fill="url(#genesis-grass-0)" />
        <polygon points="16.3,15.0 16.3,12.6 16.7,11.9 16.7,14.3" fill="url(#genesis-crimson-3)" />
        <polygon points="16.5,15.6 16.1,15.7 15.7,15.7 15.3,15.5 15.2,15.3 15.5,15.1 15.9,14.9 16.3,15.0 16.7,15.1 16.8,15.4" fill="url(#genesis-crimson-0)" />
        <polygon points="16.1,14.9 16.1,12.5 16.3,12.6 16.3,15.0" fill="url(#genesis-crimson-1)" />
        <polygon points="16.1,12.5 16.4,11.9 16.7,11.9 16.3,12.6" fill="url(#genesis-crimson-0)" />
        <polygon points="15.3,15.5 14.0,15.7 14.0,13.3 15.3,13.1" fill="url(#genesis-crimson-2)" />
        <polygon points="14.0,15.7 13.9,15.5 13.9,13.1 14.0,13.3" fill="url(#genesis-crimson-0)" />
        <polygon points="15.9,14.9 15.9,7.7 16.3,7.8 16.3,15.0" fill="url(#genesis-crimson-1)" />
        <polygon points="16.4,15.6 16.4,13.2 17.4,13.7 17.4,16.1" fill="url(#genesis-crimson-0)" />
        <polygon points="15.5,15.1 15.5,7.9 15.9,7.7 15.9,14.9" fill="url(#genesis-crimson-2)" />
        <polygon points="15.3,13.1 14.0,13.3 13.9,13.1 15.2,13.0" fill="url(#genesis-crimson-0)" />
        <polygon points="16.3,15.0 16.3,7.8 16.7,7.9 16.7,15.1" fill="url(#genesis-crimson-0)" />
        <polygon points="15.2,15.3 15.2,8.1 15.5,7.9 15.5,15.1" fill="url(#genesis-crimson-3)" />
        <polygon points="17.6,16.0 17.4,16.1 17.4,13.7 17.6,13.6" fill="url(#genesis-crimson-2)" />
        <polygon points="16.7,15.1 16.7,7.9 16.8,8.2 16.8,15.4" fill="url(#genesis-crimson-0)" />
        <polygon points="16.6,13.1 17.6,13.6 17.4,13.7 16.4,13.2" fill="url(#genesis-crimson-0)" />
        <polygon points="16.8,9.3 12.5,10.4 15.8,7.2" fill="url(#genesis-crimson-0)" />
        <polygon points="15.8,7.7 19.5,10.4 15.4,9.3" fill="url(#genesis-crimson-1)" />
        <polygon points="16.8,7.3 19.5,10.4 15.8,7.7" fill="url(#genesis-crimson-1)" />
        <polygon points="15.7,7.2 16.0,4.6 16.8,7.3" fill="url(#genesis-crimson-2)" />
        <polygon points="14.7,7.5 16.0,4.6 15.7,7.2" fill="url(#genesis-crimson-2)" />
        <polygon points="17.3,8.8 16.3,9.0 15.2,9.0 14.3,8.5 14.2,8.0 14.7,7.5 15.7,7.2 16.8,7.3 17.7,7.7 17.8,8.3" fill="url(#genesis-crimson-0)" />
        <polygon points="16.8,7.3 16.0,4.6 17.7,7.7" fill="url(#genesis-crimson-1)" />
        <polygon points="14.2,8.0 16.0,4.6 14.7,7.5" fill="url(#genesis-crimson-3)" />
      </g>
    </svg>
  );
}

/** Azure Heart: a cut heart hovering over the tile. */
export function AzureHeartIcon(): JSX.Element {
  return (
    <svg class="relics-gem" viewBox="0 0 32 32" aria-hidden="true">
      <defs>
        <linearGradient id="azure-heart-azure-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#d8f4ff" />
          <stop offset="1" stop-color="#a7cee1" />
        </linearGradient>
        <linearGradient id="azure-heart-azure-1" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#a7cee1" />
          <stop offset="1" stop-color="#76a8c4" />
        </linearGradient>
        <linearGradient id="azure-heart-azure-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#76a8c4" />
          <stop offset="1" stop-color="#4682a6" />
        </linearGradient>
        <linearGradient id="azure-heart-azure-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#4682a6" />
          <stop offset="1" stop-color="#155c88" />
        </linearGradient>
      </defs>
      <g transform="translate(0 -1.6)">
        <Tile prefix="azure-heart" glow="#4fc3f7" />
        <ellipse cx="16" cy="19.2" rx="6" ry="2.6" fill="#2e5a2e" opacity="0.5" />
        <polygon points="12.1,15.4 12.1,14.0 16.0,17.5 16.0,18.9" fill="url(#azure-heart-azure-1)" />
        <polygon points="16.0,18.9 16.0,17.5 19.9,14.0 19.9,15.4" fill="url(#azure-heart-azure-0)" />
        <polygon points="19.9,15.4 19.9,14.0 22.0,10.6 22.0,12.0" fill="url(#azure-heart-azure-0)" />
        <polygon points="10.0,12.0 10.0,10.6 12.1,14.0 12.1,15.4" fill="url(#azure-heart-azure-2)" />
        <polygon points="16.0,17.5 12.1,14.0 10.0,10.6 9.4,7.6 10.3,5.5 12.4,4.7 13.7,4.9 14.7,5.3 15.4,6.1 15.8,6.9 16.0,7.9 16.2,6.9 16.6,6.1 17.3,5.3 18.3,4.9 19.6,4.7 21.7,5.5 22.6,7.6 22.0,10.6 19.9,14.0" fill="url(#azure-heart-azure-1)" />
        <polygon points="22.0,12.0 22.0,10.6 22.6,7.6 22.6,9.0" fill="url(#azure-heart-azure-0)" />
        <polygon points="9.4,9.0 9.4,7.6 10.0,10.6 10.0,12.0" fill="url(#azure-heart-azure-3)" />
      </g>
    </svg>
  );
}

/** Spring of Aether: a pool in a rock, a fountain plume spraying up out of it. */
export function SpringOfAetherIcon(): JSX.Element {
  return (
    <svg class="relics-gem" viewBox="0 0 32 32" aria-hidden="true">
      <defs>
        <linearGradient id="spring-foam-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#ffffff" />
          <stop offset="1" stop-color="#e3f6fc" />
        </linearGradient>
        <linearGradient id="spring-foam-1" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#e3f6fc" />
          <stop offset="1" stop-color="#c7eefa" />
        </linearGradient>
        <linearGradient id="spring-foam-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#c7eefa" />
          <stop offset="1" stop-color="#abe5f8" />
        </linearGradient>
        <linearGradient id="spring-foam-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#abe5f8" />
          <stop offset="1" stop-color="#8fdcf5" />
        </linearGradient>
        <linearGradient id="spring-stone-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#e6dcc8" />
          <stop offset="1" stop-color="#c7bca7" />
        </linearGradient>
        <linearGradient id="spring-stone-1" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#c7bca7" />
          <stop offset="1" stop-color="#a89b86" />
        </linearGradient>
        <linearGradient id="spring-stone-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#a89b86" />
          <stop offset="1" stop-color="#897a66" />
        </linearGradient>
        <linearGradient id="spring-stone-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#897a66" />
          <stop offset="1" stop-color="#6a5a45" />
        </linearGradient>
        <linearGradient id="spring-water-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#e2f7ff" />
          <stop offset="1" stop-color="#b0d5e7" />
        </linearGradient>
        <linearGradient id="spring-water-1" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#b0d5e7" />
          <stop offset="1" stop-color="#7eb3d0" />
        </linearGradient>
        <linearGradient id="spring-water-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#7eb3d0" />
          <stop offset="1" stop-color="#4c91b8" />
        </linearGradient>
        <linearGradient id="spring-water-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#4c91b8" />
          <stop offset="1" stop-color="#1a6fa0" />
        </linearGradient>
      </defs>
      <g transform="translate(0 -3.1)">
        <Tile prefix="spring" glow="#4fc3f7" />
        <ellipse cx="16" cy="19.2" rx="8.5" ry="3.6" fill="#2e5a2e" opacity="0.5" />
        <polygon points="10.3,16.1 11.5,13.9 16.7,13.0 16.9,15.0" fill="url(#spring-stone-2)" />
        <polygon points="16.9,15.0 16.7,13.0 21.4,14.5 22.8,16.9" fill="url(#spring-stone-1)" />
        <polygon points="13.6,14.5 13.4,13.6 16.9,13.4 16.8,14.3" fill="url(#spring-stone-1)" />
        <polygon points="14.0,14.9 13.6,14.5 16.8,14.3 16.7,14.7" fill="url(#spring-stone-0)" />
        <polygon points="16.8,14.3 16.9,13.4 20.1,14.2 19.8,15.0" fill="url(#spring-stone-0)" />
        <polygon points="13.4,13.6 13.6,13.1 16.8,12.9 16.9,13.4" fill="url(#spring-stone-2)" />
        <polygon points="16.7,14.7 16.8,14.3 19.8,15.0 19.2,15.3" fill="url(#spring-stone-0)" />
        <polygon points="16.9,13.4 16.8,12.9 19.8,13.6 20.1,14.2" fill="url(#spring-stone-1)" />
        <polygon points="15.3,14.3 15.3,13.8 18.0,14.0 18.0,14.5" fill="url(#spring-water-1)" />
        <polygon points="11.2,15.7 10.9,14.9 13.4,13.6 13.6,14.5" fill="url(#spring-stone-1)" />
        <polygon points="12.0,15.9 11.2,15.7 13.6,14.5 14.0,14.9" fill="url(#spring-stone-0)" />
        <polygon points="12.9,14.9 12.9,14.4 15.3,13.8 15.3,14.3" fill="url(#spring-water-2)" />
        <polygon points="17.2,14.1 17.1,14.2 16.9,14.2 16.8,14.1 16.8,14.0 16.9,13.9 17.1,13.9 17.2,14.0" fill="url(#spring-water-0)" />
        <polygon points="10.9,14.9 11.2,14.3 13.6,13.1 13.4,13.6" fill="url(#spring-stone-3)" />
        <polygon points="16.2,14.2 16.1,14.6 15.9,14.6 15.8,14.2" fill="url(#spring-water-1)" />
        <polygon points="16.1,14.6 16.0,14.9 15.9,14.6" fill="url(#spring-water-0)" />
        <polygon points="15.9,14.6 16.0,14.9 15.7,14.7" fill="url(#spring-water-0)" />
        <polygon points="16.3,14.7 16.0,14.9 16.1,14.6" fill="url(#spring-water-0)" />
        <polygon points="15.8,14.2 15.9,14.6 15.7,14.7 15.6,14.3" fill="url(#spring-water-2)" />
        <polygon points="16.4,14.3 16.3,14.7 16.1,14.6 16.2,14.2" fill="url(#spring-water-0)" />
        <polygon points="15.7,14.7 16.0,14.9 15.7,14.8" fill="url(#spring-water-1)" />
        <polygon points="16.3,14.8 16.0,14.9 16.3,14.7" fill="url(#spring-water-0)" />
        <polygon points="16.1,14.0 16.2,14.2 15.8,14.2 15.9,14.0" fill="url(#spring-water-2)" />
        <polygon points="15.9,14.0 15.8,14.2 15.6,14.3 15.7,14.1" fill="url(#spring-water-3)" />
        <polygon points="16.3,14.1 16.4,14.3 16.2,14.2 16.1,14.0" fill="url(#spring-water-1)" />
        <polygon points="15.7,14.8 16.0,14.9 15.9,14.9" fill="url(#spring-water-1)" />
        <polygon points="16.1,14.9 16.0,14.9 16.3,14.8" fill="url(#spring-water-0)" />
        <polygon points="15.6,14.3 15.7,14.7 15.7,14.8 15.6,14.5" fill="url(#spring-water-2)" />
        <polygon points="16.4,14.5 16.3,14.8 16.3,14.7 16.4,14.3" fill="url(#spring-water-0)" />
        <polygon points="18.0,14.5 18.0,14.0 19.9,15.0 19.9,15.4" fill="url(#spring-water-0)" />
        <polygon points="15.9,14.9 16.0,14.9 16.1,14.9" fill="url(#spring-water-0)" />
        <polygon points="19.8,15.0 20.1,14.2 21.7,15.7 21.3,16.5" fill="url(#spring-stone-0)" />
        <polygon points="19.2,15.3 19.8,15.0 21.3,16.5 20.4,16.5" fill="url(#spring-stone-0)" />
        <polygon points="13.2,14.4 13.4,14.5 13.5,14.6 13.4,14.7 13.2,14.7 13.1,14.7 13.0,14.5 13.1,14.4" fill="url(#spring-water-0)" />
        <polygon points="20.1,14.2 19.8,13.6 21.3,15.1 21.7,15.7" fill="url(#spring-stone-1)" />
        <polygon points="18.7,22.8 11.7,22.4 8.0,19.5 10.3,16.1 16.9,15.0 22.8,16.9 23.6,20.3" fill="url(#spring-stone-0)" />
        <polygon points="16.9,10.8 17.1,13.9 16.9,13.9 16.7,10.8" fill="url(#spring-water-1)" />
        <polygon points="16.7,10.8 16.9,13.9 16.8,14.0 16.6,10.9" fill="url(#spring-water-2)" />
        <polygon points="17.0,10.9 17.2,14.0 17.1,13.9 16.9,10.8" fill="url(#spring-water-1)" />
        <polygon points="16.6,10.9 16.8,14.0 16.8,14.1 16.6,11.0" fill="url(#spring-water-3)" />
        <polygon points="11.6,16.1 11.6,15.6 12.9,14.4 12.9,14.9" fill="url(#spring-water-3)" />
        <polygon points="11.6,17.2 10.7,17.3 11.2,15.7 12.0,15.9" fill="url(#spring-stone-0)" />
        <polygon points="14.0,11.3 13.4,14.5 13.2,14.4 13.8,11.2" fill="url(#spring-water-1)" />
        <polygon points="13.8,11.2 13.2,14.4 13.1,14.4 13.7,11.3" fill="url(#spring-water-2)" />
        <polygon points="10.7,17.3 10.3,16.7 10.9,14.9 11.2,15.7" fill="url(#spring-stone-2)" />
        <polygon points="14.1,11.4 13.5,14.6 13.4,14.5 14.0,11.3" fill="url(#spring-water-0)" />
        <polygon points="13.7,11.3 13.1,14.4 13.0,14.5 13.6,11.4" fill="url(#spring-water-3)" />
        <polygon points="12.0,16.5 11.6,17.2 12.0,15.9 12.4,15.3" fill="url(#spring-stone-0)" />
        <polygon points="19.6,15.6 19.5,15.5 19.7,15.4 19.8,15.3 20.0,15.3 20.0,15.4 19.9,15.5 19.7,15.6" fill="url(#spring-water-0)" />
        <polygon points="19.9,15.4 19.9,15.0 20.4,16.3 20.4,16.8" fill="url(#spring-water-0)" />
        <polygon points="19.2,15.7 19.2,16.1 18.9,16.1 18.9,15.7" fill="url(#spring-water-1)" />
        <polygon points="13.1,15.7 13.1,16.1 12.8,16.1 12.8,15.7" fill="url(#spring-water-1)" />
        <polygon points="19.2,16.1 19.1,16.4 18.9,16.1" fill="url(#spring-water-0)" />
        <polygon points="13.1,16.1 12.9,16.4 12.8,16.1" fill="url(#spring-water-0)" />
        <polygon points="18.9,16.1 19.1,16.4 18.7,16.2" fill="url(#spring-water-0)" />
        <polygon points="19.4,16.2 19.1,16.4 19.2,16.1" fill="url(#spring-water-0)" />
        <polygon points="12.8,16.1 12.9,16.4 12.6,16.2" fill="url(#spring-water-0)" />
        <polygon points="13.3,16.2 12.9,16.4 13.1,16.1" fill="url(#spring-water-0)" />
        <polygon points="18.9,15.7 18.9,16.1 18.7,16.2 18.6,15.9" fill="url(#spring-water-2)" />
        <polygon points="19.5,15.9 19.4,16.2 19.2,16.1 19.2,15.7" fill="url(#spring-water-0)" />
        <polygon points="12.8,15.7 12.8,16.1 12.6,16.2 12.5,15.9" fill="url(#spring-water-2)" />
        <polygon points="13.4,15.9 13.3,16.2 13.1,16.1 13.1,15.7" fill="url(#spring-water-0)" />
        <polygon points="17.0,11.1 16.9,11.2 16.7,11.2 16.6,11.1 16.6,10.9 16.7,10.8 16.9,10.8 17.0,10.9" fill="url(#spring-water-0)" />
        <polygon points="19.1,18.0 16.7,18.6 14.0,18.4 12.1,17.4 11.6,16.1 12.9,14.9 15.3,14.3 18.0,14.5 19.9,15.4 20.4,16.8" fill="url(#spring-water-0)" />
        <polygon points="18.7,16.2 19.1,16.4 18.7,16.3" fill="url(#spring-water-1)" />
        <polygon points="19.4,16.3 19.1,16.4 19.4,16.2" fill="url(#spring-water-0)" />
        <polygon points="12.6,16.2 12.9,16.4 12.6,16.3" fill="url(#spring-water-1)" />
        <polygon points="13.3,16.3 12.9,16.4 13.3,16.2" fill="url(#spring-water-0)" />
        <polygon points="19.2,15.5 19.2,15.7 18.9,15.7 18.9,15.5" fill="url(#spring-water-2)" />
        <polygon points="13.1,15.5 13.1,15.7 12.8,15.7 12.8,15.5" fill="url(#spring-water-2)" />
        <polygon points="18.9,15.5 18.9,15.7 18.6,15.9 18.7,15.6" fill="url(#spring-water-3)" />
        <polygon points="19.4,15.6 19.5,15.9 19.2,15.7 19.2,15.5" fill="url(#spring-water-1)" />
        <polygon points="12.8,15.5 12.8,15.7 12.5,15.9 12.6,15.6" fill="url(#spring-water-3)" />
        <polygon points="13.3,15.6 13.4,15.9 13.1,15.7 13.1,15.5" fill="url(#spring-water-1)" />
        <polygon points="19.2,16.4 19.1,16.4 19.4,16.3" fill="url(#spring-water-0)" />
        <polygon points="18.7,16.3 19.1,16.4 18.9,16.4" fill="url(#spring-water-1)" />
        <polygon points="12.6,16.3 12.9,16.4 12.8,16.4" fill="url(#spring-water-1)" />
        <polygon points="13.1,16.4 12.9,16.4 13.3,16.3" fill="url(#spring-water-0)" />
        <polygon points="18.6,15.9 18.7,16.2 18.7,16.3 18.6,16.0" fill="url(#spring-water-2)" />
        <polygon points="19.5,16.0 19.4,16.3 19.4,16.2 19.5,15.9" fill="url(#spring-water-0)" />
        <polygon points="12.5,15.9 12.6,16.2 12.6,16.3 12.5,16.0" fill="url(#spring-water-2)" />
        <polygon points="13.4,16.0 13.3,16.3 13.3,16.2 13.4,15.9" fill="url(#spring-water-0)" />
        <polygon points="18.9,16.4 19.1,16.4 19.2,16.4" fill="url(#spring-water-0)" />
        <polygon points="12.8,16.4 12.9,16.4 13.1,16.4" fill="url(#spring-water-0)" />
        <polygon points="16.5,16.2 16.1,16.3 15.7,16.3 15.4,16.1 15.3,15.9 15.5,15.7 15.9,15.6 16.3,15.7 16.6,15.8 16.7,16.0" fill="url(#spring-water-0)" />
        <polygon points="20.4,16.5 21.3,16.5 20.8,18.1 20.0,17.9" fill="url(#spring-stone-0)" />
        <polygon points="19.0,11.9 19.8,15.3 19.7,15.4 18.9,12.0" fill="url(#spring-water-1)" />
        <polygon points="20.0,15.9 20.4,16.5 20.0,17.9 19.6,17.1" fill="url(#spring-stone-2)" />
        <polygon points="18.9,12.0 19.7,15.4 19.5,15.5 18.8,12.1" fill="url(#spring-water-2)" />
        <polygon points="19.2,12.0 20.0,15.3 19.8,15.3 19.0,11.9" fill="url(#spring-water-1)" />
        <polygon points="21.3,16.5 21.7,15.7 21.1,17.5 20.8,18.1" fill="url(#spring-stone-0)" />
        <polygon points="18.8,12.1 19.5,15.5 19.6,15.6 18.8,12.2" fill="url(#spring-water-2)" />
        <polygon points="13.8,11.2 14.0,11.3 14.0,11.4 14.0,11.5 13.8,11.6 13.7,11.5 13.6,11.3 13.7,11.2" fill="url(#spring-water-0)" />
        <polygon points="16.7,9.3 16.9,10.8 16.7,10.8 16.5,9.3" fill="url(#spring-water-2)" />
        <polygon points="16.5,9.3 16.7,10.8 16.6,10.9 16.4,9.4" fill="url(#spring-water-2)" />
        <polygon points="16.8,9.4 17.0,10.9 16.9,10.8 16.7,9.3" fill="url(#spring-water-1)" />
        <polygon points="16.4,9.4 16.6,10.9 16.6,11.1 16.4,9.5" fill="url(#spring-water-3)" />
        <polygon points="12.0,16.5 12.0,16.4 12.1,16.3 12.3,16.4 12.4,16.5 12.5,16.5 12.3,16.6 12.2,16.6" fill="url(#spring-water-0)" />
        <polygon points="15.9,15.6 15.8,9.5 16.7,9.6 16.3,15.7" fill="url(#spring-water-1)" />
        <polygon points="15.5,15.7 15.0,9.7 15.8,9.5 15.9,15.6" fill="url(#spring-water-2)" />
        <polygon points="14.6,9.7 14.0,11.3 13.8,11.2 14.4,9.6" fill="url(#spring-water-1)" />
        <polygon points="14.4,9.6 13.8,11.2 13.7,11.2 14.2,9.6" fill="url(#spring-water-2)" />
        <polygon points="14.6,9.8 14.0,11.4 14.0,11.3 14.6,9.7" fill="url(#spring-water-0)" />
        <polygon points="13.1,17.6 12.8,18.5 11.6,17.2 12.0,16.5" fill="url(#spring-stone-0)" />
        <polygon points="14.2,9.6 13.7,11.2 13.6,11.3 14.2,9.7" fill="url(#spring-water-3)" />
        <polygon points="12.8,18.5 12.2,18.8 10.7,17.3 11.6,17.2" fill="url(#spring-stone-0)" />
        <polygon points="16.3,15.7 16.7,9.6 17.3,9.9 16.6,15.8" fill="url(#spring-water-0)" />
        <polygon points="15.3,15.9 14.6,10.1 15.0,9.7 15.5,15.7" fill="url(#spring-water-2)" />
        <polygon points="18.8,12.2 18.8,12.1 18.9,12.0 19.0,11.9 19.2,11.9 19.2,12.0 19.1,12.2 18.9,12.2" fill="url(#spring-water-0)" />
        <polygon points="16.8,9.6 16.7,9.7 16.5,9.7 16.4,9.6 16.4,9.4 16.5,9.2 16.7,9.2 16.8,9.4" fill="url(#spring-water-0)" />
        <polygon points="12.8,17.1 13.1,17.6 12.0,16.5 11.6,15.9" fill="url(#spring-stone-1)" />
        <polygon points="13.1,12.8 12.3,16.4 12.1,16.3 12.9,12.8" fill="url(#spring-water-1)" />
        <polygon points="16.6,15.8 17.3,9.9 17.4,10.3 16.7,16.0" fill="url(#spring-water-0)" />
        <polygon points="13.2,12.9 12.4,16.5 12.3,16.4 13.1,12.8" fill="url(#spring-water-0)" />
        <polygon points="12.9,12.8 12.1,16.3 12.0,16.4 12.8,12.8" fill="url(#spring-water-3)" />
        <polygon points="13.2,12.9 12.5,16.5 12.4,16.5 13.2,12.9" fill="url(#spring-water-0)" />
        <polygon points="16.2,9.6 16.4,9.6 16.5,9.7 16.3,9.7" fill="url(#spring-water-1)" />
        <polygon points="16.2,9.4 16.4,9.4 16.4,9.6 16.2,9.6" fill="url(#spring-water-3)" />
        <polygon points="16.3,9.7 16.5,9.7 16.7,9.7 16.5,9.7" fill="url(#spring-water-0)" />
        <polygon points="16.2,8.3 16.0,9.1 15.5,9.1 15.4,8.3" fill="url(#spring-foam-1)" />
        <polygon points="16.3,9.3 16.5,9.2 16.4,9.4 16.2,9.4" fill="url(#spring-water-3)" />
        <polygon points="16.0,9.1 15.8,9.7 15.5,9.1" fill="url(#spring-foam-0)" />
        <polygon points="18.2,10.1 19.0,11.9 18.9,12.0 18.1,10.2" fill="url(#spring-water-1)" />
        <polygon points="19.6,17.1 20.0,17.9 18.0,18.9 17.8,18.0" fill="url(#spring-stone-1)" />
        <polygon points="14.5,9.5 14.6,9.7 14.6,9.9 14.5,10.0 14.3,10.0 14.2,9.8 14.2,9.6 14.3,9.5" fill="url(#spring-water-2)" />
        <polygon points="18.1,10.2 18.9,12.0 18.8,12.1 18.0,10.3" fill="url(#spring-water-2)" />
        <polygon points="18.4,10.1 19.2,11.9 19.0,11.9 18.2,10.1" fill="url(#spring-water-1)" />
        <polygon points="15.5,9.1 15.8,9.7 15.1,9.3" fill="url(#spring-foam-0)" />
        <polygon points="16.4,9.3 15.8,9.7 16.0,9.1" fill="url(#spring-foam-0)" />
        <polygon points="16.2,17.3 16.1,17.6 15.9,17.6 15.8,17.3" fill="url(#spring-water-1)" />
        <polygon points="16.1,17.6 16.0,17.9 15.9,17.6" fill="url(#spring-water-0)" />
        <polygon points="18.0,10.3 18.8,12.1 18.8,12.2 18.0,10.4" fill="url(#spring-water-2)" />
        <polygon points="20.0,17.9 20.8,18.1 18.4,19.3 18.0,18.9" fill="url(#spring-stone-0)" />
        <polygon points="15.4,8.3 15.5,9.1 15.1,9.3 14.8,8.6" fill="url(#spring-foam-2)" />
        <polygon points="16.7,8.6 16.4,9.3 16.0,9.1 16.2,8.3" fill="url(#spring-foam-0)" />
        <polygon points="15.9,17.6 16.0,17.9 15.7,17.7" fill="url(#spring-water-0)" />
        <polygon points="16.3,17.7 16.0,17.9 16.1,17.6" fill="url(#spring-water-0)" />
        <polygon points="15.8,17.3 15.9,17.6 15.7,17.7 15.6,17.4" fill="url(#spring-water-2)" />
        <polygon points="16.4,17.4 16.3,17.7 16.1,17.6 16.2,17.3" fill="url(#spring-water-0)" />
        <polygon points="15.1,9.8 14.6,9.9 14.6,9.7 15.1,9.6" fill="url(#spring-water-0)" />
        <polygon points="15.1,9.9 14.5,10.0 14.6,9.9 15.1,9.8" fill="url(#spring-water-0)" />
        <polygon points="18.8,17.3 18.9,17.3 19.0,17.3 18.9,17.4 18.8,17.4 18.6,17.4 18.5,17.4 18.6,17.3" fill="url(#spring-water-0)" />
        <polygon points="15.1,9.6 14.6,9.7 14.5,9.5 15.0,9.5" fill="url(#spring-water-1)" />
        <polygon points="15.7,17.7 16.0,17.9 15.7,17.9" fill="url(#spring-water-1)" />
        <polygon points="16.3,17.9 16.0,17.9 16.3,17.7" fill="url(#spring-water-0)" />
        <polygon points="16.1,17.0 16.2,17.3 15.8,17.3 15.9,17.0" fill="url(#spring-water-2)" />
        <polygon points="16.6,9.5 16.4,10.7 15.6,10.7 15.4,9.5" fill="url(#spring-foam-1)" />
        <polygon points="15.1,9.3 15.8,9.7 15.1,9.6" fill="url(#spring-foam-1)" />
        <polygon points="16.4,9.6 15.8,9.7 16.4,9.3" fill="url(#spring-foam-0)" />
        <polygon points="14.9,9.9 14.3,10.0 14.5,10.0 15.1,9.9" fill="url(#spring-water-0)" />
        <polygon points="16.4,10.7 16.0,11.6 15.6,10.7" fill="url(#spring-foam-0)" />
        <polygon points="16.0,7.8 16.2,8.3 15.4,8.3 15.5,7.8" fill="url(#spring-foam-2)" />
        <polygon points="15.9,17.0 15.8,17.3 15.6,17.4 15.7,17.1" fill="url(#spring-water-3)" />
        <polygon points="16.3,17.1 16.4,17.4 16.2,17.3 16.1,17.0" fill="url(#spring-water-1)" />
        <polygon points="15.7,17.9 16.0,17.9 15.9,18.0" fill="url(#spring-water-1)" />
        <polygon points="16.1,18.0 16.0,17.9 16.3,17.9" fill="url(#spring-water-0)" />
        <polygon points="15.6,17.4 15.7,17.7 15.7,17.9 15.6,17.6" fill="url(#spring-water-2)" />
        <polygon points="16.4,17.6 16.3,17.9 16.3,17.7 16.4,17.4" fill="url(#spring-water-0)" />
        <polygon points="20.0,16.5 19.6,17.1 17.8,18.0 18.0,17.5" fill="url(#spring-stone-3)" />
        <polygon points="15.9,18.0 16.0,17.9 16.1,18.0" fill="url(#spring-water-0)" />
        <polygon points="15.6,10.7 16.0,11.6 15.1,11.0" fill="url(#spring-foam-0)" />
        <polygon points="16.9,11.0 16.0,11.6 16.4,10.7" fill="url(#spring-foam-0)" />
        <polygon points="15.5,7.8 15.4,8.3 14.8,8.6 15.1,8.0" fill="url(#spring-foam-3)" />
        <polygon points="16.4,8.0 16.7,8.6 16.2,8.3 16.0,7.8" fill="url(#spring-foam-1)" />
        <polygon points="17.7,8.7 17.6,9.5 17.0,9.5 16.9,8.7" fill="url(#spring-foam-1)" />
        <polygon points="15.4,9.5 15.6,10.7 15.1,11.0 14.7,9.9" fill="url(#spring-foam-2)" />
        <polygon points="17.3,9.9 16.9,11.0 16.4,10.7 16.6,9.5" fill="url(#spring-foam-0)" />
        <polygon points="15.1,9.6 15.8,9.7 15.5,9.8" fill="url(#spring-foam-1)" />
        <polygon points="16.0,9.8 15.8,9.7 16.4,9.6" fill="url(#spring-foam-0)" />
        <polygon points="16.7,9.0 16.4,9.6 16.4,9.3 16.7,8.6" fill="url(#spring-foam-0)" />
        <polygon points="14.8,8.6 15.1,9.3 15.1,9.6 14.8,9.0" fill="url(#spring-foam-2)" />
        <polygon points="17.6,9.5 17.3,10.1 17.0,9.5" fill="url(#spring-foam-0)" />
        <polygon points="15.4,18.2 15.3,19.1 12.8,18.5 13.1,17.6" fill="url(#spring-stone-0)" />
        <polygon points="15.5,9.8 15.8,9.7 16.0,9.8" fill="url(#spring-foam-0)" />
        <polygon points="17.0,9.5 17.3,10.1 16.6,9.7" fill="url(#spring-foam-0)" />
        <polygon points="18.0,9.7 17.3,10.1 17.6,9.5" fill="url(#spring-foam-0)" />
        <polygon points="16.9,8.7 17.0,9.5 16.6,9.7 16.3,9.0" fill="url(#spring-foam-2)" />
        <polygon points="18.2,9.0 18.0,9.7 17.6,9.5 17.7,8.7" fill="url(#spring-foam-0)" />
        <polygon points="12.8,12.9 12.8,12.8 12.9,12.7 13.1,12.8 13.2,12.9 13.2,13.0 13.1,13.0 13.0,12.9" fill="url(#spring-water-1)" />
        <polygon points="17.3,10.0 18.1,10.2 18.1,10.4 17.3,10.1" fill="url(#spring-water-1)" />
        <polygon points="18.1,10.5 18.1,10.4 18.1,10.2 18.2,10.1 18.3,10.0 18.3,10.1 18.3,10.3 18.2,10.5" fill="url(#spring-water-0)" />
        <polygon points="15.3,19.1 15.2,19.5 12.2,18.8 12.8,18.5" fill="url(#spring-stone-0)" />
        <polygon points="15.1,11.0 16.0,11.6 15.1,11.4" fill="url(#spring-foam-1)" />
        <polygon points="16.9,11.4 16.0,11.6 16.9,11.0" fill="url(#spring-foam-0)" />
        <polygon points="17.4,9.8 18.2,10.1 18.1,10.2 17.3,10.0" fill="url(#spring-water-2)" />
        <polygon points="16.4,8.8 16.6,9.5 15.4,9.5 15.6,8.8" fill="url(#spring-foam-2)" />
        <polygon points="18.2,13.5 18.8,17.3 18.6,17.3 18.0,13.5" fill="url(#spring-water-1)" />
        <polygon points="18.3,13.5 18.9,17.3 18.8,17.3 18.2,13.5" fill="url(#spring-water-1)" />
        <polygon points="17.3,10.1 18.1,10.4 18.1,10.5 17.3,10.3" fill="url(#spring-water-1)" />
        <polygon points="15.0,8.9 14.9,9.7 14.3,9.7 14.2,8.9" fill="url(#spring-foam-1)" />
        <polygon points="17.8,18.0 18.0,18.9 15.3,19.1 15.4,18.2" fill="url(#spring-stone-1)" />
        <polygon points="14.9,9.7 14.6,10.3 14.3,9.7" fill="url(#spring-foam-0)" />
        <polygon points="16.6,9.7 17.3,10.1 16.6,10.0" fill="url(#spring-foam-1)" />
        <polygon points="18.0,10.0 17.3,10.1 18.0,9.7" fill="url(#spring-foam-0)" />
        <polygon points="17.6,8.1 17.7,8.7 16.9,8.7 17.0,8.1" fill="url(#spring-foam-2)" />
        <polygon points="18.0,13.5 18.6,17.3 18.5,17.4 17.9,13.6" fill="url(#spring-water-2)" />
        <polygon points="17.5,9.8 18.3,10.0 18.2,10.1 17.4,9.8" fill="url(#spring-water-2)" />
        <polygon points="18.4,13.5 19.0,17.3 18.9,17.3 18.3,13.5" fill="url(#spring-water-0)" />
        <polygon points="15.3,17.7 15.4,18.2 13.1,17.6 12.8,17.1" fill="url(#spring-stone-1)" />
        <polygon points="14.3,9.7 14.6,10.3 13.9,9.9" fill="url(#spring-foam-0)" />
        <polygon points="15.2,9.9 14.6,10.3 14.9,9.7" fill="url(#spring-foam-0)" />
        <polygon points="15.2,17.9 15.1,17.9 14.9,17.9 14.8,17.9 14.8,17.8 14.9,17.8 15.1,17.8 15.2,17.8" fill="url(#spring-water-0)" />
        <polygon points="13.9,10.8 13.1,12.8 12.9,12.7 13.7,10.7" fill="url(#spring-water-1)" />
        <polygon points="14.0,10.9 13.2,12.9 13.1,12.8 13.9,10.8" fill="url(#spring-water-0)" />
        <polygon points="14.2,8.9 14.3,9.7 13.9,9.9 13.6,9.2" fill="url(#spring-foam-2)" />
        <polygon points="15.5,9.2 15.2,9.9 14.9,9.7 15.0,8.9" fill="url(#spring-foam-0)" />
        <polygon points="15.6,8.8 15.4,9.5 14.7,9.9 15.1,9.0" fill="url(#spring-foam-3)" />
        <polygon points="16.9,9.0 17.3,9.9 16.6,9.5 16.4,8.8" fill="url(#spring-foam-1)" />
        <polygon points="17.0,8.1 16.9,8.7 16.3,9.0 16.6,8.3" fill="url(#spring-foam-3)" />
        <polygon points="18.0,8.3 18.2,9.0 17.7,8.7 17.6,8.1" fill="url(#spring-foam-1)" />
        <polygon points="18.0,18.9 18.4,19.3 15.2,19.5 15.3,19.1" fill="url(#spring-stone-0)" />
        <polygon points="13.7,10.7 12.9,12.7 12.8,12.8 13.6,10.7" fill="url(#spring-water-3)" />
        <polygon points="16.6,10.0 17.3,10.1 17.0,10.2" fill="url(#spring-foam-1)" />
        <polygon points="17.6,10.2 17.3,10.1 18.0,10.0" fill="url(#spring-foam-0)" />
        <polygon points="14.0,11.0 13.2,13.0 13.2,12.9 14.0,10.9" fill="url(#spring-water-0)" />
        <polygon points="15.1,11.4 16.0,11.6 15.6,11.6" fill="url(#spring-foam-1)" />
        <polygon points="16.4,11.6 16.0,11.6 16.9,11.4" fill="url(#spring-foam-0)" />
        <polygon points="18.2,9.3 18.0,10.0 18.0,9.7 18.2,9.0" fill="url(#spring-foam-0)" />
        <polygon points="16.3,9.0 16.6,9.7 16.6,10.0 16.3,9.3" fill="url(#spring-foam-2)" />
        <polygon points="14.7,9.9 15.1,11.0 15.1,11.4 14.7,10.5" fill="url(#spring-foam-2)" />
        <polygon points="17.3,10.5 16.9,11.4 16.9,11.0 17.3,9.9" fill="url(#spring-foam-0)" />
        <polygon points="13.9,9.9 14.6,10.3 13.9,10.2" fill="url(#spring-foam-1)" />
        <polygon points="15.2,10.2 14.6,10.3 15.2,9.9" fill="url(#spring-foam-0)" />
        <polygon points="17.0,10.2 17.3,10.1 17.6,10.2" fill="url(#spring-foam-0)" />
        <polygon points="14.9,8.4 15.0,8.9 14.2,8.9 14.3,8.4" fill="url(#spring-foam-2)" />
        <polygon points="18.0,17.5 17.8,18.0 15.4,18.2 15.3,17.7" fill="url(#spring-stone-2)" />
        <polygon points="15.6,11.6 16.0,11.6 16.4,11.6" fill="url(#spring-foam-0)" />
        <polygon points="14.3,8.4 14.2,8.9 13.6,9.2 13.9,8.6" fill="url(#spring-foam-3)" />
        <polygon points="15.2,8.6 15.5,9.2 15.0,8.9 14.9,8.4" fill="url(#spring-foam-1)" />
        <polygon points="13.9,10.2 14.6,10.3 14.3,10.4" fill="url(#spring-foam-1)" />
        <polygon points="14.9,10.4 14.6,10.3 15.2,10.2" fill="url(#spring-foam-0)" />
        <polygon points="15.5,9.6 15.2,10.2 15.2,9.9 15.5,9.2" fill="url(#spring-foam-0)" />
        <polygon points="13.6,9.2 13.9,9.9 13.9,10.2 13.6,9.6" fill="url(#spring-foam-2)" />
        <polygon points="14.7,10.5 13.9,11.0 13.8,10.8 14.6,10.4" fill="url(#spring-water-0)" />
        <polygon points="14.6,10.4 13.8,10.8 13.7,10.7 14.5,10.2" fill="url(#spring-water-1)" />
        <polygon points="15.3,13.9 15.1,17.8 14.9,17.8 15.1,13.9" fill="url(#spring-water-1)" />
        <polygon points="15.1,13.9 14.9,17.8 14.8,17.8 15.0,13.9" fill="url(#spring-water-2)" />
        <polygon points="14.3,10.4 14.6,10.3 14.9,10.4" fill="url(#spring-foam-0)" />
        <polygon points="15.4,14.0 15.2,17.8 15.1,17.8 15.3,13.9" fill="url(#spring-water-0)" />
        <polygon points="14.7,10.6 13.9,11.1 13.9,11.0 14.7,10.5" fill="url(#spring-water-0)" />
        <polygon points="14.5,10.2 13.7,10.7 13.7,10.6 14.5,10.2" fill="url(#spring-water-3)" />
        <polygon points="13.7,10.7 13.7,10.6 13.7,10.7 13.8,10.8 13.9,11.0 13.9,11.1 13.9,11.0 13.8,10.9" fill="url(#spring-water-2)" />
        <polygon points="15.0,13.9 14.8,17.8 14.8,17.9 15.0,14.0" fill="url(#spring-water-3)" />
        <polygon points="18.2,13.5 18.3,13.5 18.4,13.5 18.3,13.6 18.2,13.6 18.0,13.6 18.0,13.6 18.0,13.6" fill="url(#spring-water-0)" />
        <polygon points="17.4,9.5 17.3,10.3 16.7,10.3 16.6,9.5" fill="url(#spring-foam-1)" />
        <polygon points="17.3,10.3 17.0,10.9 16.7,10.3" fill="url(#spring-foam-0)" />
        <polygon points="17.6,11.3 18.2,13.5 18.0,13.6 17.4,11.4" fill="url(#spring-water-1)" />
        <polygon points="16.7,10.3 17.0,10.9 16.4,10.5" fill="url(#spring-foam-0)" />
        <polygon points="17.7,10.5 17.0,10.9 17.3,10.3" fill="url(#spring-foam-0)" />
        <polygon points="17.8,11.3 18.3,13.5 18.2,13.5 17.6,11.3" fill="url(#spring-water-1)" />
        <polygon points="16.6,9.5 16.7,10.3 16.4,10.5 16.1,9.8" fill="url(#spring-foam-2)" />
        <polygon points="18.0,9.8 17.7,10.5 17.3,10.3 17.4,9.5" fill="url(#spring-foam-0)" />
        <polygon points="15.7,9.7 15.6,10.5 15.1,10.5 15.0,9.7" fill="url(#spring-foam-1)" />
        <polygon points="17.4,11.4 18.0,13.6 18.0,13.6 17.4,11.4" fill="url(#spring-water-2)" />
        <polygon points="15.6,10.5 15.3,11.1 15.1,10.5" fill="url(#spring-foam-0)" />
        <polygon points="17.8,11.3 18.4,13.5 18.3,13.5 17.8,11.3" fill="url(#spring-water-0)" />
        <polygon points="17.1,10.8 17.7,11.4 17.5,11.5 16.9,10.9" fill="url(#spring-water-0)" />
        <polygon points="15.1,10.5 15.3,11.1 14.7,10.7" fill="url(#spring-foam-0)" />
        <polygon points="16.0,10.7 15.3,11.1 15.6,10.5" fill="url(#spring-foam-0)" />
        <polygon points="17.2,10.6 17.8,11.3 17.7,11.4 17.1,10.8" fill="url(#spring-water-0)" />
        <polygon points="16.4,10.5 17.0,10.9 16.4,10.8" fill="url(#spring-foam-1)" />
        <polygon points="17.7,10.8 17.0,10.9 17.7,10.5" fill="url(#spring-foam-0)" />
        <polygon points="15.0,9.7 15.1,10.5 14.7,10.7 14.4,9.9" fill="url(#spring-foam-2)" />
        <polygon points="16.3,9.9 16.0,10.7 15.6,10.5 15.7,9.7" fill="url(#spring-foam-0)" />
        <polygon points="17.3,9.0 17.4,9.5 16.6,9.5 16.7,9.0" fill="url(#spring-foam-2)" />
        <polygon points="16.9,10.9 16.9,10.9 16.9,10.8 17.0,10.7 17.1,10.5 17.2,10.5 17.2,10.6 17.1,10.8" fill="url(#spring-water-3)" />
        <polygon points="16.9,10.9 17.5,11.5 17.4,11.5 16.9,10.9" fill="url(#spring-water-1)" />
        <polygon points="17.2,10.5 17.8,11.2 17.8,11.3 17.2,10.6" fill="url(#spring-water-1)" />
        <polygon points="14.7,10.7 15.3,11.1 14.7,10.9" fill="url(#spring-foam-1)" />
        <polygon points="16.0,10.9 15.3,11.1 16.0,10.7" fill="url(#spring-foam-0)" />
        <polygon points="16.7,9.0 16.6,9.5 16.1,9.8 16.4,9.2" fill="url(#spring-foam-3)" />
        <polygon points="17.7,9.2 18.0,9.8 17.4,9.5 17.3,9.0" fill="url(#spring-foam-1)" />
        <polygon points="15.4,14.0 15.3,14.0 15.1,14.0 15.0,13.9 15.0,13.9 15.1,13.9 15.3,14.0 15.4,14.0" fill="url(#spring-water-0)" />
        <polygon points="15.6,9.1 15.7,9.7 15.0,9.7 15.1,9.1" fill="url(#spring-foam-2)" />
        <polygon points="16.4,10.8 17.0,10.9 16.7,11.0" fill="url(#spring-foam-1)" />
        <polygon points="17.3,11.0 17.0,10.9 17.7,10.8" fill="url(#spring-foam-0)" />
        <polygon points="16.1,9.8 16.4,10.5 16.4,10.8 16.1,10.2" fill="url(#spring-foam-2)" />
        <polygon points="18.0,10.2 17.7,10.8 17.7,10.5 18.0,9.8" fill="url(#spring-foam-0)" />
        <polygon points="15.5,11.6 15.3,14.0 15.1,13.9 15.3,11.6" fill="url(#spring-water-1)" />
        <polygon points="15.8,11.0 15.7,11.1 15.5,11.0 15.4,10.9 15.4,10.8 15.5,10.7 15.7,10.8 15.8,10.9" fill="url(#spring-water-2)" />
        <polygon points="15.3,11.6 15.1,13.9 15.0,13.9 15.2,11.6" fill="url(#spring-water-2)" />
        <polygon points="15.7,11.1 15.5,11.8 15.3,11.8 15.5,11.0" fill="url(#spring-water-0)" />
        <polygon points="16.7,11.0 17.0,10.9 17.3,11.0" fill="url(#spring-foam-0)" />
        <polygon points="15.6,11.7 15.4,14.0 15.3,14.0 15.5,11.6" fill="url(#spring-water-0)" />
        <polygon points="15.5,11.0 15.3,11.8 15.2,11.7 15.4,10.9" fill="url(#spring-water-1)" />
        <polygon points="15.8,11.0 15.6,11.8 15.5,11.8 15.7,11.1" fill="url(#spring-water-0)" />
        <polygon points="15.1,9.1 15.0,9.7 14.4,9.9 14.7,9.3" fill="url(#spring-foam-3)" />
        <polygon points="16.0,9.3 16.3,9.9 15.7,9.7 15.6,9.1" fill="url(#spring-foam-1)" />
        <polygon points="14.7,10.9 15.3,11.1 15.1,11.1" fill="url(#spring-foam-1)" />
        <polygon points="15.6,11.1 15.3,11.1 16.0,10.9" fill="url(#spring-foam-0)" />
        <polygon points="14.4,9.9 14.7,10.7 14.7,10.9 14.4,10.3" fill="url(#spring-foam-2)" />
        <polygon points="16.3,10.3 16.0,10.9 16.0,10.7 16.3,9.9" fill="url(#spring-foam-0)" />
        <polygon points="15.2,11.6 15.0,13.9 15.0,13.9 15.2,11.6" fill="url(#spring-water-3)" />
        <polygon points="15.4,10.9 15.2,11.7 15.2,11.5 15.4,10.8" fill="url(#spring-water-3)" />
        <polygon points="15.1,11.1 15.3,11.1 15.6,11.1" fill="url(#spring-foam-0)" />
      </g>
    </svg>
  );
}
