// THE RELICS' FACES in the corner panel (owner, 2026-09-04: "more
// representative of what they do and what they are", then "relic icons should
// match the style of the other icons"): one SVG per skill, the same object the
// relic takes in the world (relicShapes.ts), drawn in the toolbar's idiom
// (BrushIcons.tsx) — gradient-lit solid faces on the isometric grass tile, no
// outlines, a cast shade on the grass, a drop shadow from the tile's own CSS.
// The skill's category colour (gems.ts) is the glow on the grass and the
// object's own material, so the three-colour code a player learns from the
// gems still holds.
//
// GENERATED by .claude/orchestration/refs/hud-icons/relics.py, which projects
// the world shapes onto the tile; edit the art there and rerun it, since the
// polygons below are its output. Gradient ids are prefixed with the skill's
// name because SVG ids are document-global and the panel shows several of
// these at once.

import type { JSX } from 'solid-js';

/** The tile every icon stands on — the toolbar icons' own, verbatim. */
function Tile(props: { prefix: string; glow: string }): JSX.Element {
  return (
    <>
      <defs>
        <linearGradient id={`${props.prefix}-tile-top`} x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stop-color="#a6e08a" />
          <stop offset="1" stop-color="#4f9a4a" />
        </linearGradient>
        <linearGradient id={`${props.prefix}-tile-left`} x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#9a6a45" />
          <stop offset="1" stop-color="#5a3a22" />
        </linearGradient>
        <linearGradient id={`${props.prefix}-tile-right`} x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#6e4a2f" />
          <stop offset="1" stop-color="#3a2415" />
        </linearGradient>
      </defs>
      <ellipse cx="16" cy="27.5" rx="12" ry="3" fill="#000" opacity="0.35" />
      <polygon points="16,13 28,19 16,25 4,19" fill={`url(#${props.prefix}-tile-top)`} />
      <polygon points="4,19 16,25 16,29 4,23" fill={`url(#${props.prefix}-tile-left)`} />
      <polygon points="28,19 16,25 16,29 28,23" fill={`url(#${props.prefix}-tile-right)`} />
      <ellipse cx="16" cy="19" rx="7" ry="3.2" fill={props.glow} opacity="0.3" />
    </>
  );
}

/** Titan's Hand: an open stone hand pressing the ground flat and wide. */
export function TitansHandIcon(): JSX.Element {
  return (
    <svg class="relics-gem" viewBox="0 0 32 32" aria-hidden="true">
      <defs>
        <linearGradient id="titan-pad-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#c8f0a8" />
          <stop offset="1" stop-color="#a6d48e" />
        </linearGradient>
        <linearGradient id="titan-pad-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#84b873" />
          <stop offset="1" stop-color="#619b58" />
        </linearGradient>
        <linearGradient id="titan-stone-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#ffe2b0" />
          <stop offset="1" stop-color="#e2be88" />
        </linearGradient>
        <linearGradient id="titan-stone-1" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#e2be88" />
          <stop offset="1" stop-color="#c49b60" />
        </linearGradient>
        <linearGradient id="titan-stone-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#c49b60" />
          <stop offset="1" stop-color="#a77838" />
        </linearGradient>
        <linearGradient id="titan-stone-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#a77838" />
          <stop offset="1" stop-color="#8a5410" />
        </linearGradient>
      </defs>
      <Tile prefix="titan" glow="#ffb347" />
      <ellipse cx="16" cy="19.2" rx="8.5" ry="3.6" fill="#2e5a2e" opacity="0.5" />
      <polygon points="16.0,13.0 26.8,18.4 16.0,23.8 5.2,18.4" fill="url(#titan-pad-0)" />
      <polygon points="16.7,11.2 24.0,14.8 18.3,17.7 11.0,14.0" fill="url(#titan-stone-0)" />
      <polygon points="12.3,17.9 7.9,20.1 7.9,17.7 12.3,15.5" fill="url(#titan-stone-2)" />
      <polygon points="11.0,14.8 12.3,15.5 7.9,17.7 6.6,17.0" fill="url(#titan-stone-0)" />
      <polygon points="11.0,17.2 11.0,14.0 18.3,17.7 18.3,20.9" fill="url(#titan-stone-0)" />
      <polygon points="24.0,18.0 18.3,20.9 18.3,17.7 24.0,14.8" fill="url(#titan-stone-2)" />
      <polygon points="6.6,19.4 6.6,17.0 7.9,17.7 7.9,20.1" fill="url(#titan-stone-0)" />
      <polygon points="14.3,18.9 9.9,21.1 9.9,18.7 14.3,16.5" fill="url(#titan-stone-2)" />
      <polygon points="13.0,15.8 14.3,16.5 9.9,18.7 8.6,18.0" fill="url(#titan-stone-0)" />
      <polygon points="24.3,18.8 22.7,21.5 22.7,19.1 24.3,16.4" fill="url(#titan-stone-3)" />
      <polygon points="22.3,16.1 24.3,16.4 22.7,19.1 20.7,18.8" fill="url(#titan-stone-0)" />
      <polygon points="26.8,19.0 16.0,24.4 16.0,23.8 26.8,18.4" fill="url(#titan-pad-2)" />
      <polygon points="5.2,19.0 5.2,18.4 16.0,23.8 16.0,24.4" fill="url(#titan-pad-0)" />
      <polygon points="8.6,20.4 8.6,18.0 9.9,18.7 9.9,21.1" fill="url(#titan-stone-0)" />
      <polygon points="16.3,19.8 11.9,22.1 11.9,19.7 16.3,17.4" fill="url(#titan-stone-2)" />
      <polygon points="15.0,16.8 16.3,17.4 11.9,19.7 10.6,19.0" fill="url(#titan-stone-0)" />
      <polygon points="20.7,21.2 20.7,18.8 22.7,19.1 22.7,21.5" fill="url(#titan-stone-1)" />
      <polygon points="10.6,21.4 10.6,19.0 11.9,19.7 11.9,22.1" fill="url(#titan-stone-0)" />
      <polygon points="18.3,20.8 13.8,23.1 13.8,20.7 18.3,18.4" fill="url(#titan-stone-2)" />
      <polygon points="17.0,17.8 18.3,18.4 13.8,20.7 12.5,20.0" fill="url(#titan-stone-0)" />
      <polygon points="12.5,22.4 12.5,20.0 13.8,20.7 13.8,23.1" fill="url(#titan-stone-0)" />
    </svg>
  );
}

/** Quake: a shattered slab of rock, shards standing out of it. */
export function QuakeIcon(): JSX.Element {
  return (
    <svg class="relics-gem" viewBox="0 0 32 32" aria-hidden="true">
      <defs>
        <linearGradient id="quake-rock-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#7a6a5a" />
          <stop offset="1" stop-color="#66584a" />
        </linearGradient>
        <linearGradient id="quake-rock-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#524539" />
          <stop offset="1" stop-color="#3e3228" />
        </linearGradient>
        <linearGradient id="quake-rock-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#3e3228" />
          <stop offset="1" stop-color="#2a2018" />
        </linearGradient>
        <linearGradient id="quake-shard-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#ffc2b8" />
          <stop offset="1" stop-color="#db9890" />
        </linearGradient>
        <linearGradient id="quake-shard-1" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#db9890" />
          <stop offset="1" stop-color="#b86d68" />
        </linearGradient>
        <linearGradient id="quake-shard-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#b86d68" />
          <stop offset="1" stop-color="#944240" />
        </linearGradient>
        <linearGradient id="quake-shard-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#944240" />
          <stop offset="1" stop-color="#701818" />
        </linearGradient>
      </defs>
      <Tile prefix="quake" glow="#ff5c5c" />
      <ellipse cx="16" cy="19.2" rx="8" ry="3.4" fill="#2e5a2e" opacity="0.5" />
      <polygon points="14.0,15.3 14.4,14.2 20.5,15.0 21.4,16.3" fill="url(#quake-rock-2)" />
      <polygon points="8.6,18.0 9.9,16.4 14.4,14.2 14.0,15.3" fill="url(#quake-rock-3)" />
      <polygon points="18.0,22.7 10.6,21.7 8.6,18.0 14.0,15.3 21.4,16.3 23.4,20.0" fill="url(#quake-rock-0)" />
      <polygon points="16.4,9.5 17.8,15.8 13.8,16.4" fill="url(#quake-shard-2)" />
      <polygon points="13.8,16.4 11.2,12.8 16.4,9.5" fill="url(#quake-shard-0)" />
      <polygon points="20.0,17.9 20.5,17.0 21.6,12.9" fill="url(#quake-shard-0)" />
      <polygon points="21.6,12.9 24.8,17.3 20.0,17.9" fill="url(#quake-shard-1)" />
      <polygon points="12.6,16.0 10.1,14.7 16.1,16.0" fill="url(#quake-shard-0)" />
      <polygon points="12.0,20.7 10.1,14.7 12.6,16.0" fill="url(#quake-shard-0)" />
      <polygon points="12.0,20.7 12.6,16.0 16.1,16.0" fill="url(#quake-shard-3)" />
      <polygon points="17.4,15.7 21.6,15.9 14.1,20.1" fill="url(#quake-shard-3)" />
      <polygon points="14.5,10.9 21.6,15.9 17.4,15.7" fill="url(#quake-shard-1)" />
      <polygon points="14.1,20.1 14.5,10.9 17.4,15.7" fill="url(#quake-shard-0)" />
    </svg>
  );
}

/** Genesis: an island risen out of the tile, one tree on it. */
export function GenesisIcon(): JSX.Element {
  return (
    <svg class="relics-gem" viewBox="0 0 32 32" aria-hidden="true">
      <defs>
        <linearGradient id="genesis-bark-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#a06a3a" />
          <stop offset="1" stop-color="#8a5a30" />
        </linearGradient>
        <linearGradient id="genesis-bark-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#754b27" />
          <stop offset="1" stop-color="#603c1e" />
        </linearGradient>
        <linearGradient id="genesis-bark-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#603c1e" />
          <stop offset="1" stop-color="#4a2c14" />
        </linearGradient>
        <linearGradient id="genesis-canopy-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#ffc2b8" />
          <stop offset="1" stop-color="#db9890" />
        </linearGradient>
        <linearGradient id="genesis-canopy-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#b86d68" />
          <stop offset="1" stop-color="#944240" />
        </linearGradient>
        <linearGradient id="genesis-canopy-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#944240" />
          <stop offset="1" stop-color="#701818" />
        </linearGradient>
        <linearGradient id="genesis-mound-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#c8f0a8" />
          <stop offset="1" stop-color="#a6d48e" />
        </linearGradient>
        <linearGradient id="genesis-mound-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#84b873" />
          <stop offset="1" stop-color="#619b58" />
        </linearGradient>
        <linearGradient id="genesis-mound-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#619b58" />
          <stop offset="1" stop-color="#3f7f3e" />
        </linearGradient>
      </defs>
      <Tile prefix="genesis" glow="#ff5c5c" />
      <ellipse cx="16" cy="19.2" rx="8" ry="3.4" fill="#2e5a2e" opacity="0.5" />
      <polygon points="14.9,15.4 15.4,13.1 17.7,13.3 19.3,15.8" fill="url(#genesis-mound-2)" />
      <polygon points="10.9,16.4 13.3,13.6 15.4,13.1 14.9,15.4" fill="url(#genesis-mound-3)" />
      <polygon points="19.3,15.8 17.7,13.3 19.4,14.1 22.4,17.4" fill="url(#genesis-mound-2)" />
      <polygon points="21.1,21.6 17.1,22.6 12.7,22.2 9.6,20.6 8.9,18.4 10.9,16.4 14.9,15.4 19.3,15.8 22.4,17.4 23.1,19.6" fill="url(#genesis-mound-0)" />
      <polygon points="16.8,15.4 15.7,15.5 14.9,15.1 15.2,14.6 16.3,14.5 17.1,14.9" fill="url(#genesis-bark-0)" />
      <polygon points="15.2,14.6 15.4,10.7 16.2,10.6 16.3,14.5" fill="url(#genesis-bark-2)" />
      <polygon points="16.3,14.5 16.2,10.6 16.8,10.9 17.1,14.9" fill="url(#genesis-bark-0)" />
      <polygon points="14.9,15.1 15.2,11.1 15.4,10.7 15.2,14.6" fill="url(#genesis-bark-3)" />
      <polygon points="15.5,9.7 16.0,4.2 19.0,10.3" fill="url(#genesis-canopy-2)" />
      <polygon points="12.4,10.7 16.0,4.2 15.5,9.7" fill="url(#genesis-canopy-3)" />
      <polygon points="18.3,13.6 14.6,13.8 12.0,12.5 12.4,10.7 15.5,9.7 19.0,10.3 20.2,12.0" fill="url(#genesis-canopy-0)" />
    </svg>
  );
}

/** Azure Heart: a cut heart hovering over the tile. */
export function AzureHeartIcon(): JSX.Element {
  return (
    <svg class="relics-gem" viewBox="0 0 32 32" aria-hidden="true">
      <defs>
        <linearGradient id="azure-heart-gem-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#d8f4ff" />
          <stop offset="1" stop-color="#a7cee1" />
        </linearGradient>
        <linearGradient id="azure-heart-gem-1" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#a7cee1" />
          <stop offset="1" stop-color="#76a8c4" />
        </linearGradient>
        <linearGradient id="azure-heart-gem-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#76a8c4" />
          <stop offset="1" stop-color="#4682a6" />
        </linearGradient>
        <linearGradient id="azure-heart-gem-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#4682a6" />
          <stop offset="1" stop-color="#155c88" />
        </linearGradient>
      </defs>
      <Tile prefix="azure-heart" glow="#4fc3f7" />
      <ellipse cx="16" cy="19.2" rx="6" ry="2.6" fill="#2e5a2e" opacity="0.5" />
      <polygon points="12.1,15.4 12.1,14.0 16.0,17.5 16.0,18.9" fill="url(#azure-heart-gem-1)" />
      <polygon points="16.0,18.9 16.0,17.5 19.9,14.0 19.9,15.4" fill="url(#azure-heart-gem-0)" />
      <polygon points="19.9,15.4 19.9,14.0 22.0,10.6 22.0,12.0" fill="url(#azure-heart-gem-0)" />
      <polygon points="10.0,12.0 10.0,10.6 12.1,14.0 12.1,15.4" fill="url(#azure-heart-gem-2)" />
      <polygon points="16.0,17.5 12.1,14.0 10.0,10.6 9.4,7.6 10.3,5.5 12.4,4.7 13.7,4.9 14.7,5.3 15.4,6.1 15.8,6.9 16.0,7.9 16.2,6.9 16.6,6.1 17.3,5.3 18.3,4.9 19.6,4.7 21.7,5.5 22.6,7.6 22.0,10.6 19.9,14.0" fill="url(#azure-heart-gem-1)" />
      <polygon points="22.0,12.0 22.0,10.6 22.6,7.6 22.6,9.0" fill="url(#azure-heart-gem-0)" />
      <polygon points="9.4,9.0 9.4,7.6 10.0,10.6 10.0,12.0" fill="url(#azure-heart-gem-3)" />
    </svg>
  );
}

/** Spring of Aether: a basin with a column of water welling up from it. */
export function SpringOfAetherIcon(): JSX.Element {
  return (
    <svg class="relics-gem" viewBox="0 0 32 32" aria-hidden="true">
      <defs>
        <linearGradient id="spring-stone-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#e6dcc8" />
          <stop offset="1" stop-color="#c7bca7" />
        </linearGradient>
        <linearGradient id="spring-stone-1" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#c7bca7" />
          <stop offset="1" stop-color="#a89b86" />
        </linearGradient>
        <linearGradient id="spring-stone-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#a89b86" />
          <stop offset="1" stop-color="#897a66" />
        </linearGradient>
        <linearGradient id="spring-stone-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#897a66" />
          <stop offset="1" stop-color="#6a5a45" />
        </linearGradient>
        <linearGradient id="spring-water-0" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#e2f7ff" />
          <stop offset="1" stop-color="#b0d5e7" />
        </linearGradient>
        <linearGradient id="spring-water-1" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#b0d5e7" />
          <stop offset="1" stop-color="#7eb3d0" />
        </linearGradient>
        <linearGradient id="spring-water-2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#7eb3d0" />
          <stop offset="1" stop-color="#4c91b8" />
        </linearGradient>
        <linearGradient id="spring-water-3" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#4c91b8" />
          <stop offset="1" stop-color="#1a6fa0" />
        </linearGradient>
      </defs>
      <Tile prefix="spring" glow="#4fc3f7" />
      <ellipse cx="16" cy="19.2" rx="7" ry="3.2" fill="#2e5a2e" opacity="0.5" />
      <polygon points="12.5,15.3 12.1,13.5 17.3,13.1 17.2,15.0" fill="url(#spring-stone-1)" />
      <polygon points="13.3,16.1 12.5,15.3 17.2,15.0 16.9,15.8" fill="url(#spring-stone-0)" />
      <polygon points="17.2,15.0 17.3,13.1 22.1,14.3 21.5,16.0" fill="url(#spring-stone-0)" />
      <polygon points="12.1,13.5 12.5,12.5 17.2,12.1 17.3,13.1" fill="url(#spring-stone-2)" />
      <polygon points="16.9,15.8 17.2,15.0 21.5,16.0 20.2,16.7" fill="url(#spring-stone-0)" />
      <polygon points="17.3,13.1 17.2,12.1 21.5,13.2 22.1,14.3" fill="url(#spring-stone-1)" />
      <polygon points="9.1,17.0 8.3,15.4 12.1,13.5 12.5,15.3" fill="url(#spring-stone-1)" />
      <polygon points="10.7,17.4 9.1,17.0 12.5,15.3 13.3,16.1" fill="url(#spring-stone-0)" />
      <polygon points="8.3,15.4 9.1,14.1 12.5,12.5 12.1,13.5" fill="url(#spring-stone-3)" />
      <polygon points="21.5,16.0 22.1,14.3 24.5,16.7 23.6,18.2" fill="url(#spring-stone-0)" />
      <polygon points="20.2,16.7 21.5,16.0 23.6,18.2 21.9,18.3" fill="url(#spring-stone-0)" />
      <polygon points="22.1,14.3 21.5,13.2 23.6,15.3 24.5,16.7" fill="url(#spring-stone-1)" />
      <polygon points="10.1,19.2 8.4,19.4 9.1,17.0 10.7,17.4" fill="url(#spring-stone-0)" />
      <polygon points="8.4,19.4 7.5,18.0 8.3,15.4 9.1,17.0" fill="url(#spring-stone-2)" />
      <polygon points="11.0,17.7 10.1,19.2 10.7,17.4 11.5,16.2" fill="url(#spring-stone-0)" />
      <polygon points="21.9,18.3 23.6,18.2 22.9,20.5 21.3,20.1" fill="url(#spring-stone-0)" />
      <polygon points="18.0,18.3 16.0,18.8 14.0,18.3 13.1,17.3 14.0,16.3 16.0,15.9 18.0,16.3 18.9,17.3" fill="url(#spring-water-0)" />
      <polygon points="21.0,16.9 21.9,18.3 21.3,20.1 20.5,18.5" fill="url(#spring-stone-2)" />
      <polygon points="23.6,18.2 24.5,16.7 23.7,19.3 22.9,20.5" fill="url(#spring-stone-0)" />
      <polygon points="16.0,15.9 16.0,7.1 17.2,7.4 18.0,16.3" fill="url(#spring-water-1)" />
      <polygon points="14.0,16.3 14.8,7.4 16.0,7.1 16.0,15.9" fill="url(#spring-water-2)" />
      <polygon points="12.4,19.1 11.8,20.9 10.1,19.2 11.0,17.7" fill="url(#spring-stone-0)" />
      <polygon points="11.8,20.9 10.5,21.5 8.4,19.4 10.1,19.2" fill="url(#spring-stone-0)" />
      <polygon points="18.0,16.3 17.2,7.4 17.8,8.0 18.9,17.3" fill="url(#spring-water-0)" />
      <polygon points="13.1,17.3 14.2,8.0 14.8,7.4 14.0,16.3" fill="url(#spring-water-3)" />
      <polygon points="11.8,18.0 12.4,19.1 11.0,17.7 10.1,16.4" fill="url(#spring-stone-1)" />
      <polygon points="20.5,18.5 21.3,20.1 18.7,21.4 18.3,19.6" fill="url(#spring-stone-1)" />
      <polygon points="21.3,20.1 22.9,20.5 19.5,22.2 18.7,21.4" fill="url(#spring-stone-0)" />
      <polygon points="15.2,19.8 15.1,21.7 11.8,20.9 12.4,19.1" fill="url(#spring-stone-0)" />
      <polygon points="21.3,17.2 20.5,18.5 18.3,19.6 18.7,18.5" fill="url(#spring-stone-3)" />
      <polygon points="17.3,5.5 16.9,8.2 15.1,8.2 14.7,5.5" fill="url(#spring-water-1)" />
      <polygon points="16.9,8.2 16.0,10.2 15.1,8.2" fill="url(#spring-water-0)" />
      <polygon points="18.3,19.6 18.7,21.4 15.1,21.7 15.2,19.8" fill="url(#spring-stone-1)" />
      <polygon points="15.1,21.7 14.8,22.6 10.5,21.5 11.8,20.9" fill="url(#spring-stone-0)" />
      <polygon points="15.1,8.2 16.0,10.2 13.8,8.8" fill="url(#spring-water-0)" />
      <polygon points="18.2,8.8 16.0,10.2 16.9,8.2" fill="url(#spring-water-0)" />
      <polygon points="14.7,5.5 15.1,8.2 13.8,8.8 12.9,6.4" fill="url(#spring-water-2)" />
      <polygon points="19.1,6.4 18.2,8.8 16.9,8.2 17.3,5.5" fill="url(#spring-water-0)" />
      <polygon points="15.1,18.8 15.2,19.8 12.4,19.1 11.8,18.0" fill="url(#spring-stone-1)" />
      <polygon points="18.7,21.4 19.5,22.2 14.8,22.6 15.1,21.7" fill="url(#spring-stone-0)" />
      <polygon points="18.7,18.5 18.3,19.6 15.2,19.8 15.1,18.8" fill="url(#spring-stone-2)" />
      <polygon points="13.8,8.8 16.0,10.2 13.8,9.7" fill="url(#spring-water-1)" />
      <polygon points="18.2,9.7 16.0,10.2 18.2,8.8" fill="url(#spring-water-0)" />
      <polygon points="16.9,3.8 17.3,5.5 14.7,5.5 15.1,3.8" fill="url(#spring-water-2)" />
      <polygon points="15.1,3.8 14.7,5.5 12.9,6.4 13.8,4.4" fill="url(#spring-water-3)" />
      <polygon points="18.2,4.4 19.1,6.4 17.3,5.5 16.9,3.8" fill="url(#spring-water-1)" />
      <polygon points="13.8,9.7 16.0,10.2 15.1,10.3" fill="url(#spring-water-1)" />
      <polygon points="16.9,10.3 16.0,10.2 18.2,9.7" fill="url(#spring-water-0)" />
      <polygon points="12.9,6.4 13.8,8.8 13.8,9.7 12.9,7.7" fill="url(#spring-water-2)" />
      <polygon points="19.1,7.7 18.2,9.7 18.2,8.8 19.1,6.4" fill="url(#spring-water-0)" />
      <polygon points="15.1,10.3 16.0,10.2 16.9,10.3" fill="url(#spring-water-0)" />
      <polygon points="14.9,3.9 16.0,1.1 16.4,3.7" fill="url(#spring-water-2)" />
      <polygon points="17.1,5.0 15.6,5.2 14.5,4.6 14.9,3.9 16.4,3.7 17.5,4.2" fill="url(#spring-water-0)" />
      <polygon points="16.4,3.7 16.0,1.1 17.5,4.2" fill="url(#spring-water-1)" />
    </svg>
  );
}
