import { mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

/**
 * Perf rigs keep their fixtures in the checkout, never the home directory: two
 * checkouts sharing one snapshot silently measure different worlds.
 */
export const PERF_DIR = fileURLToPath(new URL('../../../.terrace-perf/', import.meta.url));

export const PERF_SNAPSHOT = `${PERF_DIR}snapshot.json`;

/** The owner's own world, blessed by hand — never regenerated by a rig. */
export const PERF_OWNER_SNAPSHOT = `${PERF_DIR}snapshot.owner.json`;

export const PERF_CPU_PROFILE = `${PERF_DIR}client.cpuprofile`;

/** `writeFileSync` will not make the parent, so the generator makes it first. */
export function ensurePerfDir(): void {
  mkdirSync(PERF_DIR, { recursive: true });
}
