import { BOAT_SPEED_CELLS_PER_SECOND } from '../protocol.ts';

export const CYCLONE_DAMAGE_EVENT_NAME = 'cyclone:damage';

export const BOAT_WIND_PUSH_FRACTION_OF_TOP_SPEED = 1.5;

export const BOAT_WIND_PUSH_CELLS_PER_SEVERITY_SECOND =
  BOAT_SPEED_CELLS_PER_SECOND * BOAT_WIND_PUSH_FRACTION_OF_TOP_SPEED;

export const BOAT_WIND_PUSH_STEP_CELLS = 1;
